/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftTaskUpdateRequest
        implements org.apache.thrift.TBase<ThriftTaskUpdateRequest, ThriftTaskUpdateRequest._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftTaskUpdateRequest>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftTaskUpdateRequest");

    private static final org.apache.thrift.protocol.TField SESSION_FIELD_DESC = new org.apache.thrift.protocol.TField("session", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
    private static final org.apache.thrift.protocol.TField EXTRA_CREDENTIALS_FIELD_DESC = new org.apache.thrift.protocol.TField("extraCredentials", org.apache.thrift.protocol.TType.MAP, (short) 2);
    private static final org.apache.thrift.protocol.TField FRAGMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("fragment", org.apache.thrift.protocol.TType.STRING, (short) 3);
    private static final org.apache.thrift.protocol.TField SOURCES_FIELD_DESC = new org.apache.thrift.protocol.TField("sources", org.apache.thrift.protocol.TType.LIST, (short) 4);
    private static final org.apache.thrift.protocol.TField OUTPUT_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("outputIds", org.apache.thrift.protocol.TType.STRUCT, (short) 5);
    private static final org.apache.thrift.protocol.TField TABLE_WRITE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("tableWriteInfo", org.apache.thrift.protocol.TType.STRUCT, (short) 6);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftTaskUpdateRequestStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftTaskUpdateRequestTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable ThriftSessionRepresentation session; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<String, String> extraCredentials; // required
    public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer fragment; // optional
    public @org.apache.thrift.annotation.Nullable java.util.List<ThriftTaskSource> sources; // required
    public @org.apache.thrift.annotation.Nullable ThriftOutputBuffers outputIds; // required
    public @org.apache.thrift.annotation.Nullable ThriftTableWriteInfo tableWriteInfo; // optional

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        SESSION((short) 1, "session"),
        EXTRA_CREDENTIALS((short) 2, "extraCredentials"),
        FRAGMENT((short) 3, "fragment"),
        SOURCES((short) 4, "sources"),
        OUTPUT_IDS((short) 5, "outputIds"),
        TABLE_WRITE_INFO((short) 6, "tableWriteInfo");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // SESSION
                    return SESSION;
                case 2: // EXTRA_CREDENTIALS
                    return EXTRA_CREDENTIALS;
                case 3: // FRAGMENT
                    return FRAGMENT;
                case 4: // SOURCES
                    return SOURCES;
                case 5: // OUTPUT_IDS
                    return OUTPUT_IDS;
                case 6: // TABLE_WRITE_INFO
                    return TABLE_WRITE_INFO;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) {
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final _Fields optionals[] = {_Fields.FRAGMENT, _Fields.TABLE_WRITE_INFO};
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.SESSION, new org.apache.thrift.meta_data.FieldMetaData("session", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftSessionRepresentation.class)));
        tmpMap.put(_Fields.EXTRA_CREDENTIALS, new org.apache.thrift.meta_data.FieldMetaData("extraCredentials", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
        tmpMap.put(_Fields.FRAGMENT, new org.apache.thrift.meta_data.FieldMetaData("fragment", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, true)));
        tmpMap.put(_Fields.SOURCES, new org.apache.thrift.meta_data.FieldMetaData("sources", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTaskSource.class))));
        tmpMap.put(_Fields.OUTPUT_IDS, new org.apache.thrift.meta_data.FieldMetaData("outputIds", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftOutputBuffers.class)));
        tmpMap.put(_Fields.TABLE_WRITE_INFO, new org.apache.thrift.meta_data.FieldMetaData("tableWriteInfo", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTableWriteInfo.class)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftTaskUpdateRequest.class, metaDataMap);
    }

    public ThriftTaskUpdateRequest()
    {
    }

    public ThriftTaskUpdateRequest(
            ThriftSessionRepresentation session,
            java.util.Map<String, String> extraCredentials,
            java.util.List<ThriftTaskSource> sources,
            ThriftOutputBuffers outputIds)
    {
        this();
        this.session = session;
        this.extraCredentials = extraCredentials;
        this.sources = sources;
        this.outputIds = outputIds;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftTaskUpdateRequest(ThriftTaskUpdateRequest other)
    {
        if (other.isSetSession()) {
            this.session = new ThriftSessionRepresentation(other.session);
        }
        if (other.isSetExtraCredentials()) {
            java.util.Map<String, String> __this__extraCredentials = new java.util.HashMap<String, String>(other.extraCredentials);
            this.extraCredentials = __this__extraCredentials;
        }
        if (other.isSetFragment()) {
            this.fragment = org.apache.thrift.TBaseHelper.copyBinary(other.fragment);
        }
        if (other.isSetSources()) {
            java.util.List<ThriftTaskSource> __this__sources = new java.util.ArrayList<ThriftTaskSource>(other.sources.size());
            for (ThriftTaskSource other_element : other.sources) {
                __this__sources.add(new ThriftTaskSource(other_element));
            }
            this.sources = __this__sources;
        }
        if (other.isSetOutputIds()) {
            this.outputIds = new ThriftOutputBuffers(other.outputIds);
        }
        if (other.isSetTableWriteInfo()) {
            this.tableWriteInfo = new ThriftTableWriteInfo(other.tableWriteInfo);
        }
    }

    @Override
    public ThriftTaskUpdateRequest deepCopy()
    {
        return new ThriftTaskUpdateRequest(this);
    }

    @Override
    public void clear()
    {
        this.session = null;
        this.extraCredentials = null;
        this.fragment = null;
        this.sources = null;
        this.outputIds = null;
        this.tableWriteInfo = null;
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftSessionRepresentation getSession()
    {
        return this.session;
    }

    public ThriftTaskUpdateRequest setSession(@org.apache.thrift.annotation.Nullable ThriftSessionRepresentation session)
    {
        this.session = session;
        return this;
    }

    public void unsetSession()
    {
        this.session = null;
    }

    /**
     * Returns true if field session is set (has been assigned a value) and false otherwise
     */
    public boolean isSetSession()
    {
        return this.session != null;
    }

    public void setSessionIsSet(boolean value)
    {
        if (!value) {
            this.session = null;
        }
    }

    public int getExtraCredentialsSize()
    {
        return (this.extraCredentials == null) ? 0 : this.extraCredentials.size();
    }

    public void putToExtraCredentials(String key, String val)
    {
        if (this.extraCredentials == null) {
            this.extraCredentials = new java.util.HashMap<String, String>();
        }
        this.extraCredentials.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<String, String> getExtraCredentials()
    {
        return this.extraCredentials;
    }

    public ThriftTaskUpdateRequest setExtraCredentials(@org.apache.thrift.annotation.Nullable java.util.Map<String, String> extraCredentials)
    {
        this.extraCredentials = extraCredentials;
        return this;
    }

    public void unsetExtraCredentials()
    {
        this.extraCredentials = null;
    }

    /**
     * Returns true if field extraCredentials is set (has been assigned a value) and false otherwise
     */
    public boolean isSetExtraCredentials()
    {
        return this.extraCredentials != null;
    }

    public void setExtraCredentialsIsSet(boolean value)
    {
        if (!value) {
            this.extraCredentials = null;
        }
    }

    public byte[] getFragment()
    {
        setFragment(org.apache.thrift.TBaseHelper.rightSize(fragment));
        return fragment == null ? null : fragment.array();
    }

    public java.nio.ByteBuffer bufferForFragment()
    {
        return org.apache.thrift.TBaseHelper.copyBinary(fragment);
    }

    public ThriftTaskUpdateRequest setFragment(byte[] fragment)
    {
        this.fragment = fragment == null ? (java.nio.ByteBuffer) null : java.nio.ByteBuffer.wrap(fragment.clone());
        return this;
    }

    public ThriftTaskUpdateRequest setFragment(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer fragment)
    {
        this.fragment = org.apache.thrift.TBaseHelper.copyBinary(fragment);
        return this;
    }

    public void unsetFragment()
    {
        this.fragment = null;
    }

    /**
     * Returns true if field fragment is set (has been assigned a value) and false otherwise
     */
    public boolean isSetFragment()
    {
        return this.fragment != null;
    }

    public void setFragmentIsSet(boolean value)
    {
        if (!value) {
            this.fragment = null;
        }
    }

    public int getSourcesSize()
    {
        return (this.sources == null) ? 0 : this.sources.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftTaskSource> getSourcesIterator()
    {
        return (this.sources == null) ? null : this.sources.iterator();
    }

    public void addToSources(ThriftTaskSource elem)
    {
        if (this.sources == null) {
            this.sources = new java.util.ArrayList<ThriftTaskSource>();
        }
        this.sources.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<ThriftTaskSource> getSources()
    {
        return this.sources;
    }

    public ThriftTaskUpdateRequest setSources(@org.apache.thrift.annotation.Nullable java.util.List<ThriftTaskSource> sources)
    {
        this.sources = sources;
        return this;
    }

    public void unsetSources()
    {
        this.sources = null;
    }

    /**
     * Returns true if field sources is set (has been assigned a value) and false otherwise
     */
    public boolean isSetSources()
    {
        return this.sources != null;
    }

    public void setSourcesIsSet(boolean value)
    {
        if (!value) {
            this.sources = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftOutputBuffers getOutputIds()
    {
        return this.outputIds;
    }

    public ThriftTaskUpdateRequest setOutputIds(@org.apache.thrift.annotation.Nullable ThriftOutputBuffers outputIds)
    {
        this.outputIds = outputIds;
        return this;
    }

    public void unsetOutputIds()
    {
        this.outputIds = null;
    }

    /**
     * Returns true if field outputIds is set (has been assigned a value) and false otherwise
     */
    public boolean isSetOutputIds()
    {
        return this.outputIds != null;
    }

    public void setOutputIdsIsSet(boolean value)
    {
        if (!value) {
            this.outputIds = null;
        }
    }

    public java.util.Optional<ThriftTableWriteInfo> getTableWriteInfo()
    {
        if (this.isSetTableWriteInfo()) {
            return java.util.Optional.of(this.tableWriteInfo);
        }
        else {
            return java.util.Optional.empty();
        }
    }

    public ThriftTaskUpdateRequest setTableWriteInfo(@org.apache.thrift.annotation.Nullable ThriftTableWriteInfo tableWriteInfo)
    {
        this.tableWriteInfo = tableWriteInfo;
        return this;
    }

    public void unsetTableWriteInfo()
    {
        this.tableWriteInfo = null;
    }

    /**
     * Returns true if field tableWriteInfo is set (has been assigned a value) and false otherwise
     */
    public boolean isSetTableWriteInfo()
    {
        return this.tableWriteInfo != null;
    }

    public void setTableWriteInfoIsSet(boolean value)
    {
        if (!value) {
            this.tableWriteInfo = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case SESSION:
                if (value == null) {
                    unsetSession();
                }
                else {
                    setSession((ThriftSessionRepresentation) value);
                }
                break;

            case EXTRA_CREDENTIALS:
                if (value == null) {
                    unsetExtraCredentials();
                }
                else {
                    setExtraCredentials((java.util.Map<String, String>) value);
                }
                break;

            case FRAGMENT:
                if (value == null) {
                    unsetFragment();
                }
                else {
                    if (value instanceof byte[]) {
                        setFragment((byte[]) value);
                    }
                    else {
                        setFragment((java.nio.ByteBuffer) value);
                    }
                }
                break;

            case SOURCES:
                if (value == null) {
                    unsetSources();
                }
                else {
                    setSources((java.util.List<ThriftTaskSource>) value);
                }
                break;

            case OUTPUT_IDS:
                if (value == null) {
                    unsetOutputIds();
                }
                else {
                    setOutputIds((ThriftOutputBuffers) value);
                }
                break;

            case TABLE_WRITE_INFO:
                if (value == null) {
                    unsetTableWriteInfo();
                }
                else {
                    setTableWriteInfo((ThriftTableWriteInfo) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case SESSION:
                return getSession();

            case EXTRA_CREDENTIALS:
                return getExtraCredentials();

            case FRAGMENT:
                return getFragment();

            case SOURCES:
                return getSources();

            case OUTPUT_IDS:
                return getOutputIds();

            case TABLE_WRITE_INFO:
                return getTableWriteInfo();
        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case SESSION:
                return isSetSession();
            case EXTRA_CREDENTIALS:
                return isSetExtraCredentials();
            case FRAGMENT:
                return isSetFragment();
            case SOURCES:
                return isSetSources();
            case OUTPUT_IDS:
                return isSetOutputIds();
            case TABLE_WRITE_INFO:
                return isSetTableWriteInfo();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
        if (that instanceof ThriftTaskUpdateRequest) {
            return this.equals((ThriftTaskUpdateRequest) that);
        }
        return false;
    }

    public boolean equals(ThriftTaskUpdateRequest that)
    {
        if (that == null) {
            return false;
        }
        if (this == that) {
            return true;
        }

        boolean this_present_session = true && this.isSetSession();
        boolean that_present_session = true && that.isSetSession();
        if (this_present_session || that_present_session) {
            if (!(this_present_session && that_present_session)) {
                return false;
            }
            if (!this.session.equals(that.session)) {
                return false;
            }
        }

        boolean this_present_extraCredentials = true && this.isSetExtraCredentials();
        boolean that_present_extraCredentials = true && that.isSetExtraCredentials();
        if (this_present_extraCredentials || that_present_extraCredentials) {
            if (!(this_present_extraCredentials && that_present_extraCredentials)) {
                return false;
            }
            if (!this.extraCredentials.equals(that.extraCredentials)) {
                return false;
            }
        }

        boolean this_present_fragment = true && this.isSetFragment();
        boolean that_present_fragment = true && that.isSetFragment();
        if (this_present_fragment || that_present_fragment) {
            if (!(this_present_fragment && that_present_fragment)) {
                return false;
            }
            if (!this.fragment.equals(that.fragment)) {
                return false;
            }
        }

        boolean this_present_sources = true && this.isSetSources();
        boolean that_present_sources = true && that.isSetSources();
        if (this_present_sources || that_present_sources) {
            if (!(this_present_sources && that_present_sources)) {
                return false;
            }
            if (!this.sources.equals(that.sources)) {
                return false;
            }
        }

        boolean this_present_outputIds = true && this.isSetOutputIds();
        boolean that_present_outputIds = true && that.isSetOutputIds();
        if (this_present_outputIds || that_present_outputIds) {
            if (!(this_present_outputIds && that_present_outputIds)) {
                return false;
            }
            if (!this.outputIds.equals(that.outputIds)) {
                return false;
            }
        }

        boolean this_present_tableWriteInfo = true && this.isSetTableWriteInfo();
        boolean that_present_tableWriteInfo = true && that.isSetTableWriteInfo();
        if (this_present_tableWriteInfo || that_present_tableWriteInfo) {
            if (!(this_present_tableWriteInfo && that_present_tableWriteInfo)) {
                return false;
            }
            if (!this.tableWriteInfo.equals(that.tableWriteInfo)) {
                return false;
            }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetSession()) ? 131071 : 524287);
        if (isSetSession()) {
            hashCode = hashCode * 8191 + session.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetExtraCredentials()) ? 131071 : 524287);
        if (isSetExtraCredentials()) {
            hashCode = hashCode * 8191 + extraCredentials.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetFragment()) ? 131071 : 524287);
        if (isSetFragment()) {
            hashCode = hashCode * 8191 + fragment.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetSources()) ? 131071 : 524287);
        if (isSetSources()) {
            hashCode = hashCode * 8191 + sources.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetOutputIds()) ? 131071 : 524287);
        if (isSetOutputIds()) {
            hashCode = hashCode * 8191 + outputIds.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetTableWriteInfo()) ? 131071 : 524287);
        if (isSetTableWriteInfo()) {
            hashCode = hashCode * 8191 + tableWriteInfo.hashCode();
        }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftTaskUpdateRequest other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetSession(), other.isSetSession());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSession()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.session, other.session);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetExtraCredentials(), other.isSetExtraCredentials());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetExtraCredentials()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.extraCredentials, other.extraCredentials);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetFragment(), other.isSetFragment());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetFragment()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fragment, other.fragment);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetSources(), other.isSetSources());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSources()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sources, other.sources);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetOutputIds(), other.isSetOutputIds());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetOutputIds()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputIds, other.outputIds);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetTableWriteInfo(), other.isSetTableWriteInfo());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTableWriteInfo()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableWriteInfo, other.tableWriteInfo);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftTaskUpdateRequest(");
        boolean first = true;

        sb.append("session:");
        if (this.session == null) {
            sb.append("null");
        }
        else {
            sb.append(this.session);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("extraCredentials:");
        if (this.extraCredentials == null) {
            sb.append("null");
        }
        else {
            sb.append(this.extraCredentials);
        }
        first = false;
        if (isSetFragment()) {
            if (!first) {
                sb.append(", ");
            }
            sb.append("fragment:");
            if (this.fragment == null) {
                sb.append("null");
            }
            else {
                org.apache.thrift.TBaseHelper.toString(this.fragment, sb);
            }
            first = false;
        }
        if (!first) {
            sb.append(", ");
        }
        sb.append("sources:");
        if (this.sources == null) {
            sb.append("null");
        }
        else {
            sb.append(this.sources);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("outputIds:");
        if (this.outputIds == null) {
            sb.append("null");
        }
        else {
            sb.append(this.outputIds);
        }
        first = false;
        if (isSetTableWriteInfo()) {
            if (!first) {
                sb.append(", ");
            }
            sb.append("tableWriteInfo:");
            if (this.tableWriteInfo == null) {
                sb.append("null");
            }
            else {
                sb.append(this.tableWriteInfo);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (session != null) {
            session.validate();
        }
        if (outputIds != null) {
            outputIds.validate();
        }
        if (tableWriteInfo != null) {
            tableWriteInfo.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftTaskUpdateRequestStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskUpdateRequestStandardScheme getScheme()
        {
            return new ThriftTaskUpdateRequestStandardScheme();
        }
    }

    private static class ThriftTaskUpdateRequestStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftTaskUpdateRequest>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftTaskUpdateRequest struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // SESSION
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.session = new ThriftSessionRepresentation();
                            struct.session.read(iprot);
                            struct.setSessionIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // EXTRA_CREDENTIALS
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                                struct.extraCredentials = new java.util.HashMap<String, String>(2 * _map0.size);
                                @org.apache.thrift.annotation.Nullable String _key1;
                                @org.apache.thrift.annotation.Nullable String _val2;
                                for (int _i3 = 0; _i3 < _map0.size; ++_i3) {
                                    _key1 = iprot.readString();
                                    _val2 = iprot.readString();
                                    struct.extraCredentials.put(_key1, _val2);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setExtraCredentialsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // FRAGMENT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.fragment = iprot.readBinary();
                            struct.setFragmentIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // SOURCES
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list4 = iprot.readListBegin();
                                struct.sources = new java.util.ArrayList<ThriftTaskSource>(_list4.size);
                                @org.apache.thrift.annotation.Nullable ThriftTaskSource _elem5;
                                for (int _i6 = 0; _i6 < _list4.size; ++_i6) {
                                    _elem5 = new ThriftTaskSource();
                                    _elem5.read(iprot);
                                    struct.sources.add(_elem5);
                                }
                                iprot.readListEnd();
                            }
                            struct.setSourcesIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // OUTPUT_IDS
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.outputIds = new ThriftOutputBuffers();
                            struct.outputIds.read(iprot);
                            struct.setOutputIdsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 6: // TABLE_WRITE_INFO
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.tableWriteInfo = new ThriftTableWriteInfo();
                            struct.tableWriteInfo.read(iprot);
                            struct.setTableWriteInfoIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftTaskUpdateRequest struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.session != null) {
                oprot.writeFieldBegin(SESSION_FIELD_DESC);
                struct.session.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.extraCredentials != null) {
                oprot.writeFieldBegin(EXTRA_CREDENTIALS_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.extraCredentials.size()));
                    for (java.util.Map.Entry<String, String> _iter7 : struct.extraCredentials.entrySet()) {
                        oprot.writeString(_iter7.getKey());
                        oprot.writeString(_iter7.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.fragment != null) {
                if (struct.isSetFragment()) {
                    oprot.writeFieldBegin(FRAGMENT_FIELD_DESC);
                    oprot.writeBinary(struct.fragment);
                    oprot.writeFieldEnd();
                }
            }
            if (struct.sources != null) {
                oprot.writeFieldBegin(SOURCES_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.sources.size()));
                    for (ThriftTaskSource _iter8 : struct.sources) {
                        _iter8.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.outputIds != null) {
                oprot.writeFieldBegin(OUTPUT_IDS_FIELD_DESC);
                struct.outputIds.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.tableWriteInfo != null) {
                if (struct.isSetTableWriteInfo()) {
                    oprot.writeFieldBegin(TABLE_WRITE_INFO_FIELD_DESC);
                    struct.tableWriteInfo.write(oprot);
                    oprot.writeFieldEnd();
                }
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftTaskUpdateRequestTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskUpdateRequestTupleScheme getScheme()
        {
            return new ThriftTaskUpdateRequestTupleScheme();
        }
    }

    private static class ThriftTaskUpdateRequestTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftTaskUpdateRequest>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftTaskUpdateRequest struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetSession()) {
                optionals.set(0);
            }
            if (struct.isSetExtraCredentials()) {
                optionals.set(1);
            }
            if (struct.isSetFragment()) {
                optionals.set(2);
            }
            if (struct.isSetSources()) {
                optionals.set(3);
            }
            if (struct.isSetOutputIds()) {
                optionals.set(4);
            }
            if (struct.isSetTableWriteInfo()) {
                optionals.set(5);
            }
            oprot.writeBitSet(optionals, 6);
            if (struct.isSetSession()) {
                struct.session.write(oprot);
            }
            if (struct.isSetExtraCredentials()) {
                {
                    oprot.writeI32(struct.extraCredentials.size());
                    for (java.util.Map.Entry<String, String> _iter9 : struct.extraCredentials.entrySet()) {
                        oprot.writeString(_iter9.getKey());
                        oprot.writeString(_iter9.getValue());
                    }
                }
            }
            if (struct.isSetFragment()) {
                oprot.writeBinary(struct.fragment);
            }
            if (struct.isSetSources()) {
                {
                    oprot.writeI32(struct.sources.size());
                    for (ThriftTaskSource _iter10 : struct.sources) {
                        _iter10.write(oprot);
                    }
                }
            }
            if (struct.isSetOutputIds()) {
                struct.outputIds.write(oprot);
            }
            if (struct.isSetTableWriteInfo()) {
                struct.tableWriteInfo.write(oprot);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftTaskUpdateRequest struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(6);
            if (incoming.get(0)) {
                struct.session = new ThriftSessionRepresentation();
                struct.session.read(iprot);
                struct.setSessionIsSet(true);
            }
            if (incoming.get(1)) {
                {
                    org.apache.thrift.protocol.TMap _map11 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING);
                    struct.extraCredentials = new java.util.HashMap<String, String>(2 * _map11.size);
                    @org.apache.thrift.annotation.Nullable String _key12;
                    @org.apache.thrift.annotation.Nullable String _val13;
                    for (int _i14 = 0; _i14 < _map11.size; ++_i14) {
                        _key12 = iprot.readString();
                        _val13 = iprot.readString();
                        struct.extraCredentials.put(_key12, _val13);
                    }
                }
                struct.setExtraCredentialsIsSet(true);
            }
            if (incoming.get(2)) {
                struct.fragment = iprot.readBinary();
                struct.setFragmentIsSet(true);
            }
            if (incoming.get(3)) {
                {
                    org.apache.thrift.protocol.TList _list15 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.sources = new java.util.ArrayList<ThriftTaskSource>(_list15.size);
                    @org.apache.thrift.annotation.Nullable ThriftTaskSource _elem16;
                    for (int _i17 = 0; _i17 < _list15.size; ++_i17) {
                        _elem16 = new ThriftTaskSource();
                        _elem16.read(iprot);
                        struct.sources.add(_elem16);
                    }
                }
                struct.setSourcesIsSet(true);
            }
            if (incoming.get(4)) {
                struct.outputIds = new ThriftOutputBuffers();
                struct.outputIds.read(iprot);
                struct.setOutputIdsIsSet(true);
            }
            if (incoming.get(5)) {
                struct.tableWriteInfo = new ThriftTableWriteInfo();
                struct.tableWriteInfo.read(iprot);
                struct.setTableWriteInfoIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

