/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftTypeSignatureParameter
        implements org.apache.thrift.TBase<ThriftTypeSignatureParameter, ThriftTypeSignatureParameter._Fields>, java.io.Serializable, Cloneable,
        Comparable<ThriftTypeSignatureParameter>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftTypeSignatureParameter");

    private static final org.apache.thrift.protocol.TField KIND_FIELD_DESC = new org.apache.thrift.protocol.TField("kind", org.apache.thrift.protocol.TType.I32, (short) 1);
    private static final org.apache.thrift.protocol.TField THRIFT_TYPE_SIGNATURE_PARAMETER_UNION_FIELD_DESC = new org.apache.thrift.protocol.TField("thriftTypeSignatureParameterUnion", org.apache.thrift.protocol.TType.STRUCT, (short) 2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftTypeSignatureParameterStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftTypeSignatureParameterTupleSchemeFactory();

    /**
     *
     * @see ThriftParameterKind
     */
    public @org.apache.thrift.annotation.Nullable ThriftParameterKind kind; // required
    public @org.apache.thrift.annotation.Nullable ThriftTypeSignatureParameterUnion thriftTypeSignatureParameterUnion; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        /**
         *
         * @see ThriftParameterKind
         */
        KIND((short) 1, "kind"),
        THRIFT_TYPE_SIGNATURE_PARAMETER_UNION((short) 2, "thriftTypeSignatureParameterUnion");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // KIND
                    return KIND;
                case 2: // THRIFT_TYPE_SIGNATURE_PARAMETER_UNION
                    return THRIFT_TYPE_SIGNATURE_PARAMETER_UNION;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.KIND, new org.apache.thrift.meta_data.FieldMetaData("kind", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftParameterKind.class)));
        tmpMap.put(_Fields.THRIFT_TYPE_SIGNATURE_PARAMETER_UNION, new org.apache.thrift.meta_data.FieldMetaData("thriftTypeSignatureParameterUnion", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeSignatureParameterUnion.class)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftTypeSignatureParameter.class, metaDataMap);
    }

    public ThriftTypeSignatureParameter()
    {
    }

    public ThriftTypeSignatureParameter(
            ThriftParameterKind kind,
            ThriftTypeSignatureParameterUnion thriftTypeSignatureParameterUnion)
    {
        this();
        this.kind = kind;
        this.thriftTypeSignatureParameterUnion = thriftTypeSignatureParameterUnion;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftTypeSignatureParameter(ThriftTypeSignatureParameter other)
    {
        if (other.isSetKind()) {
            this.kind = other.kind;
        }
        if (other.isSetThriftTypeSignatureParameterUnion()) {
            this.thriftTypeSignatureParameterUnion = new ThriftTypeSignatureParameterUnion(other.thriftTypeSignatureParameterUnion);
        }
    }

    @Override
    public ThriftTypeSignatureParameter deepCopy()
    {
        return new ThriftTypeSignatureParameter(this);
    }

    @Override
    public void clear()
    {
        this.kind = null;
        this.thriftTypeSignatureParameterUnion = null;
    }

    /**
     *
     * @see ThriftParameterKind
     */
    @org.apache.thrift.annotation.Nullable
    public ThriftParameterKind getKind()
    {
        return this.kind;
    }

    /**
     *
     * @see ThriftParameterKind
     */
    public ThriftTypeSignatureParameter setKind(@org.apache.thrift.annotation.Nullable ThriftParameterKind kind)
    {
        this.kind = kind;
        return this;
    }

    public void unsetKind()
    {
        this.kind = null;
    }

    /** Returns true if field kind is set (has been assigned a value) and false otherwise */
    public boolean isSetKind()
    {
        return this.kind != null;
    }

    public void setKindIsSet(boolean value)
    {
        if (!value) {
            this.kind = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftTypeSignatureParameterUnion getThriftTypeSignatureParameterUnion()
    {
        return this.thriftTypeSignatureParameterUnion;
    }

    public ThriftTypeSignatureParameter setThriftTypeSignatureParameterUnion(@org.apache.thrift.annotation.Nullable ThriftTypeSignatureParameterUnion thriftTypeSignatureParameterUnion)
    {
        this.thriftTypeSignatureParameterUnion = thriftTypeSignatureParameterUnion;
        return this;
    }

    public void unsetThriftTypeSignatureParameterUnion()
    {
        this.thriftTypeSignatureParameterUnion = null;
    }

    /** Returns true if field thriftTypeSignatureParameterUnion is set (has been assigned a value) and false otherwise */
    public boolean isSetThriftTypeSignatureParameterUnion()
    {
        return this.thriftTypeSignatureParameterUnion != null;
    }

    public void setThriftTypeSignatureParameterUnionIsSet(boolean value)
    {
        if (!value) {
            this.thriftTypeSignatureParameterUnion = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case KIND:
                if (value == null) {
                    unsetKind();
                }
                else {
                    setKind((ThriftParameterKind) value);
                }
                break;

            case THRIFT_TYPE_SIGNATURE_PARAMETER_UNION:
                if (value == null) {
                    unsetThriftTypeSignatureParameterUnion();
                }
                else {
                    setThriftTypeSignatureParameterUnion((ThriftTypeSignatureParameterUnion) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case KIND:
                return getKind();

            case THRIFT_TYPE_SIGNATURE_PARAMETER_UNION:
                return getThriftTypeSignatureParameterUnion();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case KIND:
                return isSetKind();
            case THRIFT_TYPE_SIGNATURE_PARAMETER_UNION:
                return isSetThriftTypeSignatureParameterUnion();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftTypeSignatureParameter) {
        return this.equals((ThriftTypeSignatureParameter) that);
      }
        return false;
    }

    public boolean equals(ThriftTypeSignatureParameter that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_kind = true && this.isSetKind();
        boolean that_present_kind = true && that.isSetKind();
        if (this_present_kind || that_present_kind) {
          if (!(this_present_kind && that_present_kind)) {
            return false;
          }
          if (!this.kind.equals(that.kind)) {
            return false;
          }
        }

        boolean this_present_thriftTypeSignatureParameterUnion = true && this.isSetThriftTypeSignatureParameterUnion();
        boolean that_present_thriftTypeSignatureParameterUnion = true && that.isSetThriftTypeSignatureParameterUnion();
        if (this_present_thriftTypeSignatureParameterUnion || that_present_thriftTypeSignatureParameterUnion) {
          if (!(this_present_thriftTypeSignatureParameterUnion && that_present_thriftTypeSignatureParameterUnion)) {
            return false;
          }
          if (!this.thriftTypeSignatureParameterUnion.equals(that.thriftTypeSignatureParameterUnion)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetKind()) ? 131071 : 524287);
      if (isSetKind()) {
        hashCode = hashCode * 8191 + kind.getValue();
      }

        hashCode = hashCode * 8191 + ((isSetThriftTypeSignatureParameterUnion()) ? 131071 : 524287);
      if (isSetThriftTypeSignatureParameterUnion()) {
        hashCode = hashCode * 8191 + thriftTypeSignatureParameterUnion.hashCode();
      }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftTypeSignatureParameter other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetKind(), other.isSetKind());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetKind()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kind, other.kind);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetThriftTypeSignatureParameterUnion(), other.isSetThriftTypeSignatureParameterUnion());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetThriftTypeSignatureParameterUnion()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.thriftTypeSignatureParameterUnion, other.thriftTypeSignatureParameterUnion);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftTypeSignatureParameter(");
        boolean first = true;

        sb.append("kind:");
        if (this.kind == null) {
            sb.append("null");
        }
        else {
            sb.append(this.kind);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("thriftTypeSignatureParameterUnion:");
        if (this.thriftTypeSignatureParameterUnion == null) {
            sb.append("null");
        }
        else {
            sb.append(this.thriftTypeSignatureParameterUnion);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftTypeSignatureParameterStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTypeSignatureParameterStandardScheme getScheme()
        {
            return new ThriftTypeSignatureParameterStandardScheme();
        }
    }

    private static class ThriftTypeSignatureParameterStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftTypeSignatureParameter>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftTypeSignatureParameter struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // KIND
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.kind = ThriftParameterKind.findByValue(iprot.readI32());
                            struct.setKindIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // THRIFT_TYPE_SIGNATURE_PARAMETER_UNION
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.thriftTypeSignatureParameterUnion = new ThriftTypeSignatureParameterUnion();
                            struct.thriftTypeSignatureParameterUnion.read(iprot);
                            struct.setThriftTypeSignatureParameterUnionIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftTypeSignatureParameter struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.kind != null) {
                oprot.writeFieldBegin(KIND_FIELD_DESC);
                oprot.writeI32(struct.kind.getValue());
                oprot.writeFieldEnd();
            }
            if (struct.thriftTypeSignatureParameterUnion != null) {
                oprot.writeFieldBegin(THRIFT_TYPE_SIGNATURE_PARAMETER_UNION_FIELD_DESC);
                struct.thriftTypeSignatureParameterUnion.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftTypeSignatureParameterTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTypeSignatureParameterTupleScheme getScheme()
        {
            return new ThriftTypeSignatureParameterTupleScheme();
        }
    }

    private static class ThriftTypeSignatureParameterTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftTypeSignatureParameter>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftTypeSignatureParameter struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetKind()) {
                optionals.set(0);
            }
            if (struct.isSetThriftTypeSignatureParameterUnion()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetKind()) {
                oprot.writeI32(struct.kind.getValue());
            }
            if (struct.isSetThriftTypeSignatureParameterUnion()) {
                struct.thriftTypeSignatureParameterUnion.write(oprot);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftTypeSignatureParameter struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.kind = ThriftParameterKind.findByValue(iprot.readI32());
                struct.setKindIsSet(true);
            }
            if (incoming.get(1)) {
                struct.thriftTypeSignatureParameterUnion = new ThriftTypeSignatureParameterUnion();
                struct.thriftTypeSignatureParameterUnion.read(iprot);
                struct.setThriftTypeSignatureParameterUnionIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

