/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftAggregationFunctionMetadata
        implements org.apache.thrift.TBase<ThriftAggregationFunctionMetadata, ThriftAggregationFunctionMetadata._Fields>, java.io.Serializable, Cloneable,
        Comparable<ThriftAggregationFunctionMetadata>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftAggregationFunctionMetadata");

    private static final org.apache.thrift.protocol.TField INTERMEDIATE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("intermediateType", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
    private static final org.apache.thrift.protocol.TField IS_ORDER_SENSITIVE_FIELD_DESC = new org.apache.thrift.protocol.TField("isOrderSensitive", org.apache.thrift.protocol.TType.BOOL, (short) 2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftAggregationFunctionMetadataStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftAggregationFunctionMetadataTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable ThriftTypeSignature intermediateType; // required
    public boolean isOrderSensitive; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        INTERMEDIATE_TYPE((short) 1, "intermediateType"),
        IS_ORDER_SENSITIVE((short) 2, "isOrderSensitive");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // INTERMEDIATE_TYPE
                    return INTERMEDIATE_TYPE;
                case 2: // IS_ORDER_SENSITIVE
                    return IS_ORDER_SENSITIVE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __ISORDERSENSITIVE_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.INTERMEDIATE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("intermediateType", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeSignature.class)));
        tmpMap.put(_Fields.IS_ORDER_SENSITIVE, new org.apache.thrift.meta_data.FieldMetaData("isOrderSensitive", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftAggregationFunctionMetadata.class, metaDataMap);
    }

    public ThriftAggregationFunctionMetadata()
    {
    }

    public ThriftAggregationFunctionMetadata(
            ThriftTypeSignature intermediateType,
            boolean isOrderSensitive)
    {
        this();
        this.intermediateType = intermediateType;
        this.isOrderSensitive = isOrderSensitive;
        setIsOrderSensitiveIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftAggregationFunctionMetadata(ThriftAggregationFunctionMetadata other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetIntermediateType()) {
            this.intermediateType = new ThriftTypeSignature(other.intermediateType);
        }
        this.isOrderSensitive = other.isOrderSensitive;
    }

    @Override
    public ThriftAggregationFunctionMetadata deepCopy()
    {
        return new ThriftAggregationFunctionMetadata(this);
    }

    @Override
    public void clear()
    {
        this.intermediateType = null;
        setIsOrderSensitiveIsSet(false);
        this.isOrderSensitive = false;
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftTypeSignature getIntermediateType()
    {
        return this.intermediateType;
    }

    public ThriftAggregationFunctionMetadata setIntermediateType(@org.apache.thrift.annotation.Nullable ThriftTypeSignature intermediateType)
    {
        this.intermediateType = intermediateType;
        return this;
    }

    public void unsetIntermediateType()
    {
        this.intermediateType = null;
    }

    /** Returns true if field intermediateType is set (has been assigned a value) and false otherwise */
    public boolean isSetIntermediateType()
    {
        return this.intermediateType != null;
    }

    public void setIntermediateTypeIsSet(boolean value)
    {
        if (!value) {
            this.intermediateType = null;
        }
    }

    public boolean isIsOrderSensitive()
    {
        return this.isOrderSensitive;
    }

    public ThriftAggregationFunctionMetadata setIsOrderSensitive(boolean isOrderSensitive)
    {
        this.isOrderSensitive = isOrderSensitive;
        setIsOrderSensitiveIsSet(true);
        return this;
    }

    public void unsetIsOrderSensitive()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISORDERSENSITIVE_ISSET_ID);
    }

    /** Returns true if field isOrderSensitive is set (has been assigned a value) and false otherwise */
    public boolean isSetIsOrderSensitive()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISORDERSENSITIVE_ISSET_ID);
    }

    public void setIsOrderSensitiveIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISORDERSENSITIVE_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case INTERMEDIATE_TYPE:
                if (value == null) {
                    unsetIntermediateType();
                }
                else {
                    setIntermediateType((ThriftTypeSignature) value);
                }
                break;

            case IS_ORDER_SENSITIVE:
                if (value == null) {
                    unsetIsOrderSensitive();
                }
                else {
                    setIsOrderSensitive((Boolean) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case INTERMEDIATE_TYPE:
                return getIntermediateType();

            case IS_ORDER_SENSITIVE:
                return isIsOrderSensitive();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case INTERMEDIATE_TYPE:
                return isSetIntermediateType();
            case IS_ORDER_SENSITIVE:
                return isSetIsOrderSensitive();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftAggregationFunctionMetadata) {
        return this.equals((ThriftAggregationFunctionMetadata) that);
      }
        return false;
    }

    public boolean equals(ThriftAggregationFunctionMetadata that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_intermediateType = true && this.isSetIntermediateType();
        boolean that_present_intermediateType = true && that.isSetIntermediateType();
        if (this_present_intermediateType || that_present_intermediateType) {
          if (!(this_present_intermediateType && that_present_intermediateType)) {
            return false;
          }
          if (!this.intermediateType.equals(that.intermediateType)) {
            return false;
          }
        }

        boolean this_present_isOrderSensitive = true;
        boolean that_present_isOrderSensitive = true;
        if (this_present_isOrderSensitive || that_present_isOrderSensitive) {
          if (!(this_present_isOrderSensitive && that_present_isOrderSensitive)) {
            return false;
          }
          if (this.isOrderSensitive != that.isOrderSensitive) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetIntermediateType()) ? 131071 : 524287);
      if (isSetIntermediateType()) {
        hashCode = hashCode * 8191 + intermediateType.hashCode();
      }

        hashCode = hashCode * 8191 + ((isOrderSensitive) ? 131071 : 524287);

        return hashCode;
    }

    @Override
    public int compareTo(ThriftAggregationFunctionMetadata other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetIntermediateType(), other.isSetIntermediateType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetIntermediateType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intermediateType, other.intermediateType);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetIsOrderSensitive(), other.isSetIsOrderSensitive());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetIsOrderSensitive()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isOrderSensitive, other.isOrderSensitive);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftAggregationFunctionMetadata(");
        boolean first = true;

        sb.append("intermediateType:");
        if (this.intermediateType == null) {
            sb.append("null");
        }
        else {
            sb.append(this.intermediateType);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("isOrderSensitive:");
        sb.append(this.isOrderSensitive);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (intermediateType != null) {
            intermediateType.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftAggregationFunctionMetadataStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftAggregationFunctionMetadataStandardScheme getScheme()
        {
            return new ThriftAggregationFunctionMetadataStandardScheme();
        }
    }

    private static class ThriftAggregationFunctionMetadataStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftAggregationFunctionMetadata>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftAggregationFunctionMetadata struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // INTERMEDIATE_TYPE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.intermediateType = new ThriftTypeSignature();
                            struct.intermediateType.read(iprot);
                            struct.setIntermediateTypeIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // IS_ORDER_SENSITIVE
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.isOrderSensitive = iprot.readBool();
                            struct.setIsOrderSensitiveIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftAggregationFunctionMetadata struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.intermediateType != null) {
                oprot.writeFieldBegin(INTERMEDIATE_TYPE_FIELD_DESC);
                struct.intermediateType.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(IS_ORDER_SENSITIVE_FIELD_DESC);
            oprot.writeBool(struct.isOrderSensitive);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftAggregationFunctionMetadataTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftAggregationFunctionMetadataTupleScheme getScheme()
        {
            return new ThriftAggregationFunctionMetadataTupleScheme();
        }
    }

    private static class ThriftAggregationFunctionMetadataTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftAggregationFunctionMetadata>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftAggregationFunctionMetadata struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetIntermediateType()) {
                optionals.set(0);
            }
            if (struct.isSetIsOrderSensitive()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetIntermediateType()) {
                struct.intermediateType.write(oprot);
            }
            if (struct.isSetIsOrderSensitive()) {
                oprot.writeBool(struct.isOrderSensitive);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftAggregationFunctionMetadata struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.intermediateType = new ThriftTypeSignature();
                struct.intermediateType.read(iprot);
                struct.setIntermediateTypeIsSet(true);
            }
            if (incoming.get(1)) {
                struct.isOrderSensitive = iprot.readBool();
                struct.setIsOrderSensitiveIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

