/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public enum ThriftParameterKind
        implements org.apache.thrift.TEnum
{
    TYPE(1),
    NAMED_TYPE(2),
    LONG(3),
    VARIABLE(4),
    LONG_ENUM(5),
    VARCHAR_ENUM(6),
    DISTINCT_TYPE(7);

    private final int value;

    private ThriftParameterKind(int value)
    {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    @Override
    public int getValue()
    {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static ThriftParameterKind findByValue(int value)
    {
        switch (value) {
            case 1:
                return TYPE;
            case 2:
                return NAMED_TYPE;
            case 3:
                return LONG;
            case 4:
                return VARIABLE;
            case 5:
                return LONG_ENUM;
            case 6:
                return VARCHAR_ENUM;
            case 7:
                return DISTINCT_TYPE;
            default:
                return null;
        }
    }
}
