/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftRoutineCharacteristics
        implements org.apache.thrift.TBase<ThriftRoutineCharacteristics, ThriftRoutineCharacteristics._Fields>, java.io.Serializable, Cloneable,
        Comparable<ThriftRoutineCharacteristics>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftRoutineCharacteristics");

    private static final org.apache.thrift.protocol.TField LANGUAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("language", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField DETERMINISM_FIELD_DESC = new org.apache.thrift.protocol.TField("determinism", org.apache.thrift.protocol.TType.I32, (short) 2);
    private static final org.apache.thrift.protocol.TField NULL_CALL_CLAUSE_FIELD_DESC = new org.apache.thrift.protocol.TField("nullCallClause", org.apache.thrift.protocol.TType.I32, (short) 3);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftRoutineCharacteristicsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftRoutineCharacteristicsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable String language; // required
    /**
     *
     * @see ThriftDeterminism
     */
    public @org.apache.thrift.annotation.Nullable ThriftDeterminism determinism; // required
    /**
     *
     * @see ThriftNullCallClause
     */
    public @org.apache.thrift.annotation.Nullable ThriftNullCallClause nullCallClause; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        LANGUAGE((short) 1, "language"),
        /**
         *
         * @see ThriftDeterminism
         */
        DETERMINISM((short) 2, "determinism"),
        /**
         *
         * @see ThriftNullCallClause
         */
        NULL_CALL_CLAUSE((short) 3, "nullCallClause");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // LANGUAGE
                    return LANGUAGE;
                case 2: // DETERMINISM
                    return DETERMINISM;
                case 3: // NULL_CALL_CLAUSE
                    return NULL_CALL_CLAUSE;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.LANGUAGE, new org.apache.thrift.meta_data.FieldMetaData("language", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftLanguage")));
        tmpMap.put(_Fields.DETERMINISM, new org.apache.thrift.meta_data.FieldMetaData("determinism", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftDeterminism.class)));
        tmpMap.put(_Fields.NULL_CALL_CLAUSE, new org.apache.thrift.meta_data.FieldMetaData("nullCallClause", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftNullCallClause.class)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftRoutineCharacteristics.class, metaDataMap);
    }

    public ThriftRoutineCharacteristics()
    {
    }

    public ThriftRoutineCharacteristics(
            String language,
            ThriftDeterminism determinism,
            ThriftNullCallClause nullCallClause)
    {
        this();
        this.language = language;
        this.determinism = determinism;
        this.nullCallClause = nullCallClause;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftRoutineCharacteristics(ThriftRoutineCharacteristics other)
    {
        if (other.isSetLanguage()) {
            this.language = other.language;
        }
        if (other.isSetDeterminism()) {
            this.determinism = other.determinism;
        }
        if (other.isSetNullCallClause()) {
            this.nullCallClause = other.nullCallClause;
        }
    }

    @Override
    public ThriftRoutineCharacteristics deepCopy()
    {
        return new ThriftRoutineCharacteristics(this);
    }

    @Override
    public void clear()
    {
        this.language = null;
        this.determinism = null;
        this.nullCallClause = null;
    }

    @org.apache.thrift.annotation.Nullable
    public String getLanguage()
    {
        return this.language;
    }

    public ThriftRoutineCharacteristics setLanguage(@org.apache.thrift.annotation.Nullable String language)
    {
        this.language = language;
        return this;
    }

    public void unsetLanguage()
    {
        this.language = null;
    }

    /** Returns true if field language is set (has been assigned a value) and false otherwise */
    public boolean isSetLanguage()
    {
        return this.language != null;
    }

    public void setLanguageIsSet(boolean value)
    {
        if (!value) {
            this.language = null;
        }
    }

    /**
     *
     * @see ThriftDeterminism
     */
    @org.apache.thrift.annotation.Nullable
    public ThriftDeterminism getDeterminism()
    {
        return this.determinism;
    }

    /**
     *
     * @see ThriftDeterminism
     */
    public ThriftRoutineCharacteristics setDeterminism(@org.apache.thrift.annotation.Nullable ThriftDeterminism determinism)
    {
        this.determinism = determinism;
        return this;
    }

    public void unsetDeterminism()
    {
        this.determinism = null;
    }

    /** Returns true if field determinism is set (has been assigned a value) and false otherwise */
    public boolean isSetDeterminism()
    {
        return this.determinism != null;
    }

    public void setDeterminismIsSet(boolean value)
    {
        if (!value) {
            this.determinism = null;
        }
    }

    /**
     *
     * @see ThriftNullCallClause
     */
    @org.apache.thrift.annotation.Nullable
    public ThriftNullCallClause getNullCallClause()
    {
        return this.nullCallClause;
    }

    /**
     *
     * @see ThriftNullCallClause
     */
    public ThriftRoutineCharacteristics setNullCallClause(@org.apache.thrift.annotation.Nullable ThriftNullCallClause nullCallClause)
    {
        this.nullCallClause = nullCallClause;
        return this;
    }

    public void unsetNullCallClause()
    {
        this.nullCallClause = null;
    }

    /** Returns true if field nullCallClause is set (has been assigned a value) and false otherwise */
    public boolean isSetNullCallClause()
    {
        return this.nullCallClause != null;
    }

    public void setNullCallClauseIsSet(boolean value)
    {
        if (!value) {
            this.nullCallClause = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case LANGUAGE:
                if (value == null) {
                    unsetLanguage();
                }
                else {
                    setLanguage((String) value);
                }
                break;

            case DETERMINISM:
                if (value == null) {
                    unsetDeterminism();
                }
                else {
                    setDeterminism((ThriftDeterminism) value);
                }
                break;

            case NULL_CALL_CLAUSE:
                if (value == null) {
                    unsetNullCallClause();
                }
                else {
                    setNullCallClause((ThriftNullCallClause) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case LANGUAGE:
                return getLanguage();

            case DETERMINISM:
                return getDeterminism();

            case NULL_CALL_CLAUSE:
                return getNullCallClause();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case LANGUAGE:
                return isSetLanguage();
            case DETERMINISM:
                return isSetDeterminism();
            case NULL_CALL_CLAUSE:
                return isSetNullCallClause();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftRoutineCharacteristics) {
        return this.equals((ThriftRoutineCharacteristics) that);
      }
        return false;
    }

    public boolean equals(ThriftRoutineCharacteristics that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_language = true && this.isSetLanguage();
        boolean that_present_language = true && that.isSetLanguage();
        if (this_present_language || that_present_language) {
          if (!(this_present_language && that_present_language)) {
            return false;
          }
          if (!this.language.equals(that.language)) {
            return false;
          }
        }

        boolean this_present_determinism = true && this.isSetDeterminism();
        boolean that_present_determinism = true && that.isSetDeterminism();
        if (this_present_determinism || that_present_determinism) {
          if (!(this_present_determinism && that_present_determinism)) {
            return false;
          }
          if (!this.determinism.equals(that.determinism)) {
            return false;
          }
        }

        boolean this_present_nullCallClause = true && this.isSetNullCallClause();
        boolean that_present_nullCallClause = true && that.isSetNullCallClause();
        if (this_present_nullCallClause || that_present_nullCallClause) {
          if (!(this_present_nullCallClause && that_present_nullCallClause)) {
            return false;
          }
          if (!this.nullCallClause.equals(that.nullCallClause)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetLanguage()) ? 131071 : 524287);
      if (isSetLanguage()) {
        hashCode = hashCode * 8191 + language.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetDeterminism()) ? 131071 : 524287);
      if (isSetDeterminism()) {
        hashCode = hashCode * 8191 + determinism.getValue();
      }

        hashCode = hashCode * 8191 + ((isSetNullCallClause()) ? 131071 : 524287);
      if (isSetNullCallClause()) {
        hashCode = hashCode * 8191 + nullCallClause.getValue();
      }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftRoutineCharacteristics other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetLanguage(), other.isSetLanguage());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetLanguage()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.language, other.language);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetDeterminism(), other.isSetDeterminism());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetDeterminism()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.determinism, other.determinism);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetNullCallClause(), other.isSetNullCallClause());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetNullCallClause()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nullCallClause, other.nullCallClause);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftRoutineCharacteristics(");
        boolean first = true;

        sb.append("language:");
        if (this.language == null) {
            sb.append("null");
        }
        else {
            sb.append(this.language);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("determinism:");
        if (this.determinism == null) {
            sb.append("null");
        }
        else {
            sb.append(this.determinism);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("nullCallClause:");
        if (this.nullCallClause == null) {
            sb.append("null");
        }
        else {
            sb.append(this.nullCallClause);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftRoutineCharacteristicsStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftRoutineCharacteristicsStandardScheme getScheme()
        {
            return new ThriftRoutineCharacteristicsStandardScheme();
        }
    }

    private static class ThriftRoutineCharacteristicsStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftRoutineCharacteristics>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftRoutineCharacteristics struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // LANGUAGE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.language = iprot.readString();
                            struct.setLanguageIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // DETERMINISM
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.determinism = ThriftDeterminism.findByValue(iprot.readI32());
                            struct.setDeterminismIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // NULL_CALL_CLAUSE
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.nullCallClause = ThriftNullCallClause.findByValue(iprot.readI32());
                            struct.setNullCallClauseIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftRoutineCharacteristics struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.language != null) {
                oprot.writeFieldBegin(LANGUAGE_FIELD_DESC);
                oprot.writeString(struct.language);
                oprot.writeFieldEnd();
            }
            if (struct.determinism != null) {
                oprot.writeFieldBegin(DETERMINISM_FIELD_DESC);
                oprot.writeI32(struct.determinism.getValue());
                oprot.writeFieldEnd();
            }
            if (struct.nullCallClause != null) {
                oprot.writeFieldBegin(NULL_CALL_CLAUSE_FIELD_DESC);
                oprot.writeI32(struct.nullCallClause.getValue());
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftRoutineCharacteristicsTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftRoutineCharacteristicsTupleScheme getScheme()
        {
            return new ThriftRoutineCharacteristicsTupleScheme();
        }
    }

    private static class ThriftRoutineCharacteristicsTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftRoutineCharacteristics>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftRoutineCharacteristics struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetLanguage()) {
                optionals.set(0);
            }
            if (struct.isSetDeterminism()) {
                optionals.set(1);
            }
            if (struct.isSetNullCallClause()) {
                optionals.set(2);
            }
            oprot.writeBitSet(optionals, 3);
            if (struct.isSetLanguage()) {
                oprot.writeString(struct.language);
            }
            if (struct.isSetDeterminism()) {
                oprot.writeI32(struct.determinism.getValue());
            }
            if (struct.isSetNullCallClause()) {
                oprot.writeI32(struct.nullCallClause.getValue());
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftRoutineCharacteristics struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(3);
            if (incoming.get(0)) {
                struct.language = iprot.readString();
                struct.setLanguageIsSet(true);
            }
            if (incoming.get(1)) {
                struct.determinism = ThriftDeterminism.findByValue(iprot.readI32());
                struct.setDeterminismIsSet(true);
            }
            if (incoming.get(2)) {
                struct.nullCallClause = ThriftNullCallClause.findByValue(iprot.readI32());
                struct.setNullCallClauseIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

