/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftSignature
        implements org.apache.thrift.TBase<ThriftSignature, ThriftSignature._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftSignature>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftSignature");

    private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
    private static final org.apache.thrift.protocol.TField KIND_FIELD_DESC = new org.apache.thrift.protocol.TField("kind", org.apache.thrift.protocol.TType.I32, (short) 2);
    private static final org.apache.thrift.protocol.TField TYPE_VARIABLE_CONSTRAINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("typeVariableConstraints", org.apache.thrift.protocol.TType.LIST, (short) 3);
    private static final org.apache.thrift.protocol.TField LONG_VARIABLE_CONSTRAINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("longVariableConstraints", org.apache.thrift.protocol.TType.LIST, (short) 4);
    private static final org.apache.thrift.protocol.TField RETURN_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("returnType", org.apache.thrift.protocol.TType.STRUCT, (short) 5);
    private static final org.apache.thrift.protocol.TField ARGUMENT_TYPES_FIELD_DESC = new org.apache.thrift.protocol.TField("argumentTypes", org.apache.thrift.protocol.TType.LIST, (short) 6);
    private static final org.apache.thrift.protocol.TField VARIABLE_ARITY_FIELD_DESC = new org.apache.thrift.protocol.TField("variableArity", org.apache.thrift.protocol.TType.BOOL, (short) 7);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftSignatureStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftSignatureTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName name; // required
    /**
     *
     * @see ThriftFunctionKind
     */
    public @org.apache.thrift.annotation.Nullable ThriftFunctionKind kind; // required
    public @org.apache.thrift.annotation.Nullable java.util.List<ThriftTypeVariableConstraint> typeVariableConstraints; // required
    public @org.apache.thrift.annotation.Nullable java.util.List<ThriftLongVariableConstraint> longVariableConstraints; // required
    public @org.apache.thrift.annotation.Nullable ThriftTypeSignature returnType; // required
    public @org.apache.thrift.annotation.Nullable java.util.List<ThriftTypeSignature> argumentTypes; // required
    public boolean variableArity; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        NAME((short) 1, "name"),
        /**
         *
         * @see ThriftFunctionKind
         */
        KIND((short) 2, "kind"),
        TYPE_VARIABLE_CONSTRAINTS((short) 3, "typeVariableConstraints"),
        LONG_VARIABLE_CONSTRAINTS((short) 4, "longVariableConstraints"),
        RETURN_TYPE((short) 5, "returnType"),
        ARGUMENT_TYPES((short) 6, "argumentTypes"),
        VARIABLE_ARITY((short) 7, "variableArity");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // NAME
                    return NAME;
                case 2: // KIND
                    return KIND;
                case 3: // TYPE_VARIABLE_CONSTRAINTS
                    return TYPE_VARIABLE_CONSTRAINTS;
                case 4: // LONG_VARIABLE_CONSTRAINTS
                    return LONG_VARIABLE_CONSTRAINTS;
                case 5: // RETURN_TYPE
                    return RETURN_TYPE;
                case 6: // ARGUMENT_TYPES
                    return ARGUMENT_TYPES;
                case 7: // VARIABLE_ARITY
                    return VARIABLE_ARITY;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __VARIABLEARITY_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftQualifiedObjectName.class)));
        tmpMap.put(_Fields.KIND, new org.apache.thrift.meta_data.FieldMetaData("kind", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftFunctionKind.class)));
        tmpMap.put(_Fields.TYPE_VARIABLE_CONSTRAINTS, new org.apache.thrift.meta_data.FieldMetaData("typeVariableConstraints", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeVariableConstraint.class))));
        tmpMap.put(_Fields.LONG_VARIABLE_CONSTRAINTS, new org.apache.thrift.meta_data.FieldMetaData("longVariableConstraints", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLongVariableConstraint.class))));
        tmpMap.put(_Fields.RETURN_TYPE, new org.apache.thrift.meta_data.FieldMetaData("returnType", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeSignature.class)));
        tmpMap.put(_Fields.ARGUMENT_TYPES, new org.apache.thrift.meta_data.FieldMetaData("argumentTypes", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeSignature.class))));
        tmpMap.put(_Fields.VARIABLE_ARITY, new org.apache.thrift.meta_data.FieldMetaData("variableArity", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftSignature.class, metaDataMap);
    }

    public ThriftSignature()
    {
    }

    public ThriftSignature(
            ThriftQualifiedObjectName name,
            ThriftFunctionKind kind,
            java.util.List<ThriftTypeVariableConstraint> typeVariableConstraints,
            java.util.List<ThriftLongVariableConstraint> longVariableConstraints,
            ThriftTypeSignature returnType,
            java.util.List<ThriftTypeSignature> argumentTypes,
            boolean variableArity)
    {
        this();
        this.name = name;
        this.kind = kind;
        this.typeVariableConstraints = typeVariableConstraints;
        this.longVariableConstraints = longVariableConstraints;
        this.returnType = returnType;
        this.argumentTypes = argumentTypes;
        this.variableArity = variableArity;
        setVariableArityIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftSignature(ThriftSignature other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetName()) {
            this.name = new ThriftQualifiedObjectName(other.name);
        }
        if (other.isSetKind()) {
            this.kind = other.kind;
        }
        if (other.isSetTypeVariableConstraints()) {
            java.util.List<ThriftTypeVariableConstraint> __this__typeVariableConstraints = new java.util.ArrayList<ThriftTypeVariableConstraint>(other.typeVariableConstraints.size());
            for (ThriftTypeVariableConstraint other_element : other.typeVariableConstraints) {
                __this__typeVariableConstraints.add(new ThriftTypeVariableConstraint(other_element));
            }
            this.typeVariableConstraints = __this__typeVariableConstraints;
        }
        if (other.isSetLongVariableConstraints()) {
            java.util.List<ThriftLongVariableConstraint> __this__longVariableConstraints = new java.util.ArrayList<ThriftLongVariableConstraint>(other.longVariableConstraints.size());
            for (ThriftLongVariableConstraint other_element : other.longVariableConstraints) {
                __this__longVariableConstraints.add(new ThriftLongVariableConstraint(other_element));
            }
            this.longVariableConstraints = __this__longVariableConstraints;
        }
        if (other.isSetReturnType()) {
            this.returnType = new ThriftTypeSignature(other.returnType);
        }
        if (other.isSetArgumentTypes()) {
            java.util.List<ThriftTypeSignature> __this__argumentTypes = new java.util.ArrayList<ThriftTypeSignature>(other.argumentTypes.size());
            for (ThriftTypeSignature other_element : other.argumentTypes) {
                __this__argumentTypes.add(new ThriftTypeSignature(other_element));
            }
            this.argumentTypes = __this__argumentTypes;
        }
        this.variableArity = other.variableArity;
    }

    @Override
    public ThriftSignature deepCopy()
    {
        return new ThriftSignature(this);
    }

    @Override
    public void clear()
    {
        this.name = null;
        this.kind = null;
        this.typeVariableConstraints = null;
        this.longVariableConstraints = null;
        this.returnType = null;
        this.argumentTypes = null;
        setVariableArityIsSet(false);
        this.variableArity = false;
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftQualifiedObjectName getName()
    {
        return this.name;
    }

    public ThriftSignature setName(@org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName name)
    {
        this.name = name;
        return this;
    }

    public void unsetName()
    {
        this.name = null;
    }

    /** Returns true if field name is set (has been assigned a value) and false otherwise */
    public boolean isSetName()
    {
        return this.name != null;
    }

    public void setNameIsSet(boolean value)
    {
        if (!value) {
            this.name = null;
        }
    }

    /**
     *
     * @see ThriftFunctionKind
     */
    @org.apache.thrift.annotation.Nullable
    public ThriftFunctionKind getKind()
    {
        return this.kind;
    }

    /**
     *
     * @see ThriftFunctionKind
     */
    public ThriftSignature setKind(@org.apache.thrift.annotation.Nullable ThriftFunctionKind kind)
    {
        this.kind = kind;
        return this;
    }

    public void unsetKind()
    {
        this.kind = null;
    }

    /** Returns true if field kind is set (has been assigned a value) and false otherwise */
    public boolean isSetKind()
    {
        return this.kind != null;
    }

    public void setKindIsSet(boolean value)
    {
        if (!value) {
            this.kind = null;
        }
    }

    public int getTypeVariableConstraintsSize()
    {
        return (this.typeVariableConstraints == null) ? 0 : this.typeVariableConstraints.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftTypeVariableConstraint> getTypeVariableConstraintsIterator()
    {
        return (this.typeVariableConstraints == null) ? null : this.typeVariableConstraints.iterator();
    }

    public void addToTypeVariableConstraints(ThriftTypeVariableConstraint elem)
    {
        if (this.typeVariableConstraints == null) {
            this.typeVariableConstraints = new java.util.ArrayList<ThriftTypeVariableConstraint>();
        }
        this.typeVariableConstraints.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<ThriftTypeVariableConstraint> getTypeVariableConstraints()
    {
        return this.typeVariableConstraints;
    }

    public ThriftSignature setTypeVariableConstraints(@org.apache.thrift.annotation.Nullable java.util.List<ThriftTypeVariableConstraint> typeVariableConstraints)
    {
        this.typeVariableConstraints = typeVariableConstraints;
        return this;
    }

    public void unsetTypeVariableConstraints()
    {
        this.typeVariableConstraints = null;
    }

    /** Returns true if field typeVariableConstraints is set (has been assigned a value) and false otherwise */
    public boolean isSetTypeVariableConstraints()
    {
        return this.typeVariableConstraints != null;
    }

    public void setTypeVariableConstraintsIsSet(boolean value)
    {
        if (!value) {
            this.typeVariableConstraints = null;
        }
    }

    public int getLongVariableConstraintsSize()
    {
        return (this.longVariableConstraints == null) ? 0 : this.longVariableConstraints.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftLongVariableConstraint> getLongVariableConstraintsIterator()
    {
        return (this.longVariableConstraints == null) ? null : this.longVariableConstraints.iterator();
    }

    public void addToLongVariableConstraints(ThriftLongVariableConstraint elem)
    {
        if (this.longVariableConstraints == null) {
            this.longVariableConstraints = new java.util.ArrayList<ThriftLongVariableConstraint>();
        }
        this.longVariableConstraints.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<ThriftLongVariableConstraint> getLongVariableConstraints()
    {
        return this.longVariableConstraints;
    }

    public ThriftSignature setLongVariableConstraints(@org.apache.thrift.annotation.Nullable java.util.List<ThriftLongVariableConstraint> longVariableConstraints)
    {
        this.longVariableConstraints = longVariableConstraints;
        return this;
    }

    public void unsetLongVariableConstraints()
    {
        this.longVariableConstraints = null;
    }

    /** Returns true if field longVariableConstraints is set (has been assigned a value) and false otherwise */
    public boolean isSetLongVariableConstraints()
    {
        return this.longVariableConstraints != null;
    }

    public void setLongVariableConstraintsIsSet(boolean value)
    {
        if (!value) {
            this.longVariableConstraints = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftTypeSignature getReturnType()
    {
        return this.returnType;
    }

    public ThriftSignature setReturnType(@org.apache.thrift.annotation.Nullable ThriftTypeSignature returnType)
    {
        this.returnType = returnType;
        return this;
    }

    public void unsetReturnType()
    {
        this.returnType = null;
    }

    /** Returns true if field returnType is set (has been assigned a value) and false otherwise */
    public boolean isSetReturnType()
    {
        return this.returnType != null;
    }

    public void setReturnTypeIsSet(boolean value)
    {
        if (!value) {
            this.returnType = null;
        }
    }

    public int getArgumentTypesSize()
    {
        return (this.argumentTypes == null) ? 0 : this.argumentTypes.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftTypeSignature> getArgumentTypesIterator()
    {
        return (this.argumentTypes == null) ? null : this.argumentTypes.iterator();
    }

    public void addToArgumentTypes(ThriftTypeSignature elem)
    {
        if (this.argumentTypes == null) {
            this.argumentTypes = new java.util.ArrayList<ThriftTypeSignature>();
        }
        this.argumentTypes.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<ThriftTypeSignature> getArgumentTypes()
    {
        return this.argumentTypes;
    }

    public ThriftSignature setArgumentTypes(@org.apache.thrift.annotation.Nullable java.util.List<ThriftTypeSignature> argumentTypes)
    {
        this.argumentTypes = argumentTypes;
        return this;
    }

    public void unsetArgumentTypes()
    {
        this.argumentTypes = null;
    }

    /** Returns true if field argumentTypes is set (has been assigned a value) and false otherwise */
    public boolean isSetArgumentTypes()
    {
        return this.argumentTypes != null;
    }

    public void setArgumentTypesIsSet(boolean value)
    {
        if (!value) {
            this.argumentTypes = null;
        }
    }

    public boolean isVariableArity()
    {
        return this.variableArity;
    }

    public ThriftSignature setVariableArity(boolean variableArity)
    {
        this.variableArity = variableArity;
        setVariableArityIsSet(true);
        return this;
    }

    public void unsetVariableArity()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARIABLEARITY_ISSET_ID);
    }

    /** Returns true if field variableArity is set (has been assigned a value) and false otherwise */
    public boolean isSetVariableArity()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARIABLEARITY_ISSET_ID);
    }

    public void setVariableArityIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARIABLEARITY_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case NAME:
                if (value == null) {
                    unsetName();
                }
                else {
                    setName((ThriftQualifiedObjectName) value);
                }
                break;

            case KIND:
                if (value == null) {
                    unsetKind();
                }
                else {
                    setKind((ThriftFunctionKind) value);
                }
                break;

            case TYPE_VARIABLE_CONSTRAINTS:
                if (value == null) {
                    unsetTypeVariableConstraints();
                }
                else {
                    setTypeVariableConstraints((java.util.List<ThriftTypeVariableConstraint>) value);
                }
                break;

            case LONG_VARIABLE_CONSTRAINTS:
                if (value == null) {
                    unsetLongVariableConstraints();
                }
                else {
                    setLongVariableConstraints((java.util.List<ThriftLongVariableConstraint>) value);
                }
                break;

            case RETURN_TYPE:
                if (value == null) {
                    unsetReturnType();
                }
                else {
                    setReturnType((ThriftTypeSignature) value);
                }
                break;

            case ARGUMENT_TYPES:
                if (value == null) {
                    unsetArgumentTypes();
                }
                else {
                    setArgumentTypes((java.util.List<ThriftTypeSignature>) value);
                }
                break;

            case VARIABLE_ARITY:
                if (value == null) {
                    unsetVariableArity();
                }
                else {
                    setVariableArity((Boolean) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case NAME:
                return getName();

            case KIND:
                return getKind();

            case TYPE_VARIABLE_CONSTRAINTS:
                return getTypeVariableConstraints();

            case LONG_VARIABLE_CONSTRAINTS:
                return getLongVariableConstraints();

            case RETURN_TYPE:
                return getReturnType();

            case ARGUMENT_TYPES:
                return getArgumentTypes();

            case VARIABLE_ARITY:
                return isVariableArity();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case NAME:
                return isSetName();
            case KIND:
                return isSetKind();
            case TYPE_VARIABLE_CONSTRAINTS:
                return isSetTypeVariableConstraints();
            case LONG_VARIABLE_CONSTRAINTS:
                return isSetLongVariableConstraints();
            case RETURN_TYPE:
                return isSetReturnType();
            case ARGUMENT_TYPES:
                return isSetArgumentTypes();
            case VARIABLE_ARITY:
                return isSetVariableArity();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftSignature) {
        return this.equals((ThriftSignature) that);
      }
        return false;
    }

    public boolean equals(ThriftSignature that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_name = true && this.isSetName();
        boolean that_present_name = true && that.isSetName();
        if (this_present_name || that_present_name) {
          if (!(this_present_name && that_present_name)) {
            return false;
          }
          if (!this.name.equals(that.name)) {
            return false;
          }
        }

        boolean this_present_kind = true && this.isSetKind();
        boolean that_present_kind = true && that.isSetKind();
        if (this_present_kind || that_present_kind) {
          if (!(this_present_kind && that_present_kind)) {
            return false;
          }
          if (!this.kind.equals(that.kind)) {
            return false;
          }
        }

        boolean this_present_typeVariableConstraints = true && this.isSetTypeVariableConstraints();
        boolean that_present_typeVariableConstraints = true && that.isSetTypeVariableConstraints();
        if (this_present_typeVariableConstraints || that_present_typeVariableConstraints) {
          if (!(this_present_typeVariableConstraints && that_present_typeVariableConstraints)) {
            return false;
          }
          if (!this.typeVariableConstraints.equals(that.typeVariableConstraints)) {
            return false;
          }
        }

        boolean this_present_longVariableConstraints = true && this.isSetLongVariableConstraints();
        boolean that_present_longVariableConstraints = true && that.isSetLongVariableConstraints();
        if (this_present_longVariableConstraints || that_present_longVariableConstraints) {
          if (!(this_present_longVariableConstraints && that_present_longVariableConstraints)) {
            return false;
          }
          if (!this.longVariableConstraints.equals(that.longVariableConstraints)) {
            return false;
          }
        }

        boolean this_present_returnType = true && this.isSetReturnType();
        boolean that_present_returnType = true && that.isSetReturnType();
        if (this_present_returnType || that_present_returnType) {
          if (!(this_present_returnType && that_present_returnType)) {
            return false;
          }
          if (!this.returnType.equals(that.returnType)) {
            return false;
          }
        }

        boolean this_present_argumentTypes = true && this.isSetArgumentTypes();
        boolean that_present_argumentTypes = true && that.isSetArgumentTypes();
        if (this_present_argumentTypes || that_present_argumentTypes) {
          if (!(this_present_argumentTypes && that_present_argumentTypes)) {
            return false;
          }
          if (!this.argumentTypes.equals(that.argumentTypes)) {
            return false;
          }
        }

        boolean this_present_variableArity = true;
        boolean that_present_variableArity = true;
        if (this_present_variableArity || that_present_variableArity) {
          if (!(this_present_variableArity && that_present_variableArity)) {
            return false;
          }
          if (this.variableArity != that.variableArity) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
      if (isSetName()) {
        hashCode = hashCode * 8191 + name.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetKind()) ? 131071 : 524287);
      if (isSetKind()) {
        hashCode = hashCode * 8191 + kind.getValue();
      }

        hashCode = hashCode * 8191 + ((isSetTypeVariableConstraints()) ? 131071 : 524287);
      if (isSetTypeVariableConstraints()) {
        hashCode = hashCode * 8191 + typeVariableConstraints.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetLongVariableConstraints()) ? 131071 : 524287);
      if (isSetLongVariableConstraints()) {
        hashCode = hashCode * 8191 + longVariableConstraints.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetReturnType()) ? 131071 : 524287);
      if (isSetReturnType()) {
        hashCode = hashCode * 8191 + returnType.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetArgumentTypes()) ? 131071 : 524287);
      if (isSetArgumentTypes()) {
        hashCode = hashCode * 8191 + argumentTypes.hashCode();
      }

        hashCode = hashCode * 8191 + ((variableArity) ? 131071 : 524287);

        return hashCode;
    }

    @Override
    public int compareTo(ThriftSignature other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetName(), other.isSetName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetKind(), other.isSetKind());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetKind()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kind, other.kind);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetTypeVariableConstraints(), other.isSetTypeVariableConstraints());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTypeVariableConstraints()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typeVariableConstraints, other.typeVariableConstraints);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetLongVariableConstraints(), other.isSetLongVariableConstraints());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetLongVariableConstraints()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longVariableConstraints, other.longVariableConstraints);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetReturnType(), other.isSetReturnType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetReturnType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.returnType, other.returnType);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetArgumentTypes(), other.isSetArgumentTypes());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetArgumentTypes()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.argumentTypes, other.argumentTypes);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetVariableArity(), other.isSetVariableArity());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetVariableArity()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.variableArity, other.variableArity);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftSignature(");
        boolean first = true;

        sb.append("name:");
        if (this.name == null) {
            sb.append("null");
        }
        else {
            sb.append(this.name);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("kind:");
        if (this.kind == null) {
            sb.append("null");
        }
        else {
            sb.append(this.kind);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("typeVariableConstraints:");
        if (this.typeVariableConstraints == null) {
            sb.append("null");
        }
        else {
            sb.append(this.typeVariableConstraints);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("longVariableConstraints:");
        if (this.longVariableConstraints == null) {
            sb.append("null");
        }
        else {
            sb.append(this.longVariableConstraints);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("returnType:");
        if (this.returnType == null) {
            sb.append("null");
        }
        else {
            sb.append(this.returnType);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("argumentTypes:");
        if (this.argumentTypes == null) {
            sb.append("null");
        }
        else {
            sb.append(this.argumentTypes);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("variableArity:");
        sb.append(this.variableArity);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (name != null) {
            name.validate();
        }
        if (returnType != null) {
            returnType.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftSignatureStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftSignatureStandardScheme getScheme()
        {
            return new ThriftSignatureStandardScheme();
        }
    }

    private static class ThriftSignatureStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftSignature>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftSignature struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.name = new ThriftQualifiedObjectName();
                            struct.name.read(iprot);
                            struct.setNameIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // KIND
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.kind = ThriftFunctionKind.findByValue(iprot.readI32());
                            struct.setKindIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // TYPE_VARIABLE_CONSTRAINTS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                                struct.typeVariableConstraints = new java.util.ArrayList<ThriftTypeVariableConstraint>(_list0.size);
                                @org.apache.thrift.annotation.Nullable ThriftTypeVariableConstraint _elem1;
                                for (int _i2 = 0; _i2 < _list0.size; ++_i2) {
                                    _elem1 = new ThriftTypeVariableConstraint();
                                    _elem1.read(iprot);
                                    struct.typeVariableConstraints.add(_elem1);
                                }
                                iprot.readListEnd();
                            }
                            struct.setTypeVariableConstraintsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // LONG_VARIABLE_CONSTRAINTS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                                struct.longVariableConstraints = new java.util.ArrayList<ThriftLongVariableConstraint>(_list3.size);
                                @org.apache.thrift.annotation.Nullable ThriftLongVariableConstraint _elem4;
                                for (int _i5 = 0; _i5 < _list3.size; ++_i5) {
                                    _elem4 = new ThriftLongVariableConstraint();
                                    _elem4.read(iprot);
                                    struct.longVariableConstraints.add(_elem4);
                                }
                                iprot.readListEnd();
                            }
                            struct.setLongVariableConstraintsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // RETURN_TYPE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.returnType = new ThriftTypeSignature();
                            struct.returnType.read(iprot);
                            struct.setReturnTypeIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 6: // ARGUMENT_TYPES
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                                struct.argumentTypes = new java.util.ArrayList<ThriftTypeSignature>(_list6.size);
                                @org.apache.thrift.annotation.Nullable ThriftTypeSignature _elem7;
                                for (int _i8 = 0; _i8 < _list6.size; ++_i8) {
                                    _elem7 = new ThriftTypeSignature();
                                    _elem7.read(iprot);
                                    struct.argumentTypes.add(_elem7);
                                }
                                iprot.readListEnd();
                            }
                            struct.setArgumentTypesIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 7: // VARIABLE_ARITY
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.variableArity = iprot.readBool();
                            struct.setVariableArityIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftSignature struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.name != null) {
                oprot.writeFieldBegin(NAME_FIELD_DESC);
                struct.name.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.kind != null) {
                oprot.writeFieldBegin(KIND_FIELD_DESC);
                oprot.writeI32(struct.kind.getValue());
                oprot.writeFieldEnd();
            }
            if (struct.typeVariableConstraints != null) {
                oprot.writeFieldBegin(TYPE_VARIABLE_CONSTRAINTS_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.typeVariableConstraints.size()));
                    for (ThriftTypeVariableConstraint _iter9 : struct.typeVariableConstraints) {
                        _iter9.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.longVariableConstraints != null) {
                oprot.writeFieldBegin(LONG_VARIABLE_CONSTRAINTS_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.longVariableConstraints.size()));
                    for (ThriftLongVariableConstraint _iter10 : struct.longVariableConstraints) {
                        _iter10.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.returnType != null) {
                oprot.writeFieldBegin(RETURN_TYPE_FIELD_DESC);
                struct.returnType.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.argumentTypes != null) {
                oprot.writeFieldBegin(ARGUMENT_TYPES_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.argumentTypes.size()));
                    for (ThriftTypeSignature _iter11 : struct.argumentTypes) {
                        _iter11.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(VARIABLE_ARITY_FIELD_DESC);
            oprot.writeBool(struct.variableArity);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftSignatureTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftSignatureTupleScheme getScheme()
        {
            return new ThriftSignatureTupleScheme();
        }
    }

    private static class ThriftSignatureTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftSignature>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftSignature struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetName()) {
                optionals.set(0);
            }
            if (struct.isSetKind()) {
                optionals.set(1);
            }
            if (struct.isSetTypeVariableConstraints()) {
                optionals.set(2);
            }
            if (struct.isSetLongVariableConstraints()) {
                optionals.set(3);
            }
            if (struct.isSetReturnType()) {
                optionals.set(4);
            }
            if (struct.isSetArgumentTypes()) {
                optionals.set(5);
            }
            if (struct.isSetVariableArity()) {
                optionals.set(6);
            }
            oprot.writeBitSet(optionals, 7);
            if (struct.isSetName()) {
                struct.name.write(oprot);
            }
            if (struct.isSetKind()) {
                oprot.writeI32(struct.kind.getValue());
            }
            if (struct.isSetTypeVariableConstraints()) {
                {
                    oprot.writeI32(struct.typeVariableConstraints.size());
                    for (ThriftTypeVariableConstraint _iter12 : struct.typeVariableConstraints) {
                        _iter12.write(oprot);
                    }
                }
            }
            if (struct.isSetLongVariableConstraints()) {
                {
                    oprot.writeI32(struct.longVariableConstraints.size());
                    for (ThriftLongVariableConstraint _iter13 : struct.longVariableConstraints) {
                        _iter13.write(oprot);
                    }
                }
            }
            if (struct.isSetReturnType()) {
                struct.returnType.write(oprot);
            }
            if (struct.isSetArgumentTypes()) {
                {
                    oprot.writeI32(struct.argumentTypes.size());
                    for (ThriftTypeSignature _iter14 : struct.argumentTypes) {
                        _iter14.write(oprot);
                    }
                }
            }
            if (struct.isSetVariableArity()) {
                oprot.writeBool(struct.variableArity);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftSignature struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(7);
            if (incoming.get(0)) {
                struct.name = new ThriftQualifiedObjectName();
                struct.name.read(iprot);
                struct.setNameIsSet(true);
            }
            if (incoming.get(1)) {
                struct.kind = ThriftFunctionKind.findByValue(iprot.readI32());
                struct.setKindIsSet(true);
            }
            if (incoming.get(2)) {
                {
                    org.apache.thrift.protocol.TList _list15 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.typeVariableConstraints = new java.util.ArrayList<ThriftTypeVariableConstraint>(_list15.size);
                    @org.apache.thrift.annotation.Nullable ThriftTypeVariableConstraint _elem16;
                    for (int _i17 = 0; _i17 < _list15.size; ++_i17) {
                        _elem16 = new ThriftTypeVariableConstraint();
                        _elem16.read(iprot);
                        struct.typeVariableConstraints.add(_elem16);
                    }
                }
                struct.setTypeVariableConstraintsIsSet(true);
            }
            if (incoming.get(3)) {
                {
                    org.apache.thrift.protocol.TList _list18 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.longVariableConstraints = new java.util.ArrayList<ThriftLongVariableConstraint>(_list18.size);
                    @org.apache.thrift.annotation.Nullable ThriftLongVariableConstraint _elem19;
                    for (int _i20 = 0; _i20 < _list18.size; ++_i20) {
                        _elem19 = new ThriftLongVariableConstraint();
                        _elem19.read(iprot);
                        struct.longVariableConstraints.add(_elem19);
                    }
                }
                struct.setLongVariableConstraintsIsSet(true);
            }
            if (incoming.get(4)) {
                struct.returnType = new ThriftTypeSignature();
                struct.returnType.read(iprot);
                struct.setReturnTypeIsSet(true);
            }
            if (incoming.get(5)) {
                {
                    org.apache.thrift.protocol.TList _list21 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.argumentTypes = new java.util.ArrayList<ThriftTypeSignature>(_list21.size);
                    @org.apache.thrift.annotation.Nullable ThriftTypeSignature _elem22;
                    for (int _i23 = 0; _i23 < _list21.size; ++_i23) {
                        _elem22 = new ThriftTypeSignature();
                        _elem22.read(iprot);
                        struct.argumentTypes.add(_elem22);
                    }
                }
                struct.setArgumentTypesIsSet(true);
            }
            if (incoming.get(6)) {
                struct.variableArity = iprot.readBool();
                struct.setVariableArityIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

