/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftDistinctTypeInfo
        implements org.apache.thrift.TBase<ThriftDistinctTypeInfo, ThriftDistinctTypeInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftDistinctTypeInfo>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftDistinctTypeInfo");

    private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
    private static final org.apache.thrift.protocol.TField BASE_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("baseType", org.apache.thrift.protocol.TType.STRUCT, (short) 2);
    private static final org.apache.thrift.protocol.TField IS_ORDERABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("isOrderable", org.apache.thrift.protocol.TType.BOOL, (short) 3);
    private static final org.apache.thrift.protocol.TField TOP_MOST_ANCESTOR_FIELD_DESC = new org.apache.thrift.protocol.TField("topMostAncestor", org.apache.thrift.protocol.TType.STRUCT, (short) 4);
    private static final org.apache.thrift.protocol.TField OTHER_ANCESTORS_FIELD_DESC = new org.apache.thrift.protocol.TField("otherAncestors", org.apache.thrift.protocol.TType.LIST, (short) 5);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftDistinctTypeInfoStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftDistinctTypeInfoTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName name; // required
    public @org.apache.thrift.annotation.Nullable ThriftTypeSignature baseType; // required
    public boolean isOrderable; // required
    public @org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName topMostAncestor; // optional
    public @org.apache.thrift.annotation.Nullable java.util.List<ThriftQualifiedObjectName> otherAncestors; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        NAME((short) 1, "name"),
        BASE_TYPE((short) 2, "baseType"),
        IS_ORDERABLE((short) 3, "isOrderable"),
        TOP_MOST_ANCESTOR((short) 4, "topMostAncestor"),
        OTHER_ANCESTORS((short) 5, "otherAncestors");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // NAME
                    return NAME;
                case 2: // BASE_TYPE
                    return BASE_TYPE;
                case 3: // IS_ORDERABLE
                    return IS_ORDERABLE;
                case 4: // TOP_MOST_ANCESTOR
                    return TOP_MOST_ANCESTOR;
                case 5: // OTHER_ANCESTORS
                    return OTHER_ANCESTORS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __ISORDERABLE_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    private static final _Fields optionals[] = {_Fields.TOP_MOST_ANCESTOR};
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftQualifiedObjectName.class)));
        tmpMap.put(_Fields.BASE_TYPE, new org.apache.thrift.meta_data.FieldMetaData("baseType", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTypeSignature.class)));
        tmpMap.put(_Fields.IS_ORDERABLE, new org.apache.thrift.meta_data.FieldMetaData("isOrderable", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        tmpMap.put(_Fields.TOP_MOST_ANCESTOR, new org.apache.thrift.meta_data.FieldMetaData("topMostAncestor", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftQualifiedObjectName.class)));
        tmpMap.put(_Fields.OTHER_ANCESTORS, new org.apache.thrift.meta_data.FieldMetaData("otherAncestors", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftQualifiedObjectName.class))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftDistinctTypeInfo.class, metaDataMap);
    }

    public ThriftDistinctTypeInfo()
    {
    }

    public ThriftDistinctTypeInfo(
            ThriftQualifiedObjectName name,
            ThriftTypeSignature baseType,
            boolean isOrderable,
            java.util.List<ThriftQualifiedObjectName> otherAncestors)
    {
        this();
        this.name = name;
        this.baseType = baseType;
        this.isOrderable = isOrderable;
        setIsOrderableIsSet(true);
        this.otherAncestors = otherAncestors;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftDistinctTypeInfo(ThriftDistinctTypeInfo other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetName()) {
            this.name = new ThriftQualifiedObjectName(other.name);
        }
        if (other.isSetBaseType()) {
            this.baseType = new ThriftTypeSignature(other.baseType);
        }
        this.isOrderable = other.isOrderable;
        if (other.isSetTopMostAncestor()) {
            this.topMostAncestor = new ThriftQualifiedObjectName(other.topMostAncestor);
        }
        if (other.isSetOtherAncestors()) {
            java.util.List<ThriftQualifiedObjectName> __this__otherAncestors = new java.util.ArrayList<ThriftQualifiedObjectName>(other.otherAncestors.size());
            for (ThriftQualifiedObjectName other_element : other.otherAncestors) {
                __this__otherAncestors.add(new ThriftQualifiedObjectName(other_element));
            }
            this.otherAncestors = __this__otherAncestors;
        }
    }

    @Override
    public ThriftDistinctTypeInfo deepCopy()
    {
        return new ThriftDistinctTypeInfo(this);
    }

    @Override
    public void clear()
    {
        this.name = null;
        this.baseType = null;
        setIsOrderableIsSet(false);
        this.isOrderable = false;
        this.topMostAncestor = null;
        this.otherAncestors = null;
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftQualifiedObjectName getName()
    {
        return this.name;
    }

    public ThriftDistinctTypeInfo setName(@org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName name)
    {
        this.name = name;
        return this;
    }

    public void unsetName()
    {
        this.name = null;
    }

    /** Returns true if field name is set (has been assigned a value) and false otherwise */
    public boolean isSetName()
    {
        return this.name != null;
    }

    public void setNameIsSet(boolean value)
    {
        if (!value) {
            this.name = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftTypeSignature getBaseType()
    {
        return this.baseType;
    }

    public ThriftDistinctTypeInfo setBaseType(@org.apache.thrift.annotation.Nullable ThriftTypeSignature baseType)
    {
        this.baseType = baseType;
        return this;
    }

    public void unsetBaseType()
    {
        this.baseType = null;
    }

    /** Returns true if field baseType is set (has been assigned a value) and false otherwise */
    public boolean isSetBaseType()
    {
        return this.baseType != null;
    }

    public void setBaseTypeIsSet(boolean value)
    {
        if (!value) {
            this.baseType = null;
        }
    }

    public boolean isIsOrderable()
    {
        return this.isOrderable;
    }

    public ThriftDistinctTypeInfo setIsOrderable(boolean isOrderable)
    {
        this.isOrderable = isOrderable;
        setIsOrderableIsSet(true);
        return this;
    }

    public void unsetIsOrderable()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISORDERABLE_ISSET_ID);
    }

    /** Returns true if field isOrderable is set (has been assigned a value) and false otherwise */
    public boolean isSetIsOrderable()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISORDERABLE_ISSET_ID);
    }

    public void setIsOrderableIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISORDERABLE_ISSET_ID, value);
    }

    public java.util.Optional<ThriftQualifiedObjectName> getTopMostAncestor()
    {
        if (this.isSetTopMostAncestor()) {
            return java.util.Optional.of(this.topMostAncestor);
        }
        else {
            return java.util.Optional.empty();
        }
    }

    public ThriftDistinctTypeInfo setTopMostAncestor(@org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName topMostAncestor)
    {
        this.topMostAncestor = topMostAncestor;
        return this;
    }

    public void unsetTopMostAncestor()
    {
        this.topMostAncestor = null;
    }

    /** Returns true if field topMostAncestor is set (has been assigned a value) and false otherwise */
    public boolean isSetTopMostAncestor()
    {
        return this.topMostAncestor != null;
    }

    public void setTopMostAncestorIsSet(boolean value)
    {
        if (!value) {
            this.topMostAncestor = null;
        }
    }

    public int getOtherAncestorsSize()
    {
        return (this.otherAncestors == null) ? 0 : this.otherAncestors.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftQualifiedObjectName> getOtherAncestorsIterator()
    {
        return (this.otherAncestors == null) ? null : this.otherAncestors.iterator();
    }

    public void addToOtherAncestors(ThriftQualifiedObjectName elem)
    {
        if (this.otherAncestors == null) {
            this.otherAncestors = new java.util.ArrayList<ThriftQualifiedObjectName>();
        }
        this.otherAncestors.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<ThriftQualifiedObjectName> getOtherAncestors()
    {
        return this.otherAncestors;
    }

    public ThriftDistinctTypeInfo setOtherAncestors(@org.apache.thrift.annotation.Nullable java.util.List<ThriftQualifiedObjectName> otherAncestors)
    {
        this.otherAncestors = otherAncestors;
        return this;
    }

    public void unsetOtherAncestors()
    {
        this.otherAncestors = null;
    }

    /** Returns true if field otherAncestors is set (has been assigned a value) and false otherwise */
    public boolean isSetOtherAncestors()
    {
        return this.otherAncestors != null;
    }

    public void setOtherAncestorsIsSet(boolean value)
    {
        if (!value) {
            this.otherAncestors = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case NAME:
                if (value == null) {
                    unsetName();
                }
                else {
                    setName((ThriftQualifiedObjectName) value);
                }
                break;

            case BASE_TYPE:
                if (value == null) {
                    unsetBaseType();
                }
                else {
                    setBaseType((ThriftTypeSignature) value);
                }
                break;

            case IS_ORDERABLE:
                if (value == null) {
                    unsetIsOrderable();
                }
                else {
                    setIsOrderable((Boolean) value);
                }
                break;

            case TOP_MOST_ANCESTOR:
                if (value == null) {
                    unsetTopMostAncestor();
                }
                else {
                    setTopMostAncestor((ThriftQualifiedObjectName) value);
                }
                break;

            case OTHER_ANCESTORS:
                if (value == null) {
                    unsetOtherAncestors();
                }
                else {
                    setOtherAncestors((java.util.List<ThriftQualifiedObjectName>) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case NAME:
                return getName();

            case BASE_TYPE:
                return getBaseType();

            case IS_ORDERABLE:
                return isIsOrderable();

            case TOP_MOST_ANCESTOR:
                return getTopMostAncestor();

            case OTHER_ANCESTORS:
                return getOtherAncestors();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case NAME:
                return isSetName();
            case BASE_TYPE:
                return isSetBaseType();
            case IS_ORDERABLE:
                return isSetIsOrderable();
            case TOP_MOST_ANCESTOR:
                return isSetTopMostAncestor();
            case OTHER_ANCESTORS:
                return isSetOtherAncestors();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftDistinctTypeInfo) {
        return this.equals((ThriftDistinctTypeInfo) that);
      }
        return false;
    }

    public boolean equals(ThriftDistinctTypeInfo that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_name = true && this.isSetName();
        boolean that_present_name = true && that.isSetName();
        if (this_present_name || that_present_name) {
          if (!(this_present_name && that_present_name)) {
            return false;
          }
          if (!this.name.equals(that.name)) {
            return false;
          }
        }

        boolean this_present_baseType = true && this.isSetBaseType();
        boolean that_present_baseType = true && that.isSetBaseType();
        if (this_present_baseType || that_present_baseType) {
          if (!(this_present_baseType && that_present_baseType)) {
            return false;
          }
          if (!this.baseType.equals(that.baseType)) {
            return false;
          }
        }

        boolean this_present_isOrderable = true;
        boolean that_present_isOrderable = true;
        if (this_present_isOrderable || that_present_isOrderable) {
          if (!(this_present_isOrderable && that_present_isOrderable)) {
            return false;
          }
          if (this.isOrderable != that.isOrderable) {
            return false;
          }
        }

        boolean this_present_topMostAncestor = true && this.isSetTopMostAncestor();
        boolean that_present_topMostAncestor = true && that.isSetTopMostAncestor();
        if (this_present_topMostAncestor || that_present_topMostAncestor) {
          if (!(this_present_topMostAncestor && that_present_topMostAncestor)) {
            return false;
          }
          if (!this.topMostAncestor.equals(that.topMostAncestor)) {
            return false;
          }
        }

        boolean this_present_otherAncestors = true && this.isSetOtherAncestors();
        boolean that_present_otherAncestors = true && that.isSetOtherAncestors();
        if (this_present_otherAncestors || that_present_otherAncestors) {
          if (!(this_present_otherAncestors && that_present_otherAncestors)) {
            return false;
          }
          if (!this.otherAncestors.equals(that.otherAncestors)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
      if (isSetName()) {
        hashCode = hashCode * 8191 + name.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetBaseType()) ? 131071 : 524287);
      if (isSetBaseType()) {
        hashCode = hashCode * 8191 + baseType.hashCode();
      }

        hashCode = hashCode * 8191 + ((isOrderable) ? 131071 : 524287);

        hashCode = hashCode * 8191 + ((isSetTopMostAncestor()) ? 131071 : 524287);
      if (isSetTopMostAncestor()) {
        hashCode = hashCode * 8191 + topMostAncestor.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetOtherAncestors()) ? 131071 : 524287);
      if (isSetOtherAncestors()) {
        hashCode = hashCode * 8191 + otherAncestors.hashCode();
      }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftDistinctTypeInfo other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetName(), other.isSetName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetBaseType(), other.isSetBaseType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetBaseType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.baseType, other.baseType);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetIsOrderable(), other.isSetIsOrderable());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetIsOrderable()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isOrderable, other.isOrderable);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetTopMostAncestor(), other.isSetTopMostAncestor());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTopMostAncestor()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.topMostAncestor, other.topMostAncestor);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetOtherAncestors(), other.isSetOtherAncestors());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetOtherAncestors()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.otherAncestors, other.otherAncestors);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftDistinctTypeInfo(");
        boolean first = true;

        sb.append("name:");
        if (this.name == null) {
            sb.append("null");
        }
        else {
            sb.append(this.name);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("baseType:");
        if (this.baseType == null) {
            sb.append("null");
        }
        else {
            sb.append(this.baseType);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("isOrderable:");
        sb.append(this.isOrderable);
        first = false;
        if (isSetTopMostAncestor()) {
          if (!first) {
            sb.append(", ");
          }
            sb.append("topMostAncestor:");
            if (this.topMostAncestor == null) {
                sb.append("null");
            }
            else {
                sb.append(this.topMostAncestor);
            }
            first = false;
        }
      if (!first) {
        sb.append(", ");
      }
        sb.append("otherAncestors:");
        if (this.otherAncestors == null) {
            sb.append("null");
        }
        else {
            sb.append(this.otherAncestors);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (name != null) {
            name.validate();
        }
        if (baseType != null) {
            baseType.validate();
        }
        if (topMostAncestor != null) {
            topMostAncestor.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftDistinctTypeInfoStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftDistinctTypeInfoStandardScheme getScheme()
        {
            return new ThriftDistinctTypeInfoStandardScheme();
        }
    }

    private static class ThriftDistinctTypeInfoStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftDistinctTypeInfo>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftDistinctTypeInfo struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.name = new ThriftQualifiedObjectName();
                            struct.name.read(iprot);
                            struct.setNameIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // BASE_TYPE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.baseType = new ThriftTypeSignature();
                            struct.baseType.read(iprot);
                            struct.setBaseTypeIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // IS_ORDERABLE
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.isOrderable = iprot.readBool();
                            struct.setIsOrderableIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // TOP_MOST_ANCESTOR
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.topMostAncestor = new ThriftQualifiedObjectName();
                            struct.topMostAncestor.read(iprot);
                            struct.setTopMostAncestorIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // OTHER_ANCESTORS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list20 = iprot.readListBegin();
                                struct.otherAncestors = new java.util.ArrayList<ThriftQualifiedObjectName>(_list20.size);
                                @org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName _elem21;
                                for (int _i22 = 0; _i22 < _list20.size; ++_i22) {
                                    _elem21 = new ThriftQualifiedObjectName();
                                    _elem21.read(iprot);
                                    struct.otherAncestors.add(_elem21);
                                }
                                iprot.readListEnd();
                            }
                            struct.setOtherAncestorsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftDistinctTypeInfo struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.name != null) {
                oprot.writeFieldBegin(NAME_FIELD_DESC);
                struct.name.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.baseType != null) {
                oprot.writeFieldBegin(BASE_TYPE_FIELD_DESC);
                struct.baseType.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(IS_ORDERABLE_FIELD_DESC);
            oprot.writeBool(struct.isOrderable);
            oprot.writeFieldEnd();
            if (struct.topMostAncestor != null) {
                if (struct.isSetTopMostAncestor()) {
                    oprot.writeFieldBegin(TOP_MOST_ANCESTOR_FIELD_DESC);
                    struct.topMostAncestor.write(oprot);
                    oprot.writeFieldEnd();
                }
            }
            if (struct.otherAncestors != null) {
                oprot.writeFieldBegin(OTHER_ANCESTORS_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.otherAncestors.size()));
                    for (ThriftQualifiedObjectName _iter23 : struct.otherAncestors) {
                        _iter23.write(oprot);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftDistinctTypeInfoTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftDistinctTypeInfoTupleScheme getScheme()
        {
            return new ThriftDistinctTypeInfoTupleScheme();
        }
    }

    private static class ThriftDistinctTypeInfoTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftDistinctTypeInfo>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftDistinctTypeInfo struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetName()) {
                optionals.set(0);
            }
            if (struct.isSetBaseType()) {
                optionals.set(1);
            }
            if (struct.isSetIsOrderable()) {
                optionals.set(2);
            }
            if (struct.isSetTopMostAncestor()) {
                optionals.set(3);
            }
            if (struct.isSetOtherAncestors()) {
                optionals.set(4);
            }
            oprot.writeBitSet(optionals, 5);
            if (struct.isSetName()) {
                struct.name.write(oprot);
            }
            if (struct.isSetBaseType()) {
                struct.baseType.write(oprot);
            }
            if (struct.isSetIsOrderable()) {
                oprot.writeBool(struct.isOrderable);
            }
            if (struct.isSetTopMostAncestor()) {
                struct.topMostAncestor.write(oprot);
            }
            if (struct.isSetOtherAncestors()) {
                {
                    oprot.writeI32(struct.otherAncestors.size());
                    for (ThriftQualifiedObjectName _iter24 : struct.otherAncestors) {
                        _iter24.write(oprot);
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftDistinctTypeInfo struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(5);
            if (incoming.get(0)) {
                struct.name = new ThriftQualifiedObjectName();
                struct.name.read(iprot);
                struct.setNameIsSet(true);
            }
            if (incoming.get(1)) {
                struct.baseType = new ThriftTypeSignature();
                struct.baseType.read(iprot);
                struct.setBaseTypeIsSet(true);
            }
            if (incoming.get(2)) {
                struct.isOrderable = iprot.readBool();
                struct.setIsOrderableIsSet(true);
            }
            if (incoming.get(3)) {
                struct.topMostAncestor = new ThriftQualifiedObjectName();
                struct.topMostAncestor.read(iprot);
                struct.setTopMostAncestorIsSet(true);
            }
            if (incoming.get(4)) {
                {
                    org.apache.thrift.protocol.TList _list25 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.otherAncestors = new java.util.ArrayList<ThriftQualifiedObjectName>(_list25.size);
                    @org.apache.thrift.annotation.Nullable ThriftQualifiedObjectName _elem26;
                    for (int _i27 = 0; _i27 < _list25.size; ++_i27) {
                        _elem26 = new ThriftQualifiedObjectName();
                        _elem26.read(iprot);
                        struct.otherAncestors.add(_elem26);
                    }
                }
                struct.setOtherAncestorsIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

