/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-18")
public class ThriftTaskId
        implements org.apache.thrift.TBase<ThriftTaskId, ThriftTaskId._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftTaskId>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftTaskId");

    private static final org.apache.thrift.protocol.TField STAGE_EXECUTION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("stageExecutionId", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
    private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short) 2);
    private static final org.apache.thrift.protocol.TField ATTEMPT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("attemptNumber", org.apache.thrift.protocol.TType.I32, (short) 3);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftTaskIdStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftTaskIdTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable ThriftStageExecutionId stageExecutionId; // required
    public int id; // required
    public int attemptNumber; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        STAGE_EXECUTION_ID((short) 1, "stageExecutionId"),
        ID((short) 2, "id"),
        ATTEMPT_NUMBER((short) 3, "attemptNumber");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // STAGE_EXECUTION_ID
                    return STAGE_EXECUTION_ID;
                case 2: // ID
                    return ID;
                case 3: // ATTEMPT_NUMBER
                    return ATTEMPT_NUMBER;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) {
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __ID_ISSET_ID = 0;
    private static final int __ATTEMPTNUMBER_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.STAGE_EXECUTION_ID, new org.apache.thrift.meta_data.FieldMetaData("stageExecutionId", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftStageExecutionId.class)));
        tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        tmpMap.put(_Fields.ATTEMPT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("attemptNumber", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftTaskId.class, metaDataMap);
    }

    public ThriftTaskId()
    {
    }

    public ThriftTaskId(
            ThriftStageExecutionId stageExecutionId,
            int id,
            int attemptNumber)
    {
        this();
        this.stageExecutionId = stageExecutionId;
        this.id = id;
        setIdIsSet(true);
        this.attemptNumber = attemptNumber;
        setAttemptNumberIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftTaskId(ThriftTaskId other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetStageExecutionId()) {
            this.stageExecutionId = new ThriftStageExecutionId(other.stageExecutionId);
        }
        this.id = other.id;
        this.attemptNumber = other.attemptNumber;
    }

    @Override
    public ThriftTaskId deepCopy()
    {
        return new ThriftTaskId(this);
    }

    @Override
    public void clear()
    {
        this.stageExecutionId = null;
        setIdIsSet(false);
        this.id = 0;
        setAttemptNumberIsSet(false);
        this.attemptNumber = 0;
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftStageExecutionId getStageExecutionId()
    {
        return this.stageExecutionId;
    }

    public ThriftTaskId setStageExecutionId(@org.apache.thrift.annotation.Nullable ThriftStageExecutionId stageExecutionId)
    {
        this.stageExecutionId = stageExecutionId;
        return this;
    }

    public void unsetStageExecutionId()
    {
        this.stageExecutionId = null;
    }

    /**
     * Returns true if field stageExecutionId is set (has been assigned a value) and false otherwise
     */
    public boolean isSetStageExecutionId()
    {
        return this.stageExecutionId != null;
    }

    public void setStageExecutionIdIsSet(boolean value)
    {
        if (!value) {
            this.stageExecutionId = null;
        }
    }

    public int getId()
    {
        return this.id;
    }

    public ThriftTaskId setId(int id)
    {
        this.id = id;
        setIdIsSet(true);
        return this;
    }

    public void unsetId()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
    }

    /**
     * Returns true if field id is set (has been assigned a value) and false otherwise
     */
    public boolean isSetId()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
    }

    public void setIdIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
    }

    public int getAttemptNumber()
    {
        return this.attemptNumber;
    }

    public ThriftTaskId setAttemptNumber(int attemptNumber)
    {
        this.attemptNumber = attemptNumber;
        setAttemptNumberIsSet(true);
        return this;
    }

    public void unsetAttemptNumber()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ATTEMPTNUMBER_ISSET_ID);
    }

    /**
     * Returns true if field attemptNumber is set (has been assigned a value) and false otherwise
     */
    public boolean isSetAttemptNumber()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ATTEMPTNUMBER_ISSET_ID);
    }

    public void setAttemptNumberIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ATTEMPTNUMBER_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case STAGE_EXECUTION_ID:
                if (value == null) {
                    unsetStageExecutionId();
                }
                else {
                    setStageExecutionId((ThriftStageExecutionId) value);
                }
                break;

            case ID:
                if (value == null) {
                    unsetId();
                }
                else {
                    setId((Integer) value);
                }
                break;

            case ATTEMPT_NUMBER:
                if (value == null) {
                    unsetAttemptNumber();
                }
                else {
                    setAttemptNumber((Integer) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case STAGE_EXECUTION_ID:
                return getStageExecutionId();

            case ID:
                return getId();

            case ATTEMPT_NUMBER:
                return getAttemptNumber();
        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case STAGE_EXECUTION_ID:
                return isSetStageExecutionId();
            case ID:
                return isSetId();
            case ATTEMPT_NUMBER:
                return isSetAttemptNumber();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
        if (that instanceof ThriftTaskId) {
            return this.equals((ThriftTaskId) that);
        }
        return false;
    }

    public boolean equals(ThriftTaskId that)
    {
        if (that == null) {
            return false;
        }
        if (this == that) {
            return true;
        }

        boolean this_present_stageExecutionId = true && this.isSetStageExecutionId();
        boolean that_present_stageExecutionId = true && that.isSetStageExecutionId();
        if (this_present_stageExecutionId || that_present_stageExecutionId) {
            if (!(this_present_stageExecutionId && that_present_stageExecutionId)) {
                return false;
            }
            if (!this.stageExecutionId.equals(that.stageExecutionId)) {
                return false;
            }
        }

        boolean this_present_id = true;
        boolean that_present_id = true;
        if (this_present_id || that_present_id) {
            if (!(this_present_id && that_present_id)) {
                return false;
            }
            if (this.id != that.id) {
                return false;
            }
        }

        boolean this_present_attemptNumber = true;
        boolean that_present_attemptNumber = true;
        if (this_present_attemptNumber || that_present_attemptNumber) {
            if (!(this_present_attemptNumber && that_present_attemptNumber)) {
                return false;
            }
            if (this.attemptNumber != that.attemptNumber) {
                return false;
            }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetStageExecutionId()) ? 131071 : 524287);
        if (isSetStageExecutionId()) {
            hashCode = hashCode * 8191 + stageExecutionId.hashCode();
        }

        hashCode = hashCode * 8191 + id;

        hashCode = hashCode * 8191 + attemptNumber;

        return hashCode;
    }

    @Override
    public int compareTo(ThriftTaskId other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetStageExecutionId(), other.isSetStageExecutionId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetStageExecutionId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stageExecutionId, other.stageExecutionId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetId(), other.isSetId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetAttemptNumber(), other.isSetAttemptNumber());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetAttemptNumber()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attemptNumber, other.attemptNumber);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftTaskId(");
        boolean first = true;

        sb.append("stageExecutionId:");
        if (this.stageExecutionId == null) {
            sb.append("null");
        }
        else {
            sb.append(this.stageExecutionId);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("id:");
        sb.append(this.id);
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("attemptNumber:");
        sb.append(this.attemptNumber);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (stageExecutionId != null) {
            stageExecutionId.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftTaskIdStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskIdStandardScheme getScheme()
        {
            return new ThriftTaskIdStandardScheme();
        }
    }

    private static class ThriftTaskIdStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftTaskId>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftTaskId struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // STAGE_EXECUTION_ID
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.stageExecutionId = new ThriftStageExecutionId();
                            struct.stageExecutionId.read(iprot);
                            struct.setStageExecutionIdIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // ID
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.id = iprot.readI32();
                            struct.setIdIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // ATTEMPT_NUMBER
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.attemptNumber = iprot.readI32();
                            struct.setAttemptNumberIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftTaskId struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.stageExecutionId != null) {
                oprot.writeFieldBegin(STAGE_EXECUTION_ID_FIELD_DESC);
                struct.stageExecutionId.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(ID_FIELD_DESC);
            oprot.writeI32(struct.id);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(ATTEMPT_NUMBER_FIELD_DESC);
            oprot.writeI32(struct.attemptNumber);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftTaskIdTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskIdTupleScheme getScheme()
        {
            return new ThriftTaskIdTupleScheme();
        }
    }

    private static class ThriftTaskIdTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftTaskId>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftTaskId struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetStageExecutionId()) {
                optionals.set(0);
            }
            if (struct.isSetId()) {
                optionals.set(1);
            }
            if (struct.isSetAttemptNumber()) {
                optionals.set(2);
            }
            oprot.writeBitSet(optionals, 3);
            if (struct.isSetStageExecutionId()) {
                struct.stageExecutionId.write(oprot);
            }
            if (struct.isSetId()) {
                oprot.writeI32(struct.id);
            }
            if (struct.isSetAttemptNumber()) {
                oprot.writeI32(struct.attemptNumber);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftTaskId struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(3);
            if (incoming.get(0)) {
                struct.stageExecutionId = new ThriftStageExecutionId();
                struct.stageExecutionId.read(iprot);
                struct.setStageExecutionIdIsSet(true);
            }
            if (incoming.get(1)) {
                struct.id = iprot.readI32();
                struct.setIdIsSet(true);
            }
            if (incoming.get(2)) {
                struct.attemptNumber = iprot.readI32();
                struct.setAttemptNumberIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

