/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public enum ThriftNullCallClause
        implements org.apache.thrift.TEnum
{
    RETURN_NULL_ON_NULL_INPUT(0),
    CALLED_ON_NULL_INPUT(1);

    private final int value;

    private ThriftNullCallClause(int value)
    {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    @Override
    public int getValue()
    {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static ThriftNullCallClause findByValue(int value)
    {
        switch (value) {
            case 0:
                return RETURN_NULL_ON_NULL_INPUT;
            case 1:
                return CALLED_ON_NULL_INPUT;
            default:
                return null;
        }
    }
}
