/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.common.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-20")
public class ThriftTaskSource
        implements org.apache.thrift.TBase<ThriftTaskSource, ThriftTaskSource._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftTaskSource>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftTaskSource");

    private static final org.apache.thrift.protocol.TField PLAN_NODE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("planNodeId", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField SPLITS_FIELD_DESC = new org.apache.thrift.protocol.TField("splits", org.apache.thrift.protocol.TType.SET, (short) 2);
    private static final org.apache.thrift.protocol.TField NO_MORE_SPLITS_FOR_LIFESPAN_FIELD_DESC = new org.apache.thrift.protocol.TField("noMoreSplitsForLifespan", org.apache.thrift.protocol.TType.SET, (short) 3);
    private static final org.apache.thrift.protocol.TField NO_MORE_SPLITS_FIELD_DESC = new org.apache.thrift.protocol.TField("noMoreSplits", org.apache.thrift.protocol.TType.BOOL, (short) 4);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftTaskSourceStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftTaskSourceTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable String planNodeId; // required
    public @org.apache.thrift.annotation.Nullable java.util.Set<ThriftScheduledSplit> splits; // required
    public @org.apache.thrift.annotation.Nullable java.util.Set<ThriftLifespan> noMoreSplitsForLifespan; // required
    public boolean noMoreSplits; // required

    /**
     * The set of fields this struct contains, along with convenience methods for finding and manipulating them.
     */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        PLAN_NODE_ID((short) 1, "planNodeId"),
        SPLITS((short) 2, "splits"),
        NO_MORE_SPLITS_FOR_LIFESPAN((short) 3, "noMoreSplitsForLifespan"),
        NO_MORE_SPLITS((short) 4, "noMoreSplits");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // PLAN_NODE_ID
                    return PLAN_NODE_ID;
                case 2: // SPLITS
                    return SPLITS;
                case 3: // NO_MORE_SPLITS_FOR_LIFESPAN
                    return NO_MORE_SPLITS_FOR_LIFESPAN;
                case 4: // NO_MORE_SPLITS
                    return NO_MORE_SPLITS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) {
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __NOMORESPLITS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.PLAN_NODE_ID, new org.apache.thrift.meta_data.FieldMetaData("planNodeId", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftPlanNodeId")));
        tmpMap.put(_Fields.SPLITS, new org.apache.thrift.meta_data.FieldMetaData("splits", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftScheduledSplit.class))));
        tmpMap.put(_Fields.NO_MORE_SPLITS_FOR_LIFESPAN, new org.apache.thrift.meta_data.FieldMetaData("noMoreSplitsForLifespan", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET,
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLifespan.class))));
        tmpMap.put(_Fields.NO_MORE_SPLITS, new org.apache.thrift.meta_data.FieldMetaData("noMoreSplits", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftTaskSource.class, metaDataMap);
    }

    public ThriftTaskSource()
    {
    }

    public ThriftTaskSource(
            String planNodeId,
            java.util.Set<ThriftScheduledSplit> splits,
            java.util.Set<ThriftLifespan> noMoreSplitsForLifespan,
            boolean noMoreSplits)
    {
        this();
        this.planNodeId = planNodeId;
        this.splits = splits;
        this.noMoreSplitsForLifespan = noMoreSplitsForLifespan;
        this.noMoreSplits = noMoreSplits;
        setNoMoreSplitsIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftTaskSource(ThriftTaskSource other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetPlanNodeId()) {
            this.planNodeId = other.planNodeId;
        }
        if (other.isSetSplits()) {
            java.util.Set<ThriftScheduledSplit> __this__splits = new java.util.HashSet<ThriftScheduledSplit>(other.splits.size());
            for (ThriftScheduledSplit other_element : other.splits) {
                __this__splits.add(new ThriftScheduledSplit(other_element));
            }
            this.splits = __this__splits;
        }
        if (other.isSetNoMoreSplitsForLifespan()) {
            java.util.Set<ThriftLifespan> __this__noMoreSplitsForLifespan = new java.util.HashSet<ThriftLifespan>(other.noMoreSplitsForLifespan.size());
            for (ThriftLifespan other_element : other.noMoreSplitsForLifespan) {
                __this__noMoreSplitsForLifespan.add(new ThriftLifespan(other_element));
            }
            this.noMoreSplitsForLifespan = __this__noMoreSplitsForLifespan;
        }
        this.noMoreSplits = other.noMoreSplits;
    }

    @Override
    public ThriftTaskSource deepCopy()
    {
        return new ThriftTaskSource(this);
    }

    @Override
    public void clear()
    {
        this.planNodeId = null;
        this.splits = null;
        this.noMoreSplitsForLifespan = null;
        setNoMoreSplitsIsSet(false);
        this.noMoreSplits = false;
    }

    @org.apache.thrift.annotation.Nullable
    public String getPlanNodeId()
    {
        return this.planNodeId;
    }

    public ThriftTaskSource setPlanNodeId(@org.apache.thrift.annotation.Nullable String planNodeId)
    {
        this.planNodeId = planNodeId;
        return this;
    }

    public void unsetPlanNodeId()
    {
        this.planNodeId = null;
    }

    /**
     * Returns true if field planNodeId is set (has been assigned a value) and false otherwise
     */
    public boolean isSetPlanNodeId()
    {
        return this.planNodeId != null;
    }

    public void setPlanNodeIdIsSet(boolean value)
    {
        if (!value) {
            this.planNodeId = null;
        }
    }

    public int getSplitsSize()
    {
        return (this.splits == null) ? 0 : this.splits.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftScheduledSplit> getSplitsIterator()
    {
        return (this.splits == null) ? null : this.splits.iterator();
    }

    public void addToSplits(ThriftScheduledSplit elem)
    {
        if (this.splits == null) {
            this.splits = new java.util.HashSet<ThriftScheduledSplit>();
        }
        this.splits.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Set<ThriftScheduledSplit> getSplits()
    {
        return this.splits;
    }

    public ThriftTaskSource setSplits(@org.apache.thrift.annotation.Nullable java.util.Set<ThriftScheduledSplit> splits)
    {
        this.splits = splits;
        return this;
    }

    public void unsetSplits()
    {
        this.splits = null;
    }

    /**
     * Returns true if field splits is set (has been assigned a value) and false otherwise
     */
    public boolean isSetSplits()
    {
        return this.splits != null;
    }

    public void setSplitsIsSet(boolean value)
    {
        if (!value) {
            this.splits = null;
        }
    }

    public int getNoMoreSplitsForLifespanSize()
    {
        return (this.noMoreSplitsForLifespan == null) ? 0 : this.noMoreSplitsForLifespan.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<ThriftLifespan> getNoMoreSplitsForLifespanIterator()
    {
        return (this.noMoreSplitsForLifespan == null) ? null : this.noMoreSplitsForLifespan.iterator();
    }

    public void addToNoMoreSplitsForLifespan(ThriftLifespan elem)
    {
        if (this.noMoreSplitsForLifespan == null) {
            this.noMoreSplitsForLifespan = new java.util.HashSet<ThriftLifespan>();
        }
        this.noMoreSplitsForLifespan.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Set<ThriftLifespan> getNoMoreSplitsForLifespan()
    {
        return this.noMoreSplitsForLifespan;
    }

    public ThriftTaskSource setNoMoreSplitsForLifespan(@org.apache.thrift.annotation.Nullable java.util.Set<ThriftLifespan> noMoreSplitsForLifespan)
    {
        this.noMoreSplitsForLifespan = noMoreSplitsForLifespan;
        return this;
    }

    public void unsetNoMoreSplitsForLifespan()
    {
        this.noMoreSplitsForLifespan = null;
    }

    /**
     * Returns true if field noMoreSplitsForLifespan is set (has been assigned a value) and false otherwise
     */
    public boolean isSetNoMoreSplitsForLifespan()
    {
        return this.noMoreSplitsForLifespan != null;
    }

    public void setNoMoreSplitsForLifespanIsSet(boolean value)
    {
        if (!value) {
            this.noMoreSplitsForLifespan = null;
        }
    }

    public boolean isNoMoreSplits()
    {
        return this.noMoreSplits;
    }

    public ThriftTaskSource setNoMoreSplits(boolean noMoreSplits)
    {
        this.noMoreSplits = noMoreSplits;
        setNoMoreSplitsIsSet(true);
        return this;
    }

    public void unsetNoMoreSplits()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NOMORESPLITS_ISSET_ID);
    }

    /**
     * Returns true if field noMoreSplits is set (has been assigned a value) and false otherwise
     */
    public boolean isSetNoMoreSplits()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NOMORESPLITS_ISSET_ID);
    }

    public void setNoMoreSplitsIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NOMORESPLITS_ISSET_ID, value);
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case PLAN_NODE_ID:
                if (value == null) {
                    unsetPlanNodeId();
                }
                else {
                    setPlanNodeId((String) value);
                }
                break;

            case SPLITS:
                if (value == null) {
                    unsetSplits();
                }
                else {
                    setSplits((java.util.Set<ThriftScheduledSplit>) value);
                }
                break;

            case NO_MORE_SPLITS_FOR_LIFESPAN:
                if (value == null) {
                    unsetNoMoreSplitsForLifespan();
                }
                else {
                    setNoMoreSplitsForLifespan((java.util.Set<ThriftLifespan>) value);
                }
                break;

            case NO_MORE_SPLITS:
                if (value == null) {
                    unsetNoMoreSplits();
                }
                else {
                    setNoMoreSplits((Boolean) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case PLAN_NODE_ID:
                return getPlanNodeId();

            case SPLITS:
                return getSplits();

            case NO_MORE_SPLITS_FOR_LIFESPAN:
                return getNoMoreSplitsForLifespan();

            case NO_MORE_SPLITS:
                return isNoMoreSplits();
        }
        throw new IllegalStateException();
    }

    /**
     * Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
     */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case PLAN_NODE_ID:
                return isSetPlanNodeId();
            case SPLITS:
                return isSetSplits();
            case NO_MORE_SPLITS_FOR_LIFESPAN:
                return isSetNoMoreSplitsForLifespan();
            case NO_MORE_SPLITS:
                return isSetNoMoreSplits();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
        if (that instanceof ThriftTaskSource) {
            return this.equals((ThriftTaskSource) that);
        }
        return false;
    }

    public boolean equals(ThriftTaskSource that)
    {
        if (that == null) {
            return false;
        }
        if (this == that) {
            return true;
        }

        boolean this_present_planNodeId = true && this.isSetPlanNodeId();
        boolean that_present_planNodeId = true && that.isSetPlanNodeId();
        if (this_present_planNodeId || that_present_planNodeId) {
            if (!(this_present_planNodeId && that_present_planNodeId)) {
                return false;
            }
            if (!this.planNodeId.equals(that.planNodeId)) {
                return false;
            }
        }

        boolean this_present_splits = true && this.isSetSplits();
        boolean that_present_splits = true && that.isSetSplits();
        if (this_present_splits || that_present_splits) {
            if (!(this_present_splits && that_present_splits)) {
                return false;
            }
            if (!this.splits.equals(that.splits)) {
                return false;
            }
        }

        boolean this_present_noMoreSplitsForLifespan = true && this.isSetNoMoreSplitsForLifespan();
        boolean that_present_noMoreSplitsForLifespan = true && that.isSetNoMoreSplitsForLifespan();
        if (this_present_noMoreSplitsForLifespan || that_present_noMoreSplitsForLifespan) {
            if (!(this_present_noMoreSplitsForLifespan && that_present_noMoreSplitsForLifespan)) {
                return false;
            }
            if (!this.noMoreSplitsForLifespan.equals(that.noMoreSplitsForLifespan)) {
                return false;
            }
        }

        boolean this_present_noMoreSplits = true;
        boolean that_present_noMoreSplits = true;
        if (this_present_noMoreSplits || that_present_noMoreSplits) {
            if (!(this_present_noMoreSplits && that_present_noMoreSplits)) {
                return false;
            }
            if (this.noMoreSplits != that.noMoreSplits) {
                return false;
            }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetPlanNodeId()) ? 131071 : 524287);
        if (isSetPlanNodeId()) {
            hashCode = hashCode * 8191 + planNodeId.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetSplits()) ? 131071 : 524287);
        if (isSetSplits()) {
            hashCode = hashCode * 8191 + splits.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetNoMoreSplitsForLifespan()) ? 131071 : 524287);
        if (isSetNoMoreSplitsForLifespan()) {
            hashCode = hashCode * 8191 + noMoreSplitsForLifespan.hashCode();
        }

        hashCode = hashCode * 8191 + ((noMoreSplits) ? 131071 : 524287);

        return hashCode;
    }

    @Override
    public int compareTo(ThriftTaskSource other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetPlanNodeId(), other.isSetPlanNodeId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetPlanNodeId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.planNodeId, other.planNodeId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetSplits(), other.isSetSplits());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSplits()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.splits, other.splits);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetNoMoreSplitsForLifespan(), other.isSetNoMoreSplitsForLifespan());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetNoMoreSplitsForLifespan()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.noMoreSplitsForLifespan, other.noMoreSplitsForLifespan);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetNoMoreSplits(), other.isSetNoMoreSplits());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetNoMoreSplits()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.noMoreSplits, other.noMoreSplits);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftTaskSource(");
        boolean first = true;

        sb.append("planNodeId:");
        if (this.planNodeId == null) {
            sb.append("null");
        }
        else {
            sb.append(this.planNodeId);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("splits:");
        if (this.splits == null) {
            sb.append("null");
        }
        else {
            sb.append(this.splits);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("noMoreSplitsForLifespan:");
        if (this.noMoreSplitsForLifespan == null) {
            sb.append("null");
        }
        else {
            sb.append(this.noMoreSplitsForLifespan);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("noMoreSplits:");
        sb.append(this.noMoreSplits);
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftTaskSourceStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskSourceStandardScheme getScheme()
        {
            return new ThriftTaskSourceStandardScheme();
        }
    }

    private static class ThriftTaskSourceStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftTaskSource>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftTaskSource struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // PLAN_NODE_ID
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.planNodeId = iprot.readString();
                            struct.setPlanNodeIdIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // SPLITS
                        if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
                            {
                                org.apache.thrift.protocol.TSet _set10 = iprot.readSetBegin();
                                struct.splits = new java.util.HashSet<ThriftScheduledSplit>(2 * _set10.size);
                                @org.apache.thrift.annotation.Nullable ThriftScheduledSplit _elem11;
                                for (int _i12 = 0; _i12 < _set10.size; ++_i12) {
                                    _elem11 = new ThriftScheduledSplit();
                                    _elem11.read(iprot);
                                    struct.splits.add(_elem11);
                                }
                                iprot.readSetEnd();
                            }
                            struct.setSplitsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // NO_MORE_SPLITS_FOR_LIFESPAN
                        if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
                            {
                                org.apache.thrift.protocol.TSet _set13 = iprot.readSetBegin();
                                struct.noMoreSplitsForLifespan = new java.util.HashSet<ThriftLifespan>(2 * _set13.size);
                                @org.apache.thrift.annotation.Nullable ThriftLifespan _elem14;
                                for (int _i15 = 0; _i15 < _set13.size; ++_i15) {
                                    _elem14 = new ThriftLifespan();
                                    _elem14.read(iprot);
                                    struct.noMoreSplitsForLifespan.add(_elem14);
                                }
                                iprot.readSetEnd();
                            }
                            struct.setNoMoreSplitsForLifespanIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // NO_MORE_SPLITS
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.noMoreSplits = iprot.readBool();
                            struct.setNoMoreSplitsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftTaskSource struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.planNodeId != null) {
                oprot.writeFieldBegin(PLAN_NODE_ID_FIELD_DESC);
                oprot.writeString(struct.planNodeId);
                oprot.writeFieldEnd();
            }
            if (struct.splits != null) {
                oprot.writeFieldBegin(SPLITS_FIELD_DESC);
                {
                    oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.splits.size()));
                    for (ThriftScheduledSplit _iter16 : struct.splits) {
                        _iter16.write(oprot);
                    }
                    oprot.writeSetEnd();
                }
                oprot.writeFieldEnd();
            }
            if (struct.noMoreSplitsForLifespan != null) {
                oprot.writeFieldBegin(NO_MORE_SPLITS_FOR_LIFESPAN_FIELD_DESC);
                {
                    oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.noMoreSplitsForLifespan.size()));
                    for (ThriftLifespan _iter17 : struct.noMoreSplitsForLifespan) {
                        _iter17.write(oprot);
                    }
                    oprot.writeSetEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(NO_MORE_SPLITS_FIELD_DESC);
            oprot.writeBool(struct.noMoreSplits);
            oprot.writeFieldEnd();
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftTaskSourceTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftTaskSourceTupleScheme getScheme()
        {
            return new ThriftTaskSourceTupleScheme();
        }
    }

    private static class ThriftTaskSourceTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftTaskSource>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftTaskSource struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetPlanNodeId()) {
                optionals.set(0);
            }
            if (struct.isSetSplits()) {
                optionals.set(1);
            }
            if (struct.isSetNoMoreSplitsForLifespan()) {
                optionals.set(2);
            }
            if (struct.isSetNoMoreSplits()) {
                optionals.set(3);
            }
            oprot.writeBitSet(optionals, 4);
            if (struct.isSetPlanNodeId()) {
                oprot.writeString(struct.planNodeId);
            }
            if (struct.isSetSplits()) {
                {
                    oprot.writeI32(struct.splits.size());
                    for (ThriftScheduledSplit _iter18 : struct.splits) {
                        _iter18.write(oprot);
                    }
                }
            }
            if (struct.isSetNoMoreSplitsForLifespan()) {
                {
                    oprot.writeI32(struct.noMoreSplitsForLifespan.size());
                    for (ThriftLifespan _iter19 : struct.noMoreSplitsForLifespan) {
                        _iter19.write(oprot);
                    }
                }
            }
            if (struct.isSetNoMoreSplits()) {
                oprot.writeBool(struct.noMoreSplits);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftTaskSource struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(4);
            if (incoming.get(0)) {
                struct.planNodeId = iprot.readString();
                struct.setPlanNodeIdIsSet(true);
            }
            if (incoming.get(1)) {
                {
                    org.apache.thrift.protocol.TSet _set20 = iprot.readSetBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.splits = new java.util.HashSet<ThriftScheduledSplit>(2 * _set20.size);
                    @org.apache.thrift.annotation.Nullable ThriftScheduledSplit _elem21;
                    for (int _i22 = 0; _i22 < _set20.size; ++_i22) {
                        _elem21 = new ThriftScheduledSplit();
                        _elem21.read(iprot);
                        struct.splits.add(_elem21);
                    }
                }
                struct.setSplitsIsSet(true);
            }
            if (incoming.get(2)) {
                {
                    org.apache.thrift.protocol.TSet _set23 = iprot.readSetBegin(org.apache.thrift.protocol.TType.STRUCT);
                    struct.noMoreSplitsForLifespan = new java.util.HashSet<ThriftLifespan>(2 * _set23.size);
                    @org.apache.thrift.annotation.Nullable ThriftLifespan _elem24;
                    for (int _i25 = 0; _i25 < _set23.size; ++_i25) {
                        _elem24 = new ThriftLifespan();
                        _elem24.read(iprot);
                        struct.noMoreSplitsForLifespan.add(_elem24);
                    }
                }
                struct.setNoMoreSplitsForLifespanIsSet(true);
            }
            if (incoming.get(3)) {
                struct.noMoreSplits = iprot.readBool();
                struct.setNoMoreSplitsIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

