/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-18")
public class ThriftVarcharEnumMap
        implements org.apache.thrift.TBase<ThriftVarcharEnumMap, ThriftVarcharEnumMap._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftVarcharEnumMap>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftVarcharEnumMap");

    private static final org.apache.thrift.protocol.TField TYPE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("typeName", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField ENUM_MAP_FIELD_DESC = new org.apache.thrift.protocol.TField("enumMap", org.apache.thrift.protocol.TType.MAP, (short) 2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftVarcharEnumMapStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftVarcharEnumMapTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable String typeName; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<String, String> enumMap; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        TYPE_NAME((short) 1, "typeName"),
        ENUM_MAP((short) 2, "enumMap");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // TYPE_NAME
                    return TYPE_NAME;
                case 2: // ENUM_MAP
                    return ENUM_MAP;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) {
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.TYPE_NAME, new org.apache.thrift.meta_data.FieldMetaData("typeName", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.ENUM_MAP, new org.apache.thrift.meta_data.FieldMetaData("enumMap", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftVarcharEnumMap.class, metaDataMap);
    }

    public ThriftVarcharEnumMap()
    {
    }

    public ThriftVarcharEnumMap(
            String typeName,
            java.util.Map<String, String> enumMap)
    {
        this();
        this.typeName = typeName;
        this.enumMap = enumMap;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftVarcharEnumMap(ThriftVarcharEnumMap other)
    {
        if (other.isSetTypeName()) {
            this.typeName = other.typeName;
        }
        if (other.isSetEnumMap()) {
            java.util.Map<String, String> __this__enumMap = new java.util.HashMap<String, String>(other.enumMap);
            this.enumMap = __this__enumMap;
        }
    }

    @Override
    public ThriftVarcharEnumMap deepCopy()
    {
        return new ThriftVarcharEnumMap(this);
    }

    @Override
    public void clear()
    {
        this.typeName = null;
        this.enumMap = null;
    }

    @org.apache.thrift.annotation.Nullable
    public String getTypeName()
    {
        return this.typeName;
    }

    public ThriftVarcharEnumMap setTypeName(@org.apache.thrift.annotation.Nullable String typeName)
    {
        this.typeName = typeName;
        return this;
    }

    public void unsetTypeName()
    {
        this.typeName = null;
    }

    /** Returns true if field typeName is set (has been assigned a value) and false otherwise */
    public boolean isSetTypeName()
    {
        return this.typeName != null;
    }

    public void setTypeNameIsSet(boolean value)
    {
        if (!value) {
            this.typeName = null;
        }
    }

    public int getEnumMapSize()
    {
        return (this.enumMap == null) ? 0 : this.enumMap.size();
    }

    public void putToEnumMap(String key, String val)
    {
        if (this.enumMap == null) {
            this.enumMap = new java.util.HashMap<String, String>();
        }
        this.enumMap.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<String, String> getEnumMap()
    {
        return this.enumMap;
    }

    public ThriftVarcharEnumMap setEnumMap(@org.apache.thrift.annotation.Nullable java.util.Map<String, String> enumMap)
    {
        this.enumMap = enumMap;
        return this;
    }

    public void unsetEnumMap()
    {
        this.enumMap = null;
    }

    /** Returns true if field enumMap is set (has been assigned a value) and false otherwise */
    public boolean isSetEnumMap()
    {
        return this.enumMap != null;
    }

    public void setEnumMapIsSet(boolean value)
    {
        if (!value) {
            this.enumMap = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case TYPE_NAME:
                if (value == null) {
                    unsetTypeName();
                }
                else {
                    setTypeName((String) value);
                }
                break;

            case ENUM_MAP:
                if (value == null) {
                    unsetEnumMap();
                }
                else {
                    setEnumMap((java.util.Map<String, String>) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case TYPE_NAME:
                return getTypeName();

            case ENUM_MAP:
                return getEnumMap();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case TYPE_NAME:
                return isSetTypeName();
            case ENUM_MAP:
                return isSetEnumMap();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
        if (that instanceof ThriftVarcharEnumMap) {
            return this.equals((ThriftVarcharEnumMap) that);
        }
        return false;
    }

    public boolean equals(ThriftVarcharEnumMap that)
    {
        if (that == null) {
            return false;
        }
        if (this == that) {
            return true;
        }

        boolean this_present_typeName = true && this.isSetTypeName();
        boolean that_present_typeName = true && that.isSetTypeName();
        if (this_present_typeName || that_present_typeName) {
            if (!(this_present_typeName && that_present_typeName)) {
                return false;
            }
            if (!this.typeName.equals(that.typeName)) {
                return false;
            }
        }

        boolean this_present_enumMap = true && this.isSetEnumMap();
        boolean that_present_enumMap = true && that.isSetEnumMap();
        if (this_present_enumMap || that_present_enumMap) {
            if (!(this_present_enumMap && that_present_enumMap)) {
                return false;
            }
            if (!this.enumMap.equals(that.enumMap)) {
                return false;
            }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetTypeName()) ? 131071 : 524287);
        if (isSetTypeName()) {
            hashCode = hashCode * 8191 + typeName.hashCode();
        }

        hashCode = hashCode * 8191 + ((isSetEnumMap()) ? 131071 : 524287);
        if (isSetEnumMap()) {
            hashCode = hashCode * 8191 + enumMap.hashCode();
        }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftVarcharEnumMap other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetTypeName(), other.isSetTypeName());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTypeName()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typeName, other.typeName);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetEnumMap(), other.isSetEnumMap());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetEnumMap()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enumMap, other.enumMap);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftVarcharEnumMap(");
        boolean first = true;

        sb.append("typeName:");
        if (this.typeName == null) {
            sb.append("null");
        }
        else {
            sb.append(this.typeName);
        }
        first = false;
        if (!first) {
            sb.append(", ");
        }
        sb.append("enumMap:");
        if (this.enumMap == null) {
            sb.append("null");
        }
        else {
            sb.append(this.enumMap);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftVarcharEnumMapStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftVarcharEnumMapStandardScheme getScheme()
        {
            return new ThriftVarcharEnumMapStandardScheme();
        }
    }

    private static class ThriftVarcharEnumMapStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftVarcharEnumMap>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftVarcharEnumMap struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // TYPE_NAME
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.typeName = iprot.readString();
                            struct.setTypeNameIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // ENUM_MAP
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                                struct.enumMap = new java.util.HashMap<String, String>(2 * _map0.size);
                                @org.apache.thrift.annotation.Nullable String _key1;
                                @org.apache.thrift.annotation.Nullable String _val2;
                                for (int _i3 = 0; _i3 < _map0.size; ++_i3) {
                                    _key1 = iprot.readString();
                                    _val2 = iprot.readString();
                                    struct.enumMap.put(_key1, _val2);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setEnumMapIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftVarcharEnumMap struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.typeName != null) {
                oprot.writeFieldBegin(TYPE_NAME_FIELD_DESC);
                oprot.writeString(struct.typeName);
                oprot.writeFieldEnd();
            }
            if (struct.enumMap != null) {
                oprot.writeFieldBegin(ENUM_MAP_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.enumMap.size()));
                    for (java.util.Map.Entry<String, String> _iter4 : struct.enumMap.entrySet()) {
                        oprot.writeString(_iter4.getKey());
                        oprot.writeString(_iter4.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftVarcharEnumMapTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftVarcharEnumMapTupleScheme getScheme()
        {
            return new ThriftVarcharEnumMapTupleScheme();
        }
    }

    private static class ThriftVarcharEnumMapTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftVarcharEnumMap>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftVarcharEnumMap struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetTypeName()) {
                optionals.set(0);
            }
            if (struct.isSetEnumMap()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetTypeName()) {
                oprot.writeString(struct.typeName);
            }
            if (struct.isSetEnumMap()) {
                {
                    oprot.writeI32(struct.enumMap.size());
                    for (java.util.Map.Entry<String, String> _iter5 : struct.enumMap.entrySet()) {
                        oprot.writeString(_iter5.getKey());
                        oprot.writeString(_iter5.getValue());
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftVarcharEnumMap struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.typeName = iprot.readString();
                struct.setTypeNameIsSet(true);
            }
            if (incoming.get(1)) {
                {
                    org.apache.thrift.protocol.TMap _map6 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING);
                    struct.enumMap = new java.util.HashMap<String, String>(2 * _map6.size);
                    @org.apache.thrift.annotation.Nullable String _key7;
                    @org.apache.thrift.annotation.Nullable String _val8;
                    for (int _i9 = 0; _i9 < _map6.size; ++_i9) {
                        _key7 = iprot.readString();
                        _val8 = iprot.readString();
                        struct.enumMap.put(_key7, _val8);
                    }
                }
                struct.setEnumMapIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

