/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-18")
public class ThriftSplit
        implements org.apache.thrift.TBase<ThriftSplit, ThriftSplit._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftSplit>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftSplit");

    private static final org.apache.thrift.protocol.TField CONNECTOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("connectorId", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField TRANSACTION_HANDLE_FIELD_DESC = new org.apache.thrift.protocol.TField("transactionHandle", org.apache.thrift.protocol.TType.STRING, (short) 2);
    private static final org.apache.thrift.protocol.TField CONNECTOR_SPLIT_FIELD_DESC = new org.apache.thrift.protocol.TField("connectorSplit", org.apache.thrift.protocol.TType.STRING, (short) 3);
    private static final org.apache.thrift.protocol.TField LIFESPAN_FIELD_DESC = new org.apache.thrift.protocol.TField("lifespan", org.apache.thrift.protocol.TType.STRUCT, (short) 4);
    private static final org.apache.thrift.protocol.TField SPLIT_CONTEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("splitContext", org.apache.thrift.protocol.TType.STRING, (short) 5);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftSplitStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftSplitTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable String connectorId; // required
    public @org.apache.thrift.annotation.Nullable String transactionHandle; // required
    public @org.apache.thrift.annotation.Nullable String connectorSplit; // required
    public @org.apache.thrift.annotation.Nullable ThriftLifespan lifespan; // required
    public @org.apache.thrift.annotation.Nullable String splitContext; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        CONNECTOR_ID((short) 1, "connectorId"),
        TRANSACTION_HANDLE((short) 2, "transactionHandle"),
        CONNECTOR_SPLIT((short) 3, "connectorSplit"),
        LIFESPAN((short) 4, "lifespan"),
        SPLIT_CONTEXT((short) 5, "splitContext");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // CONNECTOR_ID
                    return CONNECTOR_ID;
                case 2: // TRANSACTION_HANDLE
                    return TRANSACTION_HANDLE;
                case 3: // CONNECTOR_SPLIT
                    return CONNECTOR_SPLIT;
                case 4: // LIFESPAN
                    return LIFESPAN;
                case 5: // SPLIT_CONTEXT
                    return SPLIT_CONTEXT;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.CONNECTOR_ID, new org.apache.thrift.meta_data.FieldMetaData("connectorId", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftConnectorId")));
        tmpMap.put(_Fields.TRANSACTION_HANDLE, new org.apache.thrift.meta_data.FieldMetaData("transactionHandle", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftConnectorTransactionHandle")));
        tmpMap.put(_Fields.CONNECTOR_SPLIT, new org.apache.thrift.meta_data.FieldMetaData("connectorSplit", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftConnectorSplit")));
        tmpMap.put(_Fields.LIFESPAN, new org.apache.thrift.meta_data.FieldMetaData("lifespan", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLifespan.class)));
        tmpMap.put(_Fields.SPLIT_CONTEXT, new org.apache.thrift.meta_data.FieldMetaData("splitContext", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, "ThriftSplitContext")));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftSplit.class, metaDataMap);
    }

    public ThriftSplit()
    {
    }

    public ThriftSplit(
            String connectorId,
            String transactionHandle,
            String connectorSplit,
            ThriftLifespan lifespan,
            String splitContext)
    {
        this();
        this.connectorId = connectorId;
        this.transactionHandle = transactionHandle;
        this.connectorSplit = connectorSplit;
        this.lifespan = lifespan;
        this.splitContext = splitContext;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftSplit(ThriftSplit other)
    {
        if (other.isSetConnectorId()) {
            this.connectorId = other.connectorId;
        }
        if (other.isSetTransactionHandle()) {
            this.transactionHandle = other.transactionHandle;
        }
        if (other.isSetConnectorSplit()) {
            this.connectorSplit = other.connectorSplit;
        }
        if (other.isSetLifespan()) {
            this.lifespan = new ThriftLifespan(other.lifespan);
        }
        if (other.isSetSplitContext()) {
            this.splitContext = other.splitContext;
        }
    }

    @Override
    public ThriftSplit deepCopy()
    {
        return new ThriftSplit(this);
    }

    @Override
    public void clear()
    {
        this.connectorId = null;
        this.transactionHandle = null;
        this.connectorSplit = null;
        this.lifespan = null;
        this.splitContext = null;
    }

    @org.apache.thrift.annotation.Nullable
    public String getConnectorId()
    {
        return this.connectorId;
    }

    public ThriftSplit setConnectorId(@org.apache.thrift.annotation.Nullable String connectorId)
    {
        this.connectorId = connectorId;
        return this;
    }

    public void unsetConnectorId()
    {
        this.connectorId = null;
    }

    /** Returns true if field connectorId is set (has been assigned a value) and false otherwise */
    public boolean isSetConnectorId()
    {
        return this.connectorId != null;
    }

    public void setConnectorIdIsSet(boolean value)
    {
        if (!value) {
            this.connectorId = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public String getTransactionHandle()
    {
        return this.transactionHandle;
    }

    public ThriftSplit setTransactionHandle(@org.apache.thrift.annotation.Nullable String transactionHandle)
    {
        this.transactionHandle = transactionHandle;
        return this;
    }

    public void unsetTransactionHandle()
    {
        this.transactionHandle = null;
    }

    /** Returns true if field transactionHandle is set (has been assigned a value) and false otherwise */
    public boolean isSetTransactionHandle()
    {
        return this.transactionHandle != null;
    }

    public void setTransactionHandleIsSet(boolean value)
    {
        if (!value) {
            this.transactionHandle = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public String getConnectorSplit()
    {
        return this.connectorSplit;
    }

    public ThriftSplit setConnectorSplit(@org.apache.thrift.annotation.Nullable String connectorSplit)
    {
        this.connectorSplit = connectorSplit;
        return this;
    }

    public void unsetConnectorSplit()
    {
        this.connectorSplit = null;
    }

    /** Returns true if field connectorSplit is set (has been assigned a value) and false otherwise */
    public boolean isSetConnectorSplit()
    {
        return this.connectorSplit != null;
    }

    public void setConnectorSplitIsSet(boolean value)
    {
        if (!value) {
            this.connectorSplit = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public ThriftLifespan getLifespan()
    {
        return this.lifespan;
    }

    public ThriftSplit setLifespan(@org.apache.thrift.annotation.Nullable ThriftLifespan lifespan)
    {
        this.lifespan = lifespan;
        return this;
    }

    public void unsetLifespan()
    {
        this.lifespan = null;
    }

    /** Returns true if field lifespan is set (has been assigned a value) and false otherwise */
    public boolean isSetLifespan()
    {
        return this.lifespan != null;
    }

    public void setLifespanIsSet(boolean value)
    {
        if (!value) {
            this.lifespan = null;
        }
    }

    @org.apache.thrift.annotation.Nullable
    public String getSplitContext()
    {
        return this.splitContext;
    }

    public ThriftSplit setSplitContext(@org.apache.thrift.annotation.Nullable String splitContext)
    {
        this.splitContext = splitContext;
        return this;
    }

    public void unsetSplitContext()
    {
        this.splitContext = null;
    }

    /** Returns true if field splitContext is set (has been assigned a value) and false otherwise */
    public boolean isSetSplitContext()
    {
        return this.splitContext != null;
    }

    public void setSplitContextIsSet(boolean value)
    {
        if (!value) {
            this.splitContext = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case CONNECTOR_ID:
                if (value == null) {
                    unsetConnectorId();
                }
                else {
                    setConnectorId((String) value);
                }
                break;

            case TRANSACTION_HANDLE:
                if (value == null) {
                    unsetTransactionHandle();
                }
                else {
                    setTransactionHandle((String) value);
                }
                break;

            case CONNECTOR_SPLIT:
                if (value == null) {
                    unsetConnectorSplit();
                }
                else {
                    setConnectorSplit((String) value);
                }
                break;

            case LIFESPAN:
                if (value == null) {
                    unsetLifespan();
                }
                else {
                    setLifespan((ThriftLifespan) value);
                }
                break;

            case SPLIT_CONTEXT:
                if (value == null) {
                    unsetSplitContext();
                }
                else {
                    setSplitContext((String) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case CONNECTOR_ID:
                return getConnectorId();

            case TRANSACTION_HANDLE:
                return getTransactionHandle();

            case CONNECTOR_SPLIT:
                return getConnectorSplit();

            case LIFESPAN:
                return getLifespan();

            case SPLIT_CONTEXT:
                return getSplitContext();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case CONNECTOR_ID:
                return isSetConnectorId();
            case TRANSACTION_HANDLE:
                return isSetTransactionHandle();
            case CONNECTOR_SPLIT:
                return isSetConnectorSplit();
            case LIFESPAN:
                return isSetLifespan();
            case SPLIT_CONTEXT:
                return isSetSplitContext();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftSplit) {
        return this.equals((ThriftSplit) that);
      }
        return false;
    }

    public boolean equals(ThriftSplit that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_connectorId = true && this.isSetConnectorId();
        boolean that_present_connectorId = true && that.isSetConnectorId();
        if (this_present_connectorId || that_present_connectorId) {
          if (!(this_present_connectorId && that_present_connectorId)) {
            return false;
          }
          if (!this.connectorId.equals(that.connectorId)) {
            return false;
          }
        }

        boolean this_present_transactionHandle = true && this.isSetTransactionHandle();
        boolean that_present_transactionHandle = true && that.isSetTransactionHandle();
        if (this_present_transactionHandle || that_present_transactionHandle) {
          if (!(this_present_transactionHandle && that_present_transactionHandle)) {
            return false;
          }
          if (!this.transactionHandle.equals(that.transactionHandle)) {
            return false;
          }
        }

        boolean this_present_connectorSplit = true && this.isSetConnectorSplit();
        boolean that_present_connectorSplit = true && that.isSetConnectorSplit();
        if (this_present_connectorSplit || that_present_connectorSplit) {
          if (!(this_present_connectorSplit && that_present_connectorSplit)) {
            return false;
          }
          if (!this.connectorSplit.equals(that.connectorSplit)) {
            return false;
          }
        }

        boolean this_present_lifespan = true && this.isSetLifespan();
        boolean that_present_lifespan = true && that.isSetLifespan();
        if (this_present_lifespan || that_present_lifespan) {
          if (!(this_present_lifespan && that_present_lifespan)) {
            return false;
          }
          if (!this.lifespan.equals(that.lifespan)) {
            return false;
          }
        }

        boolean this_present_splitContext = true && this.isSetSplitContext();
        boolean that_present_splitContext = true && that.isSetSplitContext();
        if (this_present_splitContext || that_present_splitContext) {
          if (!(this_present_splitContext && that_present_splitContext)) {
            return false;
          }
          if (!this.splitContext.equals(that.splitContext)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetConnectorId()) ? 131071 : 524287);
      if (isSetConnectorId()) {
        hashCode = hashCode * 8191 + connectorId.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetTransactionHandle()) ? 131071 : 524287);
      if (isSetTransactionHandle()) {
        hashCode = hashCode * 8191 + transactionHandle.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetConnectorSplit()) ? 131071 : 524287);
      if (isSetConnectorSplit()) {
        hashCode = hashCode * 8191 + connectorSplit.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetLifespan()) ? 131071 : 524287);
      if (isSetLifespan()) {
        hashCode = hashCode * 8191 + lifespan.hashCode();
      }

        hashCode = hashCode * 8191 + ((isSetSplitContext()) ? 131071 : 524287);
      if (isSetSplitContext()) {
        hashCode = hashCode * 8191 + splitContext.hashCode();
      }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftSplit other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetConnectorId(), other.isSetConnectorId());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetConnectorId()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.connectorId, other.connectorId);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetTransactionHandle(), other.isSetTransactionHandle());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTransactionHandle()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transactionHandle, other.transactionHandle);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetConnectorSplit(), other.isSetConnectorSplit());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetConnectorSplit()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.connectorSplit, other.connectorSplit);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetLifespan(), other.isSetLifespan());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetLifespan()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lifespan, other.lifespan);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetSplitContext(), other.isSetSplitContext());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetSplitContext()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.splitContext, other.splitContext);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftSplit(");
        boolean first = true;

        sb.append("connectorId:");
        if (this.connectorId == null) {
            sb.append("null");
        }
        else {
            sb.append(this.connectorId);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("transactionHandle:");
        if (this.transactionHandle == null) {
            sb.append("null");
        }
        else {
            sb.append(this.transactionHandle);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("connectorSplit:");
        if (this.connectorSplit == null) {
            sb.append("null");
        }
        else {
            sb.append(this.connectorSplit);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("lifespan:");
        if (this.lifespan == null) {
            sb.append("null");
        }
        else {
            sb.append(this.lifespan);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("splitContext:");
        if (this.splitContext == null) {
            sb.append("null");
        }
        else {
            sb.append(this.splitContext);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
        if (lifespan != null) {
            lifespan.validate();
        }
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftSplitStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftSplitStandardScheme getScheme()
        {
            return new ThriftSplitStandardScheme();
        }
    }

    private static class ThriftSplitStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftSplit>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftSplit struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // CONNECTOR_ID
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.connectorId = iprot.readString();
                            struct.setConnectorIdIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // TRANSACTION_HANDLE
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.transactionHandle = iprot.readString();
                            struct.setTransactionHandleIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // CONNECTOR_SPLIT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.connectorSplit = iprot.readString();
                            struct.setConnectorSplitIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // LIFESPAN
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                            struct.lifespan = new ThriftLifespan();
                            struct.lifespan.read(iprot);
                            struct.setLifespanIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 5: // SPLIT_CONTEXT
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.splitContext = iprot.readString();
                            struct.setSplitContextIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftSplit struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.connectorId != null) {
                oprot.writeFieldBegin(CONNECTOR_ID_FIELD_DESC);
                oprot.writeString(struct.connectorId);
                oprot.writeFieldEnd();
            }
            if (struct.transactionHandle != null) {
                oprot.writeFieldBegin(TRANSACTION_HANDLE_FIELD_DESC);
                oprot.writeString(struct.transactionHandle);
                oprot.writeFieldEnd();
            }
            if (struct.connectorSplit != null) {
                oprot.writeFieldBegin(CONNECTOR_SPLIT_FIELD_DESC);
                oprot.writeString(struct.connectorSplit);
                oprot.writeFieldEnd();
            }
            if (struct.lifespan != null) {
                oprot.writeFieldBegin(LIFESPAN_FIELD_DESC);
                struct.lifespan.write(oprot);
                oprot.writeFieldEnd();
            }
            if (struct.splitContext != null) {
                oprot.writeFieldBegin(SPLIT_CONTEXT_FIELD_DESC);
                oprot.writeString(struct.splitContext);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftSplitTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftSplitTupleScheme getScheme()
        {
            return new ThriftSplitTupleScheme();
        }
    }

    private static class ThriftSplitTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftSplit>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftSplit struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetConnectorId()) {
                optionals.set(0);
            }
            if (struct.isSetTransactionHandle()) {
                optionals.set(1);
            }
            if (struct.isSetConnectorSplit()) {
                optionals.set(2);
            }
            if (struct.isSetLifespan()) {
                optionals.set(3);
            }
            if (struct.isSetSplitContext()) {
                optionals.set(4);
            }
            oprot.writeBitSet(optionals, 5);
            if (struct.isSetConnectorId()) {
                oprot.writeString(struct.connectorId);
            }
            if (struct.isSetTransactionHandle()) {
                oprot.writeString(struct.transactionHandle);
            }
            if (struct.isSetConnectorSplit()) {
                oprot.writeString(struct.connectorSplit);
            }
            if (struct.isSetLifespan()) {
                struct.lifespan.write(oprot);
            }
            if (struct.isSetSplitContext()) {
                oprot.writeString(struct.splitContext);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftSplit struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(5);
            if (incoming.get(0)) {
                struct.connectorId = iprot.readString();
                struct.setConnectorIdIsSet(true);
            }
            if (incoming.get(1)) {
                struct.transactionHandle = iprot.readString();
                struct.setTransactionHandleIsSet(true);
            }
            if (incoming.get(2)) {
                struct.connectorSplit = iprot.readString();
                struct.setConnectorSplitIsSet(true);
            }
            if (incoming.get(3)) {
                struct.lifespan = new ThriftLifespan();
                struct.lifespan.read(iprot);
                struct.setLifespanIsSet(true);
            }
            if (incoming.get(4)) {
                struct.splitContext = iprot.readString();
                struct.setSplitContextIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

