/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package com.facebook.presto.experimental.auto_gen;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-03-18")
public class ThriftOutputBuffers
        implements org.apache.thrift.TBase<ThriftOutputBuffers, ThriftOutputBuffers._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftOutputBuffers>
{
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftOutputBuffers");

    private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short) 1);
    private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.I64, (short) 2);
    private static final org.apache.thrift.protocol.TField NO_MORE_BUFFER_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("noMoreBufferIds", org.apache.thrift.protocol.TType.BOOL, (short) 3);
    private static final org.apache.thrift.protocol.TField BUFFERS_FIELD_DESC = new org.apache.thrift.protocol.TField("buffers", org.apache.thrift.protocol.TType.MAP, (short) 4);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftOutputBuffersStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftOutputBuffersTupleSchemeFactory();

    /**
     *
     * @see ThriftBufferType
     */
    public @org.apache.thrift.annotation.Nullable ThriftBufferType type; // required
    public long version; // required
    public boolean noMoreBufferIds; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<Integer, Integer> buffers; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields
            implements org.apache.thrift.TFieldIdEnum
    {
        /**
         *
         * @see ThriftBufferType
         */
        TYPE((short) 1, "type"),
        VERSION((short) 2, "version"),
        NO_MORE_BUFFER_IDS((short) 3, "noMoreBufferIds"),
        BUFFERS((short) 4, "buffers");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId)
        {
            switch (fieldId) {
                case 1: // TYPE
                    return TYPE;
                case 2: // VERSION
                    return VERSION;
                case 3: // NO_MORE_BUFFER_IDS
                    return NO_MORE_BUFFER_IDS;
                case 4: // BUFFERS
                    return BUFFERS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId)
        {
            _Fields fields = findByThriftId(fieldId);
          if (fields == null) {
            throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
          }
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(String name)
        {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName)
        {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId()
        {
            return _thriftId;
        }

        @Override
        public String getFieldName()
        {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final int __VERSION_ISSET_ID = 0;
    private static final int __NOMOREBUFFERIDS_ISSET_ID = 1;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftBufferType.class)));
        tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
        tmpMap.put(_Fields.NO_MORE_BUFFER_IDS, new org.apache.thrift.meta_data.FieldMetaData("noMoreBufferIds", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
        tmpMap.put(_Fields.BUFFERS, new org.apache.thrift.meta_data.FieldMetaData("buffers", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32, "ThriftOutputBufferId"),
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftOutputBuffers.class, metaDataMap);
    }

    public ThriftOutputBuffers()
    {
    }

    public ThriftOutputBuffers(
            ThriftBufferType type,
            long version,
            boolean noMoreBufferIds,
            java.util.Map<Integer, Integer> buffers)
    {
        this();
        this.type = type;
        this.version = version;
        setVersionIsSet(true);
        this.noMoreBufferIds = noMoreBufferIds;
        setNoMoreBufferIdsIsSet(true);
        this.buffers = buffers;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ThriftOutputBuffers(ThriftOutputBuffers other)
    {
        __isset_bitfield = other.__isset_bitfield;
        if (other.isSetType()) {
            this.type = other.type;
        }
        this.version = other.version;
        this.noMoreBufferIds = other.noMoreBufferIds;
        if (other.isSetBuffers()) {
            java.util.Map<Integer, Integer> __this__buffers = new java.util.HashMap<Integer, Integer>(other.buffers.size());
            for (java.util.Map.Entry<Integer, Integer> other_element : other.buffers.entrySet()) {

                Integer other_element_key = other_element.getKey();
                Integer other_element_value = other_element.getValue();

                Integer __this__buffers_copy_key = other_element_key;

                Integer __this__buffers_copy_value = other_element_value;

                __this__buffers.put(__this__buffers_copy_key, __this__buffers_copy_value);
            }
            this.buffers = __this__buffers;
        }
    }

    @Override
    public ThriftOutputBuffers deepCopy()
    {
        return new ThriftOutputBuffers(this);
    }

    @Override
    public void clear()
    {
        this.type = null;
        setVersionIsSet(false);
        this.version = 0;
        setNoMoreBufferIdsIsSet(false);
        this.noMoreBufferIds = false;
        this.buffers = null;
    }

    /**
     *
     * @see ThriftBufferType
     */
    @org.apache.thrift.annotation.Nullable
    public ThriftBufferType getType()
    {
        return this.type;
    }

    /**
     *
     * @see ThriftBufferType
     */
    public ThriftOutputBuffers setType(@org.apache.thrift.annotation.Nullable ThriftBufferType type)
    {
        this.type = type;
        return this;
    }

    public void unsetType()
    {
        this.type = null;
    }

    /** Returns true if field type is set (has been assigned a value) and false otherwise */
    public boolean isSetType()
    {
        return this.type != null;
    }

    public void setTypeIsSet(boolean value)
    {
        if (!value) {
            this.type = null;
        }
    }

    public long getVersion()
    {
        return this.version;
    }

    public ThriftOutputBuffers setVersion(long version)
    {
        this.version = version;
        setVersionIsSet(true);
        return this;
    }

    public void unsetVersion()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERSION_ISSET_ID);
    }

    /** Returns true if field version is set (has been assigned a value) and false otherwise */
    public boolean isSetVersion()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERSION_ISSET_ID);
    }

    public void setVersionIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERSION_ISSET_ID, value);
    }

    public boolean isNoMoreBufferIds()
    {
        return this.noMoreBufferIds;
    }

    public ThriftOutputBuffers setNoMoreBufferIds(boolean noMoreBufferIds)
    {
        this.noMoreBufferIds = noMoreBufferIds;
        setNoMoreBufferIdsIsSet(true);
        return this;
    }

    public void unsetNoMoreBufferIds()
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NOMOREBUFFERIDS_ISSET_ID);
    }

    /** Returns true if field noMoreBufferIds is set (has been assigned a value) and false otherwise */
    public boolean isSetNoMoreBufferIds()
    {
        return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NOMOREBUFFERIDS_ISSET_ID);
    }

    public void setNoMoreBufferIdsIsSet(boolean value)
    {
        __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NOMOREBUFFERIDS_ISSET_ID, value);
    }

    public int getBuffersSize()
    {
        return (this.buffers == null) ? 0 : this.buffers.size();
    }

    public void putToBuffers(int key, int val)
    {
        if (this.buffers == null) {
            this.buffers = new java.util.HashMap<Integer, Integer>();
        }
        this.buffers.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<Integer, Integer> getBuffers()
    {
        return this.buffers;
    }

    public ThriftOutputBuffers setBuffers(@org.apache.thrift.annotation.Nullable java.util.Map<Integer, Integer> buffers)
    {
        this.buffers = buffers;
        return this;
    }

    public void unsetBuffers()
    {
        this.buffers = null;
    }

    /** Returns true if field buffers is set (has been assigned a value) and false otherwise */
    public boolean isSetBuffers()
    {
        return this.buffers != null;
    }

    public void setBuffersIsSet(boolean value)
    {
        if (!value) {
            this.buffers = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value)
    {
        switch (field) {
            case TYPE:
                if (value == null) {
                    unsetType();
                }
                else {
                    setType((ThriftBufferType) value);
                }
                break;

            case VERSION:
                if (value == null) {
                    unsetVersion();
                }
                else {
                    setVersion((Long) value);
                }
                break;

            case NO_MORE_BUFFER_IDS:
                if (value == null) {
                    unsetNoMoreBufferIds();
                }
                else {
                    setNoMoreBufferIds((Boolean) value);
                }
                break;

            case BUFFERS:
                if (value == null) {
                    unsetBuffers();
                }
                else {
                    setBuffers((java.util.Map<Integer, Integer>) value);
                }
                break;
        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public Object getFieldValue(_Fields field)
    {
        switch (field) {
            case TYPE:
                return getType();

            case VERSION:
                return getVersion();

            case NO_MORE_BUFFER_IDS:
                return isNoMoreBufferIds();

            case BUFFERS:
                return getBuffers();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field)
    {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case TYPE:
                return isSetType();
            case VERSION:
                return isSetVersion();
            case NO_MORE_BUFFER_IDS:
                return isSetNoMoreBufferIds();
            case BUFFERS:
                return isSetBuffers();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that)
    {
      if (that instanceof ThriftOutputBuffers) {
        return this.equals((ThriftOutputBuffers) that);
      }
        return false;
    }

    public boolean equals(ThriftOutputBuffers that)
    {
      if (that == null) {
        return false;
      }
      if (this == that) {
        return true;
      }

        boolean this_present_type = true && this.isSetType();
        boolean that_present_type = true && that.isSetType();
        if (this_present_type || that_present_type) {
          if (!(this_present_type && that_present_type)) {
            return false;
          }
          if (!this.type.equals(that.type)) {
            return false;
          }
        }

        boolean this_present_version = true;
        boolean that_present_version = true;
        if (this_present_version || that_present_version) {
          if (!(this_present_version && that_present_version)) {
            return false;
          }
          if (this.version != that.version) {
            return false;
          }
        }

        boolean this_present_noMoreBufferIds = true;
        boolean that_present_noMoreBufferIds = true;
        if (this_present_noMoreBufferIds || that_present_noMoreBufferIds) {
          if (!(this_present_noMoreBufferIds && that_present_noMoreBufferIds)) {
            return false;
          }
          if (this.noMoreBufferIds != that.noMoreBufferIds) {
            return false;
          }
        }

        boolean this_present_buffers = true && this.isSetBuffers();
        boolean that_present_buffers = true && that.isSetBuffers();
        if (this_present_buffers || that_present_buffers) {
          if (!(this_present_buffers && that_present_buffers)) {
            return false;
          }
          if (!this.buffers.equals(that.buffers)) {
            return false;
          }
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
      if (isSetType()) {
        hashCode = hashCode * 8191 + type.getValue();
      }

        hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(version);

        hashCode = hashCode * 8191 + ((noMoreBufferIds) ? 131071 : 524287);

        hashCode = hashCode * 8191 + ((isSetBuffers()) ? 131071 : 524287);
      if (isSetBuffers()) {
        hashCode = hashCode * 8191 + buffers.hashCode();
      }

        return hashCode;
    }

    @Override
    public int compareTo(ThriftOutputBuffers other)
    {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.compare(isSetType(), other.isSetType());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetType()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetVersion(), other.isSetVersion());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetVersion()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetNoMoreBufferIds(), other.isSetNoMoreBufferIds());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetNoMoreBufferIds()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.noMoreBufferIds, other.noMoreBufferIds);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = Boolean.compare(isSetBuffers(), other.isSetBuffers());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetBuffers()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.buffers, other.buffers);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId)
    {
        return _Fields.findByThriftId(fieldId);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot)
            throws org.apache.thrift.TException
    {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot)
            throws org.apache.thrift.TException
    {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("ThriftOutputBuffers(");
        boolean first = true;

        sb.append("type:");
        if (this.type == null) {
            sb.append("null");
        }
        else {
            sb.append(this.type);
        }
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("version:");
        sb.append(this.version);
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("noMoreBufferIds:");
        sb.append(this.noMoreBufferIds);
        first = false;
      if (!first) {
        sb.append(", ");
      }
        sb.append("buffers:");
        if (this.buffers == null) {
            sb.append("null");
        }
        else {
            sb.append(this.buffers);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate()
            throws org.apache.thrift.TException
    {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out)
            throws java.io.IOException
    {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in)
            throws java.io.IOException, ClassNotFoundException
    {
        try {
            // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
            __isset_bitfield = 0;
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        }
        catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ThriftOutputBuffersStandardSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftOutputBuffersStandardScheme getScheme()
        {
            return new ThriftOutputBuffersStandardScheme();
        }
    }

    private static class ThriftOutputBuffersStandardScheme
            extends org.apache.thrift.scheme.StandardScheme<ThriftOutputBuffers>
    {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftOutputBuffers struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // TYPE
                        if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                            struct.type = ThriftBufferType.findByValue(iprot.readI32());
                            struct.setTypeIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // VERSION
                        if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                            struct.version = iprot.readI64();
                            struct.setVersionIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 3: // NO_MORE_BUFFER_IDS
                        if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                            struct.noMoreBufferIds = iprot.readBool();
                            struct.setNoMoreBufferIdsIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 4: // BUFFERS
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                                struct.buffers = new java.util.HashMap<Integer, Integer>(2 * _map0.size);
                                int _key1;
                                int _val2;
                                for (int _i3 = 0; _i3 < _map0.size; ++_i3) {
                                    _key1 = iprot.readI32();
                                    _val2 = iprot.readI32();
                                    struct.buffers.put(_key1, _val2);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setBuffersIsSet(true);
                        }
                        else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftOutputBuffers struct)
                throws org.apache.thrift.TException
        {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.type != null) {
                oprot.writeFieldBegin(TYPE_FIELD_DESC);
                oprot.writeI32(struct.type.getValue());
                oprot.writeFieldEnd();
            }
            oprot.writeFieldBegin(VERSION_FIELD_DESC);
            oprot.writeI64(struct.version);
            oprot.writeFieldEnd();
            oprot.writeFieldBegin(NO_MORE_BUFFER_IDS_FIELD_DESC);
            oprot.writeBool(struct.noMoreBufferIds);
            oprot.writeFieldEnd();
            if (struct.buffers != null) {
                oprot.writeFieldBegin(BUFFERS_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.I32, struct.buffers.size()));
                    for (java.util.Map.Entry<Integer, Integer> _iter4 : struct.buffers.entrySet()) {
                        oprot.writeI32(_iter4.getKey());
                        oprot.writeI32(_iter4.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class ThriftOutputBuffersTupleSchemeFactory
            implements org.apache.thrift.scheme.SchemeFactory
    {
        @Override
        public ThriftOutputBuffersTupleScheme getScheme()
        {
            return new ThriftOutputBuffersTupleScheme();
        }
    }

    private static class ThriftOutputBuffersTupleScheme
            extends org.apache.thrift.scheme.TupleScheme<ThriftOutputBuffers>
    {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ThriftOutputBuffers struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetType()) {
                optionals.set(0);
            }
            if (struct.isSetVersion()) {
                optionals.set(1);
            }
            if (struct.isSetNoMoreBufferIds()) {
                optionals.set(2);
            }
            if (struct.isSetBuffers()) {
                optionals.set(3);
            }
            oprot.writeBitSet(optionals, 4);
            if (struct.isSetType()) {
                oprot.writeI32(struct.type.getValue());
            }
            if (struct.isSetVersion()) {
                oprot.writeI64(struct.version);
            }
            if (struct.isSetNoMoreBufferIds()) {
                oprot.writeBool(struct.noMoreBufferIds);
            }
            if (struct.isSetBuffers()) {
                {
                    oprot.writeI32(struct.buffers.size());
                    for (java.util.Map.Entry<Integer, Integer> _iter5 : struct.buffers.entrySet()) {
                        oprot.writeI32(_iter5.getKey());
                        oprot.writeI32(_iter5.getValue());
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ThriftOutputBuffers struct)
                throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(4);
            if (incoming.get(0)) {
                struct.type = ThriftBufferType.findByValue(iprot.readI32());
                struct.setTypeIsSet(true);
            }
            if (incoming.get(1)) {
                struct.version = iprot.readI64();
                struct.setVersionIsSet(true);
            }
            if (incoming.get(2)) {
                struct.noMoreBufferIds = iprot.readBool();
                struct.setNoMoreBufferIdsIsSet(true);
            }
            if (incoming.get(3)) {
                {
                    org.apache.thrift.protocol.TMap _map6 = iprot.readMapBegin(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.I32);
                    struct.buffers = new java.util.HashMap<Integer, Integer>(2 * _map6.size);
                    int _key7;
                    int _val8;
                    for (int _i9 = 0; _i9 < _map6.size; ++_i9) {
                        _key7 = iprot.readI32();
                        _val8 = iprot.readI32();
                        struct.buffers.put(_key7, _val8);
                    }
                }
                struct.setBuffersIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto)
    {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

