/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace test {


TestMessage::~TestMessage() noexcept {
}

TestMessage::TestMessage() noexcept
   : text(),
     number(0) {
}

void TestMessage::__set_text(const std::string& val) {
  this->text = val;
}

void TestMessage::__set_number(const int32_t val) {
  this->number = val;
}

void TestMessage::__set_items(const std::vector<std::string> & val) {
  this->items = val;
}
std::ostream& operator<<(std::ostream& out, const TestMessage& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t TestMessage::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->text);
          this->__isset.text = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->number);
          this->__isset.number = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->items.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->items.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->items[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.items = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TestMessage::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("TestMessage");

  xfer += oprot->writeFieldBegin("text", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->text);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("number", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->number);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("items", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->items.size()));
    std::vector<std::string> ::const_iterator _iter5;
    for (_iter5 = this->items.begin(); _iter5 != this->items.end(); ++_iter5)
    {
      xfer += oprot->writeString((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(TestMessage &a, TestMessage &b) {
  using ::std::swap;
  swap(a.text, b.text);
  swap(a.number, b.number);
  swap(a.items, b.items);
  swap(a.__isset, b.__isset);
}

bool TestMessage::operator==(const TestMessage & rhs) const
{
  if (!(text == rhs.text))
    return false;
  if (!(number == rhs.number))
    return false;
  if (!(items == rhs.items))
    return false;
  return true;
}

TestMessage::TestMessage(const TestMessage& other6) {
  text = other6.text;
  number = other6.number;
  items = other6.items;
  __isset = other6.__isset;
}
TestMessage& TestMessage::operator=(const TestMessage& other7) {
  text = other7.text;
  number = other7.number;
  items = other7.items;
  __isset = other7.__isset;
  return *this;
}
void TestMessage::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "TestMessage(";
  out << "text=" << to_string(text);
  out << ", " << "number=" << to_string(number);
  out << ", " << "items=" << to_string(items);
  out << ")";
}

} // namespace
