namespace java com.facebook.presto.common.experimental
namespace cpp protocol

typedef string ThriftConnectorTableHandle
typedef string ThriftConnectorTransactionHandle
typedef string ThriftExecutionWriterTarget
typedef string ThriftSplitContext
typedef string ThriftConnectorSplit
typedef string ThriftConnectorTableLayoutHandle