/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftDataType_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace protocol {

int _kThriftTaskStateValues[] = {
  ThriftTaskState::PLANNED,
  ThriftTaskState::RUNNING,
  ThriftTaskState::FINISHED,
  ThriftTaskState::CANCELED,
  ThriftTaskState::ABORTED,
  ThriftTaskState::FAILED
};
const char* _kThriftTaskStateNames[] = {
  "PLANNED",
  "RUNNING",
  "FINISHED",
  "CANCELED",
  "ABORTED",
  "FAILED"
};
const std::map<int, const char*> _ThriftTaskState_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(6, _kThriftTaskStateValues, _kThriftTaskStateNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftTaskState::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftTaskState_VALUES_TO_NAMES.find(val);
  if (it != _ThriftTaskState_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftTaskState::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftTaskState_VALUES_TO_NAMES.find(val);
  if (it != _ThriftTaskState_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kThriftErrorCauseValues[] = {
  ThriftErrorCause::UNKNOWN,
  ThriftErrorCause::LOW_PARTITION_COUNT,
  ThriftErrorCause::EXCEEDS_BROADCAST_MEMORY_LIMIT
};
const char* _kThriftErrorCauseNames[] = {
  "UNKNOWN",
  "LOW_PARTITION_COUNT",
  "EXCEEDS_BROADCAST_MEMORY_LIMIT"
};
const std::map<int, const char*> _ThriftErrorCause_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kThriftErrorCauseValues, _kThriftErrorCauseNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftErrorCause::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorCause_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorCause_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftErrorCause::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorCause_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorCause_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kThriftErrorTypeValues[] = {
  ThriftErrorType::USER_ERROR,
  ThriftErrorType::INTERNAL_ERROR,
  ThriftErrorType::INSUFFICIENT_RESOURCES,
  ThriftErrorType::EXTERNAL
};
const char* _kThriftErrorTypeNames[] = {
  "USER_ERROR",
  "INTERNAL_ERROR",
  "INSUFFICIENT_RESOURCES",
  "EXTERNAL"
};
const std::map<int, const char*> _ThriftErrorType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kThriftErrorTypeValues, _kThriftErrorTypeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ThriftErrorType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ThriftErrorType::type& val) {
  std::map<int, const char*>::const_iterator it = _ThriftErrorType_VALUES_TO_NAMES.find(val);
  if (it != _ThriftErrorType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ThriftLifespan::~ThriftLifespan() noexcept {
}

ThriftLifespan::ThriftLifespan() noexcept
   : grouped(0),
     groupId(0) {
}

void ThriftLifespan::__set_grouped(const bool val) {
  this->grouped = val;
}

void ThriftLifespan::__set_groupId(const int32_t val) {
  this->groupId = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftLifespan& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftLifespan::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->grouped);
          this->__isset.grouped = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->groupId);
          this->__isset.groupId = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftLifespan::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftLifespan");

  xfer += oprot->writeFieldBegin("grouped", ::apache::thrift::protocol::T_BOOL, 1);
  xfer += oprot->writeBool(this->grouped);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("groupId", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->groupId);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftLifespan &a, ThriftLifespan &b) {
  using ::std::swap;
  swap(a.grouped, b.grouped);
  swap(a.groupId, b.groupId);
  swap(a.__isset, b.__isset);
}

bool ThriftLifespan::operator==(const ThriftLifespan & rhs) const
{
  if (!(grouped == rhs.grouped))
    return false;
  if (!(groupId == rhs.groupId))
    return false;
  return true;
}

ThriftLifespan::ThriftLifespan(const ThriftLifespan& other0) noexcept {
  grouped = other0.grouped;
  groupId = other0.groupId;
  __isset = other0.__isset;
}
ThriftLifespan& ThriftLifespan::operator=(const ThriftLifespan& other1) noexcept {
  grouped = other1.grouped;
  groupId = other1.groupId;
  __isset = other1.__isset;
  return *this;
}
void ThriftLifespan::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftLifespan(";
  out << "grouped=" << to_string(grouped);
  out << ", " << "groupId=" << to_string(groupId);
  out << ")";
}


ThriftErrorCode::~ThriftErrorCode() noexcept {
}

ThriftErrorCode::ThriftErrorCode() noexcept
   : code(0),
     name(),
     type(static_cast<ThriftErrorType::type>(0)),
     retriable(0) {
}

void ThriftErrorCode::__set_code(const int32_t val) {
  this->code = val;
}

void ThriftErrorCode::__set_name(const std::string& val) {
  this->name = val;
}

void ThriftErrorCode::__set_type(const ThriftErrorType::type val) {
  this->type = val;
}

void ThriftErrorCode::__set_retriable(const bool val) {
  this->retriable = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftErrorCode& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftErrorCode::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->code);
          this->__isset.code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->type = static_cast<ThriftErrorType::type>(ecast2);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->retriable);
          this->__isset.retriable = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftErrorCode::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftErrorCode");

  xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(static_cast<int32_t>(this->type));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("retriable", ::apache::thrift::protocol::T_BOOL, 4);
  xfer += oprot->writeBool(this->retriable);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftErrorCode &a, ThriftErrorCode &b) {
  using ::std::swap;
  swap(a.code, b.code);
  swap(a.name, b.name);
  swap(a.type, b.type);
  swap(a.retriable, b.retriable);
  swap(a.__isset, b.__isset);
}

bool ThriftErrorCode::operator==(const ThriftErrorCode & rhs) const
{
  if (!(code == rhs.code))
    return false;
  if (!(name == rhs.name))
    return false;
  if (!(type == rhs.type))
    return false;
  if (!(retriable == rhs.retriable))
    return false;
  return true;
}

ThriftErrorCode::ThriftErrorCode(const ThriftErrorCode& other3) {
  code = other3.code;
  name = other3.name;
  type = other3.type;
  retriable = other3.retriable;
  __isset = other3.__isset;
}
ThriftErrorCode& ThriftErrorCode::operator=(const ThriftErrorCode& other4) {
  code = other4.code;
  name = other4.name;
  type = other4.type;
  retriable = other4.retriable;
  __isset = other4.__isset;
  return *this;
}
void ThriftErrorCode::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftErrorCode(";
  out << "code=" << to_string(code);
  out << ", " << "name=" << to_string(name);
  out << ", " << "type=" << to_string(type);
  out << ", " << "retriable=" << to_string(retriable);
  out << ")";
}


ThriftErrorLocation::~ThriftErrorLocation() noexcept {
}

ThriftErrorLocation::ThriftErrorLocation() noexcept
   : lineNumber(0),
     columnNumber(0) {
}

void ThriftErrorLocation::__set_lineNumber(const int32_t val) {
  this->lineNumber = val;
}

void ThriftErrorLocation::__set_columnNumber(const int32_t val) {
  this->columnNumber = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftErrorLocation& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftErrorLocation::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->lineNumber);
          this->__isset.lineNumber = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->columnNumber);
          this->__isset.columnNumber = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftErrorLocation::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftErrorLocation");

  xfer += oprot->writeFieldBegin("lineNumber", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->lineNumber);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("columnNumber", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->columnNumber);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftErrorLocation &a, ThriftErrorLocation &b) {
  using ::std::swap;
  swap(a.lineNumber, b.lineNumber);
  swap(a.columnNumber, b.columnNumber);
  swap(a.__isset, b.__isset);
}

bool ThriftErrorLocation::operator==(const ThriftErrorLocation & rhs) const
{
  if (!(lineNumber == rhs.lineNumber))
    return false;
  if (!(columnNumber == rhs.columnNumber))
    return false;
  return true;
}

ThriftErrorLocation::ThriftErrorLocation(const ThriftErrorLocation& other5) noexcept {
  lineNumber = other5.lineNumber;
  columnNumber = other5.columnNumber;
  __isset = other5.__isset;
}
ThriftErrorLocation& ThriftErrorLocation::operator=(const ThriftErrorLocation& other6) noexcept {
  lineNumber = other6.lineNumber;
  columnNumber = other6.columnNumber;
  __isset = other6.__isset;
  return *this;
}
void ThriftErrorLocation::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftErrorLocation(";
  out << "lineNumber=" << to_string(lineNumber);
  out << ", " << "columnNumber=" << to_string(columnNumber);
  out << ")";
}


ThriftHostAddress::~ThriftHostAddress() noexcept {
}

ThriftHostAddress::ThriftHostAddress() noexcept
   : host(),
     port(0) {
}

void ThriftHostAddress::__set_host(const std::string& val) {
  this->host = val;
}

void ThriftHostAddress::__set_port(const int32_t val) {
  this->port = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftHostAddress& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftHostAddress::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->host);
          this->__isset.host = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftHostAddress::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftHostAddress");

  xfer += oprot->writeFieldBegin("host", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->host);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftHostAddress &a, ThriftHostAddress &b) {
  using ::std::swap;
  swap(a.host, b.host);
  swap(a.port, b.port);
  swap(a.__isset, b.__isset);
}

bool ThriftHostAddress::operator==(const ThriftHostAddress & rhs) const
{
  if (!(host == rhs.host))
    return false;
  if (!(port == rhs.port))
    return false;
  return true;
}

ThriftHostAddress::ThriftHostAddress(const ThriftHostAddress& other7) {
  host = other7.host;
  port = other7.port;
  __isset = other7.__isset;
}
ThriftHostAddress& ThriftHostAddress::operator=(const ThriftHostAddress& other8) {
  host = other8.host;
  port = other8.port;
  __isset = other8.__isset;
  return *this;
}
void ThriftHostAddress::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftHostAddress(";
  out << "host=" << to_string(host);
  out << ", " << "port=" << to_string(port);
  out << ")";
}


ThriftExecutionFailureInfo::~ThriftExecutionFailureInfo() noexcept {
}

ThriftExecutionFailureInfo::ThriftExecutionFailureInfo() noexcept
   : type(),
     message(),
     errorCause(static_cast<ThriftErrorCause::type>(0)) {
}

void ThriftExecutionFailureInfo::__set_type(const std::string& val) {
  this->type = val;
}

void ThriftExecutionFailureInfo::__set_message(const std::string& val) {
  this->message = val;
}

void ThriftExecutionFailureInfo::__set_cause(const ThriftExecutionFailureInfo& val) {
  this->cause = val;
__isset.cause = true;
}

void ThriftExecutionFailureInfo::__set_suppressed(const std::vector<ThriftExecutionFailureInfo> & val) {
  this->suppressed = val;
}

void ThriftExecutionFailureInfo::__set_stack(const std::vector<std::string> & val) {
  this->stack = val;
}

void ThriftExecutionFailureInfo::__set_errorLocation(const ThriftErrorLocation& val) {
  this->errorLocation = val;
}

void ThriftExecutionFailureInfo::__set_errorCode(const ThriftErrorCode& val) {
  this->errorCode = val;
}

void ThriftExecutionFailureInfo::__set_remoteHost(const ThriftHostAddress& val) {
  this->remoteHost = val;
}

void ThriftExecutionFailureInfo::__set_errorCause(const ThriftErrorCause::type val) {
  this->errorCause = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftExecutionFailureInfo& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftExecutionFailureInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->type);
          this->__isset.type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          this->__isset.message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->cause.read(iprot);
          this->__isset.cause = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->suppressed.clear();
            uint32_t _size9;
            ::apache::thrift::protocol::TType _etype12;
            xfer += iprot->readListBegin(_etype12, _size9);
            this->suppressed.resize(_size9);
            uint32_t _i13;
            for (_i13 = 0; _i13 < _size9; ++_i13)
            {
              xfer += this->suppressed[_i13].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.suppressed = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->stack.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _etype17;
            xfer += iprot->readListBegin(_etype17, _size14);
            this->stack.resize(_size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              xfer += iprot->readString(this->stack[_i18]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.stack = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->errorLocation.read(iprot);
          this->__isset.errorLocation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->errorCode.read(iprot);
          this->__isset.errorCode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->remoteHost.read(iprot);
          this->__isset.remoteHost = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast19;
          xfer += iprot->readI32(ecast19);
          this->errorCause = static_cast<ThriftErrorCause::type>(ecast19);
          this->__isset.errorCause = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftExecutionFailureInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftExecutionFailureInfo");

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->type);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("message", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.cause) {
    xfer += oprot->writeFieldBegin("cause", ::apache::thrift::protocol::T_STRUCT, 3);
    xfer += this->cause.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("suppressed", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->suppressed.size()));
    std::vector<ThriftExecutionFailureInfo> ::const_iterator _iter20;
    for (_iter20 = this->suppressed.begin(); _iter20 != this->suppressed.end(); ++_iter20)
    {
      xfer += (*_iter20).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("stack", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->stack.size()));
    std::vector<std::string> ::const_iterator _iter21;
    for (_iter21 = this->stack.begin(); _iter21 != this->stack.end(); ++_iter21)
    {
      xfer += oprot->writeString((*_iter21));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("errorLocation", ::apache::thrift::protocol::T_STRUCT, 6);
  xfer += this->errorLocation.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("errorCode", ::apache::thrift::protocol::T_STRUCT, 7);
  xfer += this->errorCode.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("remoteHost", ::apache::thrift::protocol::T_STRUCT, 8);
  xfer += this->remoteHost.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("errorCause", ::apache::thrift::protocol::T_I32, 9);
  xfer += oprot->writeI32(static_cast<int32_t>(this->errorCause));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftExecutionFailureInfo &a, ThriftExecutionFailureInfo &b) {
  using ::std::swap;
  swap(a.type, b.type);
  swap(a.message, b.message);
  swap(a.cause, b.cause);
  swap(a.suppressed, b.suppressed);
  swap(a.stack, b.stack);
  swap(a.errorLocation, b.errorLocation);
  swap(a.errorCode, b.errorCode);
  swap(a.remoteHost, b.remoteHost);
  swap(a.errorCause, b.errorCause);
  swap(a.__isset, b.__isset);
}

bool ThriftExecutionFailureInfo::operator==(const ThriftExecutionFailureInfo & rhs) const
{
  if (!(type == rhs.type))
    return false;
  if (!(message == rhs.message))
    return false;
  if (__isset.cause != rhs.__isset.cause)
    return false;
  else if (__isset.cause && !(cause == rhs.cause))
    return false;
  if (!(suppressed == rhs.suppressed))
    return false;
  if (!(stack == rhs.stack))
    return false;
  if (!(errorLocation == rhs.errorLocation))
    return false;
  if (!(errorCode == rhs.errorCode))
    return false;
  if (!(remoteHost == rhs.remoteHost))
    return false;
  if (!(errorCause == rhs.errorCause))
    return false;
  return true;
}

ThriftExecutionFailureInfo::ThriftExecutionFailureInfo(const ThriftExecutionFailureInfo& other22) {
  type = other22.type;
  message = other22.message;
  cause = other22.cause;
  suppressed = other22.suppressed;
  stack = other22.stack;
  errorLocation = other22.errorLocation;
  errorCode = other22.errorCode;
  remoteHost = other22.remoteHost;
  errorCause = other22.errorCause;
  __isset = other22.__isset;
}
ThriftExecutionFailureInfo& ThriftExecutionFailureInfo::operator=(const ThriftExecutionFailureInfo& other23) {
  type = other23.type;
  message = other23.message;
  cause = other23.cause;
  suppressed = other23.suppressed;
  stack = other23.stack;
  errorLocation = other23.errorLocation;
  errorCode = other23.errorCode;
  remoteHost = other23.remoteHost;
  errorCause = other23.errorCause;
  __isset = other23.__isset;
  return *this;
}
void ThriftExecutionFailureInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftExecutionFailureInfo(";
  out << "type=" << to_string(type);
  out << ", " << "message=" << to_string(message);
  out << ", " << "cause="; (__isset.cause ? (out << to_string(cause)) : (out << "<null>"));
  out << ", " << "suppressed=" << to_string(suppressed);
  out << ", " << "stack=" << to_string(stack);
  out << ", " << "errorLocation=" << to_string(errorLocation);
  out << ", " << "errorCode=" << to_string(errorCode);
  out << ", " << "remoteHost=" << to_string(remoteHost);
  out << ", " << "errorCause=" << to_string(errorCause);
  out << ")";
}


ThriftTaskStatus::~ThriftTaskStatus() noexcept {
}

ThriftTaskStatus::ThriftTaskStatus() noexcept
   : taskInstanceIdLeastSignificantBits(0),
     taskInstanceIdMostSignificantBits(0),
     version(0),
     state(static_cast<ThriftTaskState::type>(0)),
     self(),
     queuedPartitionedDrivers(0),
     runningPartitionedDrivers(0),
     outputBufferUtilization(0),
     outputBufferOverutilized(0),
     physicalWrittenDataSizeInBytes(0),
     memoryReservationInBytes(0),
     systemMemoryReservationInBytes(0),
     peakNodeTotalMemoryReservationInBytes(0),
     fullGcCount(0),
     fullGcTimeInMillis(0),
     totalCpuTimeInNanos(0),
     taskAgeInMillis(0),
     queuedPartitionedSplitsWeight(0),
     runningPartitionedSplitsWeight(0) {
}

void ThriftTaskStatus::__set_taskInstanceIdLeastSignificantBits(const int64_t val) {
  this->taskInstanceIdLeastSignificantBits = val;
}

void ThriftTaskStatus::__set_taskInstanceIdMostSignificantBits(const int64_t val) {
  this->taskInstanceIdMostSignificantBits = val;
}

void ThriftTaskStatus::__set_version(const int64_t val) {
  this->version = val;
}

void ThriftTaskStatus::__set_state(const ThriftTaskState::type val) {
  this->state = val;
}

void ThriftTaskStatus::__set_self(const std::string& val) {
  this->self = val;
}

void ThriftTaskStatus::__set_completedDriverGroups(const std::set<ThriftLifespan> & val) {
  this->completedDriverGroups = val;
}

void ThriftTaskStatus::__set_failures(const std::vector<ThriftExecutionFailureInfo> & val) {
  this->failures = val;
}

void ThriftTaskStatus::__set_queuedPartitionedDrivers(const int32_t val) {
  this->queuedPartitionedDrivers = val;
}

void ThriftTaskStatus::__set_runningPartitionedDrivers(const int32_t val) {
  this->runningPartitionedDrivers = val;
}

void ThriftTaskStatus::__set_outputBufferUtilization(const double val) {
  this->outputBufferUtilization = val;
}

void ThriftTaskStatus::__set_outputBufferOverutilized(const bool val) {
  this->outputBufferOverutilized = val;
}

void ThriftTaskStatus::__set_physicalWrittenDataSizeInBytes(const int64_t val) {
  this->physicalWrittenDataSizeInBytes = val;
}

void ThriftTaskStatus::__set_memoryReservationInBytes(const int64_t val) {
  this->memoryReservationInBytes = val;
}

void ThriftTaskStatus::__set_systemMemoryReservationInBytes(const int64_t val) {
  this->systemMemoryReservationInBytes = val;
}

void ThriftTaskStatus::__set_peakNodeTotalMemoryReservationInBytes(const int64_t val) {
  this->peakNodeTotalMemoryReservationInBytes = val;
}

void ThriftTaskStatus::__set_fullGcCount(const int64_t val) {
  this->fullGcCount = val;
}

void ThriftTaskStatus::__set_fullGcTimeInMillis(const int64_t val) {
  this->fullGcTimeInMillis = val;
}

void ThriftTaskStatus::__set_totalCpuTimeInNanos(const int64_t val) {
  this->totalCpuTimeInNanos = val;
}

void ThriftTaskStatus::__set_taskAgeInMillis(const int64_t val) {
  this->taskAgeInMillis = val;
}

void ThriftTaskStatus::__set_queuedPartitionedSplitsWeight(const int64_t val) {
  this->queuedPartitionedSplitsWeight = val;
}

void ThriftTaskStatus::__set_runningPartitionedSplitsWeight(const int64_t val) {
  this->runningPartitionedSplitsWeight = val;
}
std::ostream& operator<<(std::ostream& out, const ThriftTaskStatus& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ThriftTaskStatus::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->taskInstanceIdLeastSignificantBits);
          this->__isset.taskInstanceIdLeastSignificantBits = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->taskInstanceIdMostSignificantBits);
          this->__isset.taskInstanceIdMostSignificantBits = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->version);
          this->__isset.version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast24;
          xfer += iprot->readI32(ecast24);
          this->state = static_cast<ThriftTaskState::type>(ecast24);
          this->__isset.state = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->self);
          this->__isset.self = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_SET) {
          {
            this->completedDriverGroups.clear();
            uint32_t _size25;
            ::apache::thrift::protocol::TType _etype28;
            xfer += iprot->readSetBegin(_etype28, _size25);
            uint32_t _i29;
            for (_i29 = 0; _i29 < _size25; ++_i29)
            {
              ThriftLifespan _elem30;
              xfer += _elem30.read(iprot);
              this->completedDriverGroups.insert(_elem30);
            }
            xfer += iprot->readSetEnd();
          }
          this->__isset.completedDriverGroups = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->failures.clear();
            uint32_t _size31;
            ::apache::thrift::protocol::TType _etype34;
            xfer += iprot->readListBegin(_etype34, _size31);
            this->failures.resize(_size31);
            uint32_t _i35;
            for (_i35 = 0; _i35 < _size31; ++_i35)
            {
              xfer += this->failures[_i35].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.failures = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->queuedPartitionedDrivers);
          this->__isset.queuedPartitionedDrivers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->runningPartitionedDrivers);
          this->__isset.runningPartitionedDrivers = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->outputBufferUtilization);
          this->__isset.outputBufferUtilization = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->outputBufferOverutilized);
          this->__isset.outputBufferOverutilized = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->physicalWrittenDataSizeInBytes);
          this->__isset.physicalWrittenDataSizeInBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->memoryReservationInBytes);
          this->__isset.memoryReservationInBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->systemMemoryReservationInBytes);
          this->__isset.systemMemoryReservationInBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->peakNodeTotalMemoryReservationInBytes);
          this->__isset.peakNodeTotalMemoryReservationInBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->fullGcCount);
          this->__isset.fullGcCount = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 17:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->fullGcTimeInMillis);
          this->__isset.fullGcTimeInMillis = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 18:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->totalCpuTimeInNanos);
          this->__isset.totalCpuTimeInNanos = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 19:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->taskAgeInMillis);
          this->__isset.taskAgeInMillis = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 20:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->queuedPartitionedSplitsWeight);
          this->__isset.queuedPartitionedSplitsWeight = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 21:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->runningPartitionedSplitsWeight);
          this->__isset.runningPartitionedSplitsWeight = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ThriftTaskStatus::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ThriftTaskStatus");

  xfer += oprot->writeFieldBegin("taskInstanceIdLeastSignificantBits", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->taskInstanceIdLeastSignificantBits);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("taskInstanceIdMostSignificantBits", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->taskInstanceIdMostSignificantBits);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("version", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->version);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("state", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(static_cast<int32_t>(this->state));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("self", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->self);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("completedDriverGroups", ::apache::thrift::protocol::T_SET, 6);
  {
    xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->completedDriverGroups.size()));
    std::set<ThriftLifespan> ::const_iterator _iter36;
    for (_iter36 = this->completedDriverGroups.begin(); _iter36 != this->completedDriverGroups.end(); ++_iter36)
    {
      xfer += (*_iter36).write(oprot);
    }
    xfer += oprot->writeSetEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("failures", ::apache::thrift::protocol::T_LIST, 7);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->failures.size()));
    std::vector<ThriftExecutionFailureInfo> ::const_iterator _iter37;
    for (_iter37 = this->failures.begin(); _iter37 != this->failures.end(); ++_iter37)
    {
      xfer += (*_iter37).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("queuedPartitionedDrivers", ::apache::thrift::protocol::T_I32, 8);
  xfer += oprot->writeI32(this->queuedPartitionedDrivers);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("runningPartitionedDrivers", ::apache::thrift::protocol::T_I32, 9);
  xfer += oprot->writeI32(this->runningPartitionedDrivers);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("outputBufferUtilization", ::apache::thrift::protocol::T_DOUBLE, 10);
  xfer += oprot->writeDouble(this->outputBufferUtilization);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("outputBufferOverutilized", ::apache::thrift::protocol::T_BOOL, 11);
  xfer += oprot->writeBool(this->outputBufferOverutilized);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("physicalWrittenDataSizeInBytes", ::apache::thrift::protocol::T_I64, 12);
  xfer += oprot->writeI64(this->physicalWrittenDataSizeInBytes);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("memoryReservationInBytes", ::apache::thrift::protocol::T_I64, 13);
  xfer += oprot->writeI64(this->memoryReservationInBytes);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("systemMemoryReservationInBytes", ::apache::thrift::protocol::T_I64, 14);
  xfer += oprot->writeI64(this->systemMemoryReservationInBytes);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("peakNodeTotalMemoryReservationInBytes", ::apache::thrift::protocol::T_I64, 15);
  xfer += oprot->writeI64(this->peakNodeTotalMemoryReservationInBytes);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("fullGcCount", ::apache::thrift::protocol::T_I64, 16);
  xfer += oprot->writeI64(this->fullGcCount);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("fullGcTimeInMillis", ::apache::thrift::protocol::T_I64, 17);
  xfer += oprot->writeI64(this->fullGcTimeInMillis);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("totalCpuTimeInNanos", ::apache::thrift::protocol::T_I64, 18);
  xfer += oprot->writeI64(this->totalCpuTimeInNanos);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("taskAgeInMillis", ::apache::thrift::protocol::T_I64, 19);
  xfer += oprot->writeI64(this->taskAgeInMillis);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("queuedPartitionedSplitsWeight", ::apache::thrift::protocol::T_I64, 20);
  xfer += oprot->writeI64(this->queuedPartitionedSplitsWeight);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("runningPartitionedSplitsWeight", ::apache::thrift::protocol::T_I64, 21);
  xfer += oprot->writeI64(this->runningPartitionedSplitsWeight);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ThriftTaskStatus &a, ThriftTaskStatus &b) {
  using ::std::swap;
  swap(a.taskInstanceIdLeastSignificantBits, b.taskInstanceIdLeastSignificantBits);
  swap(a.taskInstanceIdMostSignificantBits, b.taskInstanceIdMostSignificantBits);
  swap(a.version, b.version);
  swap(a.state, b.state);
  swap(a.self, b.self);
  swap(a.completedDriverGroups, b.completedDriverGroups);
  swap(a.failures, b.failures);
  swap(a.queuedPartitionedDrivers, b.queuedPartitionedDrivers);
  swap(a.runningPartitionedDrivers, b.runningPartitionedDrivers);
  swap(a.outputBufferUtilization, b.outputBufferUtilization);
  swap(a.outputBufferOverutilized, b.outputBufferOverutilized);
  swap(a.physicalWrittenDataSizeInBytes, b.physicalWrittenDataSizeInBytes);
  swap(a.memoryReservationInBytes, b.memoryReservationInBytes);
  swap(a.systemMemoryReservationInBytes, b.systemMemoryReservationInBytes);
  swap(a.peakNodeTotalMemoryReservationInBytes, b.peakNodeTotalMemoryReservationInBytes);
  swap(a.fullGcCount, b.fullGcCount);
  swap(a.fullGcTimeInMillis, b.fullGcTimeInMillis);
  swap(a.totalCpuTimeInNanos, b.totalCpuTimeInNanos);
  swap(a.taskAgeInMillis, b.taskAgeInMillis);
  swap(a.queuedPartitionedSplitsWeight, b.queuedPartitionedSplitsWeight);
  swap(a.runningPartitionedSplitsWeight, b.runningPartitionedSplitsWeight);
  swap(a.__isset, b.__isset);
}

bool ThriftTaskStatus::operator==(const ThriftTaskStatus & rhs) const
{
  if (!(taskInstanceIdLeastSignificantBits == rhs.taskInstanceIdLeastSignificantBits))
    return false;
  if (!(taskInstanceIdMostSignificantBits == rhs.taskInstanceIdMostSignificantBits))
    return false;
  if (!(version == rhs.version))
    return false;
  if (!(state == rhs.state))
    return false;
  if (!(self == rhs.self))
    return false;
  if (!(completedDriverGroups == rhs.completedDriverGroups))
    return false;
  if (!(failures == rhs.failures))
    return false;
  if (!(queuedPartitionedDrivers == rhs.queuedPartitionedDrivers))
    return false;
  if (!(runningPartitionedDrivers == rhs.runningPartitionedDrivers))
    return false;
  if (!(outputBufferUtilization == rhs.outputBufferUtilization))
    return false;
  if (!(outputBufferOverutilized == rhs.outputBufferOverutilized))
    return false;
  if (!(physicalWrittenDataSizeInBytes == rhs.physicalWrittenDataSizeInBytes))
    return false;
  if (!(memoryReservationInBytes == rhs.memoryReservationInBytes))
    return false;
  if (!(systemMemoryReservationInBytes == rhs.systemMemoryReservationInBytes))
    return false;
  if (!(peakNodeTotalMemoryReservationInBytes == rhs.peakNodeTotalMemoryReservationInBytes))
    return false;
  if (!(fullGcCount == rhs.fullGcCount))
    return false;
  if (!(fullGcTimeInMillis == rhs.fullGcTimeInMillis))
    return false;
  if (!(totalCpuTimeInNanos == rhs.totalCpuTimeInNanos))
    return false;
  if (!(taskAgeInMillis == rhs.taskAgeInMillis))
    return false;
  if (!(queuedPartitionedSplitsWeight == rhs.queuedPartitionedSplitsWeight))
    return false;
  if (!(runningPartitionedSplitsWeight == rhs.runningPartitionedSplitsWeight))
    return false;
  return true;
}

ThriftTaskStatus::ThriftTaskStatus(const ThriftTaskStatus& other38) {
  taskInstanceIdLeastSignificantBits = other38.taskInstanceIdLeastSignificantBits;
  taskInstanceIdMostSignificantBits = other38.taskInstanceIdMostSignificantBits;
  version = other38.version;
  state = other38.state;
  self = other38.self;
  completedDriverGroups = other38.completedDriverGroups;
  failures = other38.failures;
  queuedPartitionedDrivers = other38.queuedPartitionedDrivers;
  runningPartitionedDrivers = other38.runningPartitionedDrivers;
  outputBufferUtilization = other38.outputBufferUtilization;
  outputBufferOverutilized = other38.outputBufferOverutilized;
  physicalWrittenDataSizeInBytes = other38.physicalWrittenDataSizeInBytes;
  memoryReservationInBytes = other38.memoryReservationInBytes;
  systemMemoryReservationInBytes = other38.systemMemoryReservationInBytes;
  peakNodeTotalMemoryReservationInBytes = other38.peakNodeTotalMemoryReservationInBytes;
  fullGcCount = other38.fullGcCount;
  fullGcTimeInMillis = other38.fullGcTimeInMillis;
  totalCpuTimeInNanos = other38.totalCpuTimeInNanos;
  taskAgeInMillis = other38.taskAgeInMillis;
  queuedPartitionedSplitsWeight = other38.queuedPartitionedSplitsWeight;
  runningPartitionedSplitsWeight = other38.runningPartitionedSplitsWeight;
  __isset = other38.__isset;
}
ThriftTaskStatus& ThriftTaskStatus::operator=(const ThriftTaskStatus& other39) {
  taskInstanceIdLeastSignificantBits = other39.taskInstanceIdLeastSignificantBits;
  taskInstanceIdMostSignificantBits = other39.taskInstanceIdMostSignificantBits;
  version = other39.version;
  state = other39.state;
  self = other39.self;
  completedDriverGroups = other39.completedDriverGroups;
  failures = other39.failures;
  queuedPartitionedDrivers = other39.queuedPartitionedDrivers;
  runningPartitionedDrivers = other39.runningPartitionedDrivers;
  outputBufferUtilization = other39.outputBufferUtilization;
  outputBufferOverutilized = other39.outputBufferOverutilized;
  physicalWrittenDataSizeInBytes = other39.physicalWrittenDataSizeInBytes;
  memoryReservationInBytes = other39.memoryReservationInBytes;
  systemMemoryReservationInBytes = other39.systemMemoryReservationInBytes;
  peakNodeTotalMemoryReservationInBytes = other39.peakNodeTotalMemoryReservationInBytes;
  fullGcCount = other39.fullGcCount;
  fullGcTimeInMillis = other39.fullGcTimeInMillis;
  totalCpuTimeInNanos = other39.totalCpuTimeInNanos;
  taskAgeInMillis = other39.taskAgeInMillis;
  queuedPartitionedSplitsWeight = other39.queuedPartitionedSplitsWeight;
  runningPartitionedSplitsWeight = other39.runningPartitionedSplitsWeight;
  __isset = other39.__isset;
  return *this;
}
void ThriftTaskStatus::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ThriftTaskStatus(";
  out << "taskInstanceIdLeastSignificantBits=" << to_string(taskInstanceIdLeastSignificantBits);
  out << ", " << "taskInstanceIdMostSignificantBits=" << to_string(taskInstanceIdMostSignificantBits);
  out << ", " << "version=" << to_string(version);
  out << ", " << "state=" << to_string(state);
  out << ", " << "self=" << to_string(self);
  out << ", " << "completedDriverGroups=" << to_string(completedDriverGroups);
  out << ", " << "failures=" << to_string(failures);
  out << ", " << "queuedPartitionedDrivers=" << to_string(queuedPartitionedDrivers);
  out << ", " << "runningPartitionedDrivers=" << to_string(runningPartitionedDrivers);
  out << ", " << "outputBufferUtilization=" << to_string(outputBufferUtilization);
  out << ", " << "outputBufferOverutilized=" << to_string(outputBufferOverutilized);
  out << ", " << "physicalWrittenDataSizeInBytes=" << to_string(physicalWrittenDataSizeInBytes);
  out << ", " << "memoryReservationInBytes=" << to_string(memoryReservationInBytes);
  out << ", " << "systemMemoryReservationInBytes=" << to_string(systemMemoryReservationInBytes);
  out << ", " << "peakNodeTotalMemoryReservationInBytes=" << to_string(peakNodeTotalMemoryReservationInBytes);
  out << ", " << "fullGcCount=" << to_string(fullGcCount);
  out << ", " << "fullGcTimeInMillis=" << to_string(fullGcTimeInMillis);
  out << ", " << "totalCpuTimeInNanos=" << to_string(totalCpuTimeInNanos);
  out << ", " << "taskAgeInMillis=" << to_string(taskAgeInMillis);
  out << ", " << "queuedPartitionedSplitsWeight=" << to_string(queuedPartitionedSplitsWeight);
  out << ", " << "runningPartitionedSplitsWeight=" << to_string(runningPartitionedSplitsWeight);
  out << ")";
}

} // namespace
