/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftDataType_TYPES_H
#define ThriftDataType_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace protocol {

struct ThriftTaskState {
  enum type {
    PLANNED = 0,
    RUNNING = 1,
    FINISHED = 2,
    CANCELED = 3,
    ABORTED = 4,
    FAILED = 5
  };
};

extern const std::map<int, const char*> _ThriftTaskState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ThriftTaskState::type& val);

std::string to_string(const ThriftTaskState::type& val);

struct ThriftErrorCause {
  enum type {
    UNKNOWN = 0,
    LOW_PARTITION_COUNT = 1,
    EXCEEDS_BROADCAST_MEMORY_LIMIT = 2
  };
};

extern const std::map<int, const char*> _ThriftErrorCause_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ThriftErrorCause::type& val);

std::string to_string(const ThriftErrorCause::type& val);

struct ThriftErrorType {
  enum type {
    USER_ERROR = 0,
    INTERNAL_ERROR = 1,
    INSUFFICIENT_RESOURCES = 2,
    EXTERNAL = 3
  };
};

extern const std::map<int, const char*> _ThriftErrorType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ThriftErrorType::type& val);

std::string to_string(const ThriftErrorType::type& val);

class ThriftLifespan;

class ThriftErrorCode;

class ThriftErrorLocation;

class ThriftHostAddress;

class ThriftExecutionFailureInfo;

class ThriftTaskStatus;

typedef struct _ThriftLifespan__isset {
  _ThriftLifespan__isset() : grouped(false), groupId(false) {}
  bool grouped :1;
  bool groupId :1;
} _ThriftLifespan__isset;

class ThriftLifespan : public virtual ::apache::thrift::TBase {
 public:

  ThriftLifespan(const ThriftLifespan&) noexcept;
  ThriftLifespan& operator=(const ThriftLifespan&) noexcept;
  ThriftLifespan() noexcept;

  virtual ~ThriftLifespan() noexcept;
  bool grouped;
  int32_t groupId;

  _ThriftLifespan__isset __isset;

  void __set_grouped(const bool val);

  void __set_groupId(const int32_t val);

  bool operator == (const ThriftLifespan & rhs) const;
  bool operator != (const ThriftLifespan &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftLifespan & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftLifespan &a, ThriftLifespan &b);

std::ostream& operator<<(std::ostream& out, const ThriftLifespan& obj);

typedef struct _ThriftErrorCode__isset {
  _ThriftErrorCode__isset() : code(false), name(false), type(false), retriable(false) {}
  bool code :1;
  bool name :1;
  bool type :1;
  bool retriable :1;
} _ThriftErrorCode__isset;

class ThriftErrorCode : public virtual ::apache::thrift::TBase {
 public:

  ThriftErrorCode(const ThriftErrorCode&);
  ThriftErrorCode& operator=(const ThriftErrorCode&);
  ThriftErrorCode() noexcept;

  virtual ~ThriftErrorCode() noexcept;
  int32_t code;
  std::string name;
  /**
   * 
   * @see ThriftErrorType
   */
  ThriftErrorType::type type;
  bool retriable;

  _ThriftErrorCode__isset __isset;

  void __set_code(const int32_t val);

  void __set_name(const std::string& val);

  void __set_type(const ThriftErrorType::type val);

  void __set_retriable(const bool val);

  bool operator == (const ThriftErrorCode & rhs) const;
  bool operator != (const ThriftErrorCode &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftErrorCode & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftErrorCode &a, ThriftErrorCode &b);

std::ostream& operator<<(std::ostream& out, const ThriftErrorCode& obj);

typedef struct _ThriftErrorLocation__isset {
  _ThriftErrorLocation__isset() : lineNumber(false), columnNumber(false) {}
  bool lineNumber :1;
  bool columnNumber :1;
} _ThriftErrorLocation__isset;

class ThriftErrorLocation : public virtual ::apache::thrift::TBase {
 public:

  ThriftErrorLocation(const ThriftErrorLocation&) noexcept;
  ThriftErrorLocation& operator=(const ThriftErrorLocation&) noexcept;
  ThriftErrorLocation() noexcept;

  virtual ~ThriftErrorLocation() noexcept;
  int32_t lineNumber;
  int32_t columnNumber;

  _ThriftErrorLocation__isset __isset;

  void __set_lineNumber(const int32_t val);

  void __set_columnNumber(const int32_t val);

  bool operator == (const ThriftErrorLocation & rhs) const;
  bool operator != (const ThriftErrorLocation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftErrorLocation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftErrorLocation &a, ThriftErrorLocation &b);

std::ostream& operator<<(std::ostream& out, const ThriftErrorLocation& obj);

typedef struct _ThriftHostAddress__isset {
  _ThriftHostAddress__isset() : host(false), port(false) {}
  bool host :1;
  bool port :1;
} _ThriftHostAddress__isset;

class ThriftHostAddress : public virtual ::apache::thrift::TBase {
 public:

  ThriftHostAddress(const ThriftHostAddress&);
  ThriftHostAddress& operator=(const ThriftHostAddress&);
  ThriftHostAddress() noexcept;

  virtual ~ThriftHostAddress() noexcept;
  std::string host;
  int32_t port;

  _ThriftHostAddress__isset __isset;

  void __set_host(const std::string& val);

  void __set_port(const int32_t val);

  bool operator == (const ThriftHostAddress & rhs) const;
  bool operator != (const ThriftHostAddress &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftHostAddress & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftHostAddress &a, ThriftHostAddress &b);

std::ostream& operator<<(std::ostream& out, const ThriftHostAddress& obj);

typedef struct _ThriftExecutionFailureInfo__isset {
  _ThriftExecutionFailureInfo__isset() : type(false), message(false), cause(false), suppressed(false), stack(false), errorLocation(false), errorCode(false), remoteHost(false), errorCause(false) {}
  bool type :1;
  bool message :1;
  bool cause :1;
  bool suppressed :1;
  bool stack :1;
  bool errorLocation :1;
  bool errorCode :1;
  bool remoteHost :1;
  bool errorCause :1;
} _ThriftExecutionFailureInfo__isset;

class ThriftExecutionFailureInfo : public virtual ::apache::thrift::TBase {
 public:

  ThriftExecutionFailureInfo(const ThriftExecutionFailureInfo&);
  ThriftExecutionFailureInfo& operator=(const ThriftExecutionFailureInfo&);
  ThriftExecutionFailureInfo() noexcept;

  virtual ~ThriftExecutionFailureInfo() noexcept;
  std::string type;
  std::string message;
  ThriftExecutionFailureInfo cause;
  std::vector<ThriftExecutionFailureInfo>  suppressed;
  std::vector<std::string>  stack;
  ThriftErrorLocation errorLocation;
  ThriftErrorCode errorCode;
  ThriftHostAddress remoteHost;
  /**
   * 
   * @see ThriftErrorCause
   */
  ThriftErrorCause::type errorCause;

  _ThriftExecutionFailureInfo__isset __isset;

  void __set_type(const std::string& val);

  void __set_message(const std::string& val);

  void __set_cause(const ThriftExecutionFailureInfo& val);

  void __set_suppressed(const std::vector<ThriftExecutionFailureInfo> & val);

  void __set_stack(const std::vector<std::string> & val);

  void __set_errorLocation(const ThriftErrorLocation& val);

  void __set_errorCode(const ThriftErrorCode& val);

  void __set_remoteHost(const ThriftHostAddress& val);

  void __set_errorCause(const ThriftErrorCause::type val);

  bool operator == (const ThriftExecutionFailureInfo & rhs) const;
  bool operator != (const ThriftExecutionFailureInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftExecutionFailureInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftExecutionFailureInfo &a, ThriftExecutionFailureInfo &b);

std::ostream& operator<<(std::ostream& out, const ThriftExecutionFailureInfo& obj);

typedef struct _ThriftTaskStatus__isset {
  _ThriftTaskStatus__isset() : taskInstanceIdLeastSignificantBits(false), taskInstanceIdMostSignificantBits(false), version(false), state(false), self(false), completedDriverGroups(false), failures(false), queuedPartitionedDrivers(false), runningPartitionedDrivers(false), outputBufferUtilization(false), outputBufferOverutilized(false), physicalWrittenDataSizeInBytes(false), memoryReservationInBytes(false), systemMemoryReservationInBytes(false), peakNodeTotalMemoryReservationInBytes(false), fullGcCount(false), fullGcTimeInMillis(false), totalCpuTimeInNanos(false), taskAgeInMillis(false), queuedPartitionedSplitsWeight(false), runningPartitionedSplitsWeight(false) {}
  bool taskInstanceIdLeastSignificantBits :1;
  bool taskInstanceIdMostSignificantBits :1;
  bool version :1;
  bool state :1;
  bool self :1;
  bool completedDriverGroups :1;
  bool failures :1;
  bool queuedPartitionedDrivers :1;
  bool runningPartitionedDrivers :1;
  bool outputBufferUtilization :1;
  bool outputBufferOverutilized :1;
  bool physicalWrittenDataSizeInBytes :1;
  bool memoryReservationInBytes :1;
  bool systemMemoryReservationInBytes :1;
  bool peakNodeTotalMemoryReservationInBytes :1;
  bool fullGcCount :1;
  bool fullGcTimeInMillis :1;
  bool totalCpuTimeInNanos :1;
  bool taskAgeInMillis :1;
  bool queuedPartitionedSplitsWeight :1;
  bool runningPartitionedSplitsWeight :1;
} _ThriftTaskStatus__isset;

class ThriftTaskStatus : public virtual ::apache::thrift::TBase {
 public:

  ThriftTaskStatus(const ThriftTaskStatus&);
  ThriftTaskStatus& operator=(const ThriftTaskStatus&);
  ThriftTaskStatus() noexcept;

  virtual ~ThriftTaskStatus() noexcept;
  int64_t taskInstanceIdLeastSignificantBits;
  int64_t taskInstanceIdMostSignificantBits;
  int64_t version;
  /**
   * 
   * @see ThriftTaskState
   */
  ThriftTaskState::type state;
  std::string self;
  std::set<ThriftLifespan>  completedDriverGroups;
  std::vector<ThriftExecutionFailureInfo>  failures;
  int32_t queuedPartitionedDrivers;
  int32_t runningPartitionedDrivers;
  double outputBufferUtilization;
  bool outputBufferOverutilized;
  int64_t physicalWrittenDataSizeInBytes;
  int64_t memoryReservationInBytes;
  int64_t systemMemoryReservationInBytes;
  int64_t peakNodeTotalMemoryReservationInBytes;
  int64_t fullGcCount;
  int64_t fullGcTimeInMillis;
  int64_t totalCpuTimeInNanos;
  int64_t taskAgeInMillis;
  int64_t queuedPartitionedSplitsWeight;
  int64_t runningPartitionedSplitsWeight;

  _ThriftTaskStatus__isset __isset;

  void __set_taskInstanceIdLeastSignificantBits(const int64_t val);

  void __set_taskInstanceIdMostSignificantBits(const int64_t val);

  void __set_version(const int64_t val);

  void __set_state(const ThriftTaskState::type val);

  void __set_self(const std::string& val);

  void __set_completedDriverGroups(const std::set<ThriftLifespan> & val);

  void __set_failures(const std::vector<ThriftExecutionFailureInfo> & val);

  void __set_queuedPartitionedDrivers(const int32_t val);

  void __set_runningPartitionedDrivers(const int32_t val);

  void __set_outputBufferUtilization(const double val);

  void __set_outputBufferOverutilized(const bool val);

  void __set_physicalWrittenDataSizeInBytes(const int64_t val);

  void __set_memoryReservationInBytes(const int64_t val);

  void __set_systemMemoryReservationInBytes(const int64_t val);

  void __set_peakNodeTotalMemoryReservationInBytes(const int64_t val);

  void __set_fullGcCount(const int64_t val);

  void __set_fullGcTimeInMillis(const int64_t val);

  void __set_totalCpuTimeInNanos(const int64_t val);

  void __set_taskAgeInMillis(const int64_t val);

  void __set_queuedPartitionedSplitsWeight(const int64_t val);

  void __set_runningPartitionedSplitsWeight(const int64_t val);

  bool operator == (const ThriftTaskStatus & rhs) const;
  bool operator != (const ThriftTaskStatus &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ThriftTaskStatus & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ThriftTaskStatus &a, ThriftTaskStatus &b);

std::ostream& operator<<(std::ostream& out, const ThriftTaskStatus& obj);

} // namespace

#endif
